; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=tricore -global-isel -stop-after=irtranslator -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

define void @ret_void() {
  ; CHECK-LABEL: name: ret_void
  ; CHECK: bb.1.entry:
  ; CHECK:   RET implicit $a11
entry:
  ret void
}

define zeroext i1 @ret_ui1(i1 zeroext %d4) {
  ; CHECK-LABEL: name: ret_ui1
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[TRUNC]](s1)
  ; CHECK:   $d2 = COPY [[ZEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i1 %d4
}

define zeroext i8 @ret_ui8(i8 zeroext %i)  {
  ; CHECK-LABEL: name: ret_ui8
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[TRUNC]](s8)
  ; CHECK:   $d2 = COPY [[ZEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i8 %i
}

define signext i8 @ret_i8(i8 signext %i) {
  ; CHECK-LABEL: name: ret_i8
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s8)
  ; CHECK:   $d2 = COPY [[SEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i8 %i
}

define zeroext i16 @ret_ui16(i16 zeroext %i) {
  ; CHECK-LABEL: name: ret_ui16
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[TRUNC]](s16)
  ; CHECK:   $d2 = COPY [[ZEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i16 %i
}

define signext i16 @ret_i16(i16 signext %i) {
  ; CHECK-LABEL: name: ret_i16
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[SEXT:%[0-9]+]]:_(s32) = G_SEXT [[TRUNC]](s16)
  ; CHECK:   $d2 = COPY [[SEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i16 %i
}

define i32 @ret_i32(i32 %i) {
  ; CHECK-LABEL: name: ret_i32
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   $d2 = COPY [[COPY]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i32 %i
}

define half @ret_half(half %i) {
  ; CHECK-LABEL: name: ret_half
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[TRUNC]](s16)
  ; CHECK:   $d2 = COPY [[ANYEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret half %i
}

define float @ret_float(float %i) {
  ; CHECK-LABEL: name: ret_float
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   $d2 = COPY [[COPY]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret float %i
}

define double @ret_double(double %i) {
  ; CHECK-LABEL: name: ret_double
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $e4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s64) = COPY $e4
  ; CHECK:   $e2 = COPY [[COPY]](s64)
  ; CHECK:   RET implicit $a11, implicit $e2
entry:
  ret double %i
}

define i32 @args_i32(i32 %d4, i32 %d5, i32 %d6, i32 %d7) {
  ; CHECK-LABEL: name: args_i32
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $d6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   $d2 = COPY [[COPY]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i32 %d4
}

define i64 @ret_i64(i64 %i) {
  ; CHECK-LABEL: name: ret_i64
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $e4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s64) = COPY $e4
  ; CHECK:   $e2 = COPY [[COPY]](s64)
  ; CHECK:   RET implicit $a11, implicit $e2
entry:
  ret i64 %i
}

define i64 @args_i64(i64 %e4, i64 %e6) {
  ; CHECK-LABEL: name: args_i64
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $e4, $e6
  ; CHECK:   [[COPY:%[0-9]+]]:_(s64) = COPY $e4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
  ; CHECK:   $e2 = COPY [[COPY]](s64)
  ; CHECK:   RET implicit $a11, implicit $e2
entry:
  ret i64 %e4
}

define i32 @args_i32_i64_i32(i32 %d4, i64 %e6, i32 %d5) {
  ; CHECK-LABEL: name: args_i32_i64_i32
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $e6
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   $d2 = COPY [[COPY2]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i32 %d5
}

define i64 @args_i64_i32(i64 %e4, i32 %d6) {
  ; CHECK-LABEL: name: args_i64_i32
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d6, $e4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s64) = COPY $e4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   $e2 = COPY [[COPY]](s64)
  ; CHECK:   RET implicit $a11, implicit $e2
entry:
  ret i64 %e4
}

define i32* @ret_i32_ptr(i32* %p) {
  ; CHECK-LABEL: name: ret_i32_ptr
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $a4
  ; CHECK:   [[COPY:%[0-9]+]]:_(p0) = COPY $a4
  ; CHECK:   $a2 = COPY [[COPY]](p0)
  ; CHECK:   RET implicit $a11, implicit $a2
entry:
  ret i32* %p
}

define i32* @args_ptr(i32* %a4, i32* %a5, i32* %a6, i32* %a7) {
  ; CHECK-LABEL: name: args_ptr
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $a4, $a5, $a6, $a7
  ; CHECK:   [[COPY:%[0-9]+]]:_(p0) = COPY $a4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(p0) = COPY $a5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(p0) = COPY $a6
  ; CHECK:   [[COPY3:%[0-9]+]]:_(p0) = COPY $a7
  ; CHECK:   $a2 = COPY [[COPY]](p0)
  ; CHECK:   RET implicit $a11, implicit $a2
entry:
  ret i32* %a4
}

define float @args_floats(half %d4, float %d5, double %e6) {
  ; CHECK-LABEL: name: args_floats
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $e6
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s64) = COPY $e6
  ; CHECK:   $d2 = COPY [[COPY1]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret float %d5
}

define i32 @args_struct_1([1 x i32] %d4) {
  ; CHECK-LABEL: name: args_struct_1
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   $d2 = COPY [[COPY]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  %d4.extract = extractvalue [1 x i32] %d4, 0
  ret i32 %d4.extract
}

define i32 @args_struct_2([2 x i32] %e4) {
  ; CHECK-LABEL: name: args_struct_2
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   $d2 = COPY [[COPY]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  %e4.extract = extractvalue [2 x i32] %e4, 0
  ret i32 %e4.extract
}

define i32 @args_i32_struct_i32(i32 %d4, [2 x i32] %e6, i32 %d5) {
  ; CHECK-LABEL: name: args_i32_struct_i32
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $d6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   $d2 = COPY [[COPY1]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  %e6.extract = extractvalue [2 x i32] %e6, 0
  ret i32 %e6.extract
}

define [2 x i32] @ret_struct([2 x i32] %e4) {
  ; CHECK-LABEL: name: ret_struct
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   $d2 = COPY [[COPY]](s32)
  ; CHECK:   $d3 = COPY [[COPY1]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2, implicit $d3
entry:
  ret [2 x i32] %e4
}

define i32 @args_stack1(i32 %d4, i32 %d5, i32 %d6, i32 %d7, i32 %stack1, i64 %stack2) {
  ; CHECK-LABEL: name: args_stack1
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $d6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load 4 from %fixed-stack.1, align 8)
  ; CHECK:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK:   [[LOAD1:%[0-9]+]]:_(s64) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load 8 from %fixed-stack.0, align 4)
  ; CHECK:   $d2 = COPY [[LOAD]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i32 %stack1
}

define i32 @args_stack2(i32 %d4, i32 %d5, i32 %d6, i32 %d7, [2 x i32] %stack1, i32 %stack2) {
  ; CHECK-LABEL: name: args_stack2
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $d6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load 4 from %fixed-stack.2, align 8)
  ; CHECK:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load 4 from %fixed-stack.1)
  ; CHECK:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK:   [[LOAD2:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load 4 from %fixed-stack.0, align 8)
  ; CHECK:   $d2 = COPY [[LOAD]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  %stack1.extract = extractvalue [2 x i32] %stack1, 0
  ret i32 %stack1.extract
}

define i32 @args_stack3(i32 %d4, i32 %d5, i32 %d6, [2 x i32] %stack1, i32 %d7) {
  ; CHECK-LABEL: name: args_stack3
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $d6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load 4 from %fixed-stack.1, align 8)
  ; CHECK:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load 4 from %fixed-stack.0)
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   $d2 = COPY [[LOAD]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  %stack1.extract = extractvalue [2 x i32] %stack1, 0
  ret i32 %stack1.extract
}

define i32* @args_stack4(i32* %a4, i32 %d4, i32* %a5, i32 %d5, i32* %a6, i32 %d6, i32* %a7, i32 %d7, i32* %stack1, i32 %stack2) {
  ; CHECK-LABEL: name: args_stack4
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $a4, $a5, $a6, $a7, $d4, $d5, $d6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(p0) = COPY $a4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY2:%[0-9]+]]:_(p0) = COPY $a5
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY4:%[0-9]+]]:_(p0) = COPY $a6
  ; CHECK:   [[COPY5:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[COPY6:%[0-9]+]]:_(p0) = COPY $a7
  ; CHECK:   [[COPY7:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK:   [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load 4 from %fixed-stack.1, align 8)
  ; CHECK:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load 4 from %fixed-stack.0)
  ; CHECK:   $a2 = COPY [[LOAD]](p0)
  ; CHECK:   RET implicit $a11, implicit $a2
entry:
  ret i32* %stack1
}

define zeroext i8 @args_stack_mixed(i32 %d4, i32 %d5, i32 %d6, i32 %d7, i1 zeroext %stack1, i8 zeroext %stack2, i16 signext %stack3) {
  ; CHECK-LABEL: name: args_stack_mixed
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $d6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK:   [[LOAD:%[0-9]+]]:_(s1) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load 1 from %fixed-stack.2, align 8)
  ; CHECK:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK:   [[LOAD1:%[0-9]+]]:_(s8) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load 1 from %fixed-stack.1, align 4)
  ; CHECK:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK:   [[LOAD2:%[0-9]+]]:_(s16) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load 2 from %fixed-stack.0, align 8)
  ; CHECK:   [[ZEXT:%[0-9]+]]:_(s32) = G_ZEXT [[LOAD1]](s8)
  ; CHECK:   $d2 = COPY [[ZEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret i8 %stack2
}

define half @args_stack_floats_mixed(half %d4, float %d5, double %e6, half %stack1, float %stack2, double %stack3) {
  ; CHECK-LABEL: name: args_stack_floats_mixed
  ; CHECK: bb.1.entry:
  ; CHECK:   liveins: $d4, $d5, $e6
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s64) = COPY $e6
  ; CHECK:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.2
  ; CHECK:   [[LOAD:%[0-9]+]]:_(s16) = G_LOAD [[FRAME_INDEX]](p0) :: (invariant load 2 from %fixed-stack.2, align 8)
  ; CHECK:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (invariant load 4 from %fixed-stack.1)
  ; CHECK:   [[FRAME_INDEX2:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK:   [[LOAD2:%[0-9]+]]:_(s64) = G_LOAD [[FRAME_INDEX2]](p0) :: (invariant load 8 from %fixed-stack.0)
  ; CHECK:   [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[LOAD]](s16)
  ; CHECK:   $d2 = COPY [[ANYEXT]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
entry:
  ret half %stack1
}
