# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
---
name:            test_legal_implicit_def
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_legal_implicit_def
    ; CHECK: [[DEF:%[0-9]+]]:_(p0) = G_IMPLICIT_DEF
    ; CHECK: $a2 = COPY [[DEF]](p0)
    ; CHECK: [[DEF1:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: $d2 = COPY [[COPY]](s32)
    ; CHECK: [[DEF2:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[DEF2]](s32)
    ; CHECK: $d2 = COPY [[COPY1]](s32)
    ; CHECK: [[DEF3:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[DEF3]](s32)
    ; CHECK: $d2 = COPY [[COPY2]](s32)
    ; CHECK: [[DEF4:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: $d2 = COPY [[DEF4]](s32)
    ; CHECK: [[DEF5:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: $e2 = COPY [[DEF5]](s64)
    %0:_(p0) = G_IMPLICIT_DEF
    $a2 = COPY %0(p0)
    %1:_(s1) = G_IMPLICIT_DEF
    %2:_(s32) = G_ANYEXT %1:_(s1)
    $d2 = COPY %2(s32)
    %3:_(s8) = G_IMPLICIT_DEF
    %4:_(s32) = G_ANYEXT %3:_(s8)
    $d2 = COPY %4(s32)
    %5:_(s16) = G_IMPLICIT_DEF
    %6:_(s32) = G_ANYEXT %5:_(s16)
    $d2 = COPY %6(s32)
    %7:_(s32) = G_IMPLICIT_DEF
    $d2 = COPY %7(s32)
    %8:_(s64) = G_IMPLICIT_DEF
    $e2 = COPY %8(s64)
...
---
name:            test_other_implicit_def
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_other_implicit_def
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK: $d2 = COPY [[COPY]](s32)
    ; CHECK: [[DEF1:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[DEF2:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[DEF3:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: $e2 = COPY [[DEF1]](s64)
    ; CHECK: $e2 = COPY [[DEF2]](s64)
    ; CHECK: $e2 = COPY [[DEF3]](s64)
    %0:_(s3) = G_IMPLICIT_DEF
    %1:_(s32) = G_ANYEXT %0:_(s3)
    $d2 = COPY %1(s32)
    %2:_(s192) = G_IMPLICIT_DEF
    %3:_(s64), %4:_(s64), %5:_(s64) = G_UNMERGE_VALUES %2:_(s192)
    $e2 = COPY %3(s64)
    $e2 = COPY %4(s64)
    $e2 = COPY %5(s64)
...
