# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_ext
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_ext
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[TRUNC]], 1
    ; CHECK: G_STORE [[SEXT_INREG]](s32), [[COPY1]](p0) :: (store 1)
    ; CHECK: [[TRUNC1:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[TRUNC1]], 1
    ; CHECK: G_STORE [[SEXT_INREG1]](s32), [[COPY1]](p0) :: (store 2)
    ; CHECK: [[TRUNC2:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[SEXT_INREG2:%[0-9]+]]:_(s32) = G_SEXT_INREG [[TRUNC2]], 8
    ; CHECK: G_STORE [[SEXT_INREG2]](s32), [[COPY1]](p0) :: (store 2)
    ; CHECK: [[TRUNC3:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: $d4 = COPY [[TRUNC3]](s32)
    ; CHECK: [[TRUNC4:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: $d4 = COPY [[TRUNC4]](s32)
    ; CHECK: [[TRUNC5:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: $d4 = COPY [[TRUNC5]](s32)
    ; CHECK: [[TRUNC6:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: $d4 = COPY [[TRUNC6]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: $e4 = COPY [[COPY2]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 255
    ; CHECK: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY3]](s64)
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C]](s64)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[UV]], [[UV2]]
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV1]], [[UV3]]
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[AND]](s32), [[AND1]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    ; CHECK: [[COPY4:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: $e4 = COPY [[COPY4]](s64)
    ; CHECK: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[SEXT_INREG3:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY5]], 32
    ; CHECK: $e4 = COPY [[SEXT_INREG3]](s64)
    ; CHECK: [[TRUNC7:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[SEXT_INREG4:%[0-9]+]]:_(s32) = G_SEXT_INREG [[TRUNC7]], 1
    ; CHECK: $d4 = COPY [[SEXT_INREG4]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[TRUNC8:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[TRUNC8]], [[C1]]
    ; CHECK: $d4 = COPY [[AND2]](s32)
    ; CHECK: [[TRUNC9:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: $d4 = COPY [[TRUNC9]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[TRUNC10:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[AND3:%[0-9]+]]:_(s32) = G_AND [[TRUNC10]], [[C2]]
    ; CHECK: $d4 = COPY [[AND3]](s32)
    ; CHECK: [[TRUNC11:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: $d4 = COPY [[TRUNC11]](s32)
    ; CHECK: [[TRUNC12:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[SEXT_INREG5:%[0-9]+]]:_(s32) = G_SEXT_INREG [[TRUNC12]], 16
    ; CHECK: $d4 = COPY [[SEXT_INREG5]](s32)
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[TRUNC13:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[AND4:%[0-9]+]]:_(s32) = G_AND [[TRUNC13]], [[C3]]
    ; CHECK: $d4 = COPY [[AND4]](s32)
    ; CHECK: [[TRUNC14:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: $d4 = COPY [[TRUNC14]](s32)
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK: [[AND5:%[0-9]+]]:_(s32) = G_AND [[COPY6]], [[C4]]
    ; CHECK: $d4 = COPY [[AND5]](s32)
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK: [[SEXT_INREG6:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY7]], 16
    ; CHECK: $d4 = COPY [[SEXT_INREG6]](s32)
    ; CHECK: [[COPY8:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK: $d4 = COPY [[COPY8]](s32)
    ; CHECK: [[COPY9:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[COPY9]](s32)
    ; CHECK: $e4 = COPY [[ANYEXT]](s64)
    ; CHECK: [[COPY10:%[0-9]+]]:_(s32) = COPY [[TRUNC6]](s32)
    ; CHECK: [[SEXT_INREG7:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY10]], 5
    ; CHECK: $d4 = COPY [[SEXT_INREG7]](s32)
    ; CHECK: [[COPY11:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: $e4 = COPY [[COPY11]](s64)
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[COPY12:%[0-9]+]]:_(s32) = COPY [[TRUNC6]](s32)
    ; CHECK: [[AND6:%[0-9]+]]:_(s32) = G_AND [[COPY12]], [[C5]]
    ; CHECK: G_STORE [[AND6]](s32), [[COPY1]](p0) :: (store 1)
    %0:_(s64) = COPY $e4
    %30:_(p0) = COPY $a4
    %1:_(s1) = G_TRUNC %0(s64)
    %2:_(s8) = G_TRUNC %0(s64)
    %31:_(s8) = G_SEXT%1(s1)
    G_STORE %31(s8), %30(p0) :: (store 1)
    %32:_(s16) = G_SEXT%1(s1)
    G_STORE %32(s16), %30(p0) :: (store 2)
    %33:_(s16) = G_SEXT%2(s8)
    G_STORE %33(s16), %30(p0) :: (store 2)
    %19:_(s32) = G_ANYEXT %1(s1)
    $d4 = COPY %19(s32)
    %20:_(s32) = G_ANYEXT %2(s8)
    $d4 = COPY %20(s32)
    %3:_(s16) = G_TRUNC %0(s64)
    %21:_(s32) = G_ANYEXT %3(s16)
    $d4 = COPY %21(s32)
    %4:_(s32) = G_TRUNC %0(s64)
    $d4 = COPY %4(s32)
    %5:_(s64) = G_ANYEXT %1(s1)
    $e4 = COPY %5(s64)
    %6:_(s64) = G_ZEXT %2(s8)
    $e4 = COPY %6(s64)
    %7:_(s64) = G_ANYEXT %3(s16)
    $e4 = COPY %7(s64)
    %8:_(s64) = G_SEXT %4(s32)
    $e4 = COPY %8(s64)
    %9:_(s32) = G_SEXT %1(s1)
    $d4 = COPY %9(s32)
    %10:_(s32) = G_ZEXT %2(s8)
    $d4 = COPY %10(s32)
    %11:_(s32) = G_ANYEXT %3(s16)
    $d4 = COPY %11(s32)
    %12:_(s32) = G_ZEXT %1(s1)
    $d4 = COPY %12(s32)
    %13:_(s32) = G_ANYEXT %2(s8)
    $d4 = COPY %13(s32)
    %14:_(s32) = G_SEXT %3(s16)
    $d4 = COPY %14(s32)
    %15:_(s8) = G_ZEXT %1(s1)
    %22:_(s32) = G_ANYEXT %15(s8)
    $d4 = COPY %22(s32)
    %16:_(s16) = G_ANYEXT %2(s8)
    %23:_(s32) = G_ANYEXT %16(s16)
    $d4 = COPY %23(s32)
    %24:_(s16) = G_IMPLICIT_DEF
    %25:_(s32) = G_ZEXT %24(s16)
    $d4 = COPY %25(s32)
    %26:_(s32) = G_SEXT %24(s16)
    $d4 = COPY %26(s32)
    %27:_(s32) = G_ANYEXT %24(s16)
    $d4 = COPY %27(s32)
    %28:_(s32) = COPY $d4
    %29:_(s64) = G_ANYEXT %28(s32)
    $e4 = COPY %29(s64)
    %34:_(s5) = G_TRUNC %4(s32)
    %35:_(s32) = G_SEXT %34(s5)
    $d4 = COPY %35(s32)
    %36:_(s64) = G_ANYEXT %34(s5)
    $e4 = COPY %36(s64)
    %37:_(s12) = G_ZEXT %34(s5)
    G_STORE %37(s12), %30(p0) :: (store 1)
...

---
name:            test_anyext_anyext
body:             |
  bb.0:
    liveins: $d4

    ; CHECK-LABEL: name: test_anyext_anyext
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: $d4 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s1) = G_TRUNC %0(s32)
    %2:_(s8) = G_ANYEXT %1(s1)
    %3:_(s32) = G_ANYEXT %2(s8)
    $d4 = COPY %3(s32)
...

---
name:            test_anyext_sext
body:             |
  bb.0:
    liveins: $d4

    ; CHECK-LABEL: name: test_anyext_sext
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 1
    ; CHECK: $d4 = COPY [[SEXT_INREG]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s1) = G_TRUNC %0(s32)
    %2:_(s8) = G_SEXT %1(s1)
    %3:_(s32) = G_ANYEXT %2(s8)
    $d4 = COPY %3(s32)
...

---
name:            test_anyext_zext
body:             |
  bb.0:
    liveins: $d4

    ; CHECK-LABEL: name: test_anyext_zext
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK: $d4 = COPY [[AND]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s1) = G_TRUNC %0(s32)
    %2:_(s8) = G_ZEXT %1(s1)
    %3:_(s32) = G_ANYEXT %2(s8)
    $d4 = COPY %3(s32)
...

---
name:            test_sext_inreg
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_sext_inreg
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[DEF]], 16
    ; CHECK: $d4 = COPY [[SEXT_INREG]](s32)
    ; CHECK: [[DEF1:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[DEF1]], 16
    ; CHECK: $e4 = COPY [[SEXT_INREG1]](s64)
    %0:_(s32) = G_IMPLICIT_DEF
    %1:_(s32) = G_SEXT_INREG %0(s32), 16
    $d4 = COPY %1(s32)
    %2:_(s64) = G_IMPLICIT_DEF
    %3:_(s64) = G_SEXT_INREG %2(s64), 16
    $e4 = COPY %3(s64)
...
