# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

--- |
  source_filename = "t15_20acase1.i"
  target datalayout = "e-m:e-i64:32-p:32:32-f64:32-n32-a:0:32-S64"
  target triple = "tricore"

  %struct.b = type { [9 x i8], i8 }

  define dso_local i32 @supertest_t15_20acase1() {
  entry:
    %e = alloca %struct.b, align 2
    %0 = bitcast %struct.b* %e to i72*
    %bf.load = load i72, i72* %0, align 2
    %bf.shl = shl i72 %bf.load, 7
    %bf.ashr = ashr i72 %bf.shl, 66
    %bf.cast = trunc i72 %bf.ashr to i32
    call void bitcast (void (...)* @a to void (i32)*)(i32 %bf.cast)
    ret i32 0
  }

  declare dso_local void @a(...)

...
---
name:            supertest_t15_20acase1
tracksRegLiveness: true
stack:
  - { id: 0, name: e, type: default, offset: 0, size: 10, alignment: 2,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: supertest_t15_20acase1
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 7
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[DEF1:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF1]](s64)
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C]](s64)
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY [[UV2]](s32)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C]](s64)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[UV5]](s32)
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY2]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[C1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY4]], [[C2]]
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -256
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV]], [[C3]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 66
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[DEF2:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[DEF3:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF3]](s64)
    ; CHECK: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C4]](s64)
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[UV8]](s32)
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[COPY6]](s32)
    ; CHECK: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C4]](s64)
    ; CHECK: [[COPY8:%[0-9]+]]:_(s32) = COPY [[UV11]](s32)
    ; CHECK: [[COPY9:%[0-9]+]]:_(s32) = COPY [[COPY8]](s32)
    ; CHECK: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY10:%[0-9]+]]:_(s32) = COPY [[C5]](s32)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[COPY10]], [[C6]]
    ; CHECK: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 -256
    ; CHECK: [[AND3:%[0-9]+]]:_(s32) = G_AND [[UV6]], [[C7]]
    ; CHECK: [[OR1:%[0-9]+]]:_(s32) = G_OR [[AND3]], [[AND2]]
    ; CHECK: [[COPY11:%[0-9]+]]:_(s32) = COPY [[OR1]](s32)
    ; CHECK: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.e
    ; CHECK: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[FRAME_INDEX]](p0) :: (dereferenceable load 8 from %ir.0, align 2)
    ; CHECK: [[C9:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[FRAME_INDEX]], [[C10]](s32)
    ; CHECK: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load 1 from %ir.0 + 8, align 2)
    ; CHECK: [[DEF4:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[DEF5:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[C11:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 64
    ; CHECK: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 64
    ; CHECK: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C12]], [[C13]]
    ; CHECK: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[C13]], [[C12]]
    ; CHECK: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[C12]](s32), [[C13]]
    ; CHECK: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C12]](s32), [[C14]]
    ; CHECK: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[C12]], [[C15]]
    ; CHECK: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[C15]], [[C12]]
    ; CHECK: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[C12]](s32), [[C15]]
    ; CHECK: [[ICMP3:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C12]](s32), [[C16]]
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[C12]](s32)
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[LOAD1]], [[SUB3]](s32)
    ; CHECK: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[DEF4]], [[C12]](s32)
    ; CHECK: [[OR2:%[0-9]+]]:_(s32) = G_OR [[LSHR]], [[SHL1]]
    ; CHECK: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[SUB2]](s32)
    ; CHECK: [[COPY12:%[0-9]+]]:_(s32) = COPY [[ICMP2]](s32)
    ; CHECK: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[COPY12]](s32), [[SHL]], [[C17]]
    ; CHECK: [[COPY13:%[0-9]+]]:_(s32) = COPY [[ICMP2]](s32)
    ; CHECK: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[COPY13]](s32), [[OR2]], [[SHL2]]
    ; CHECK: [[COPY14:%[0-9]+]]:_(s32) = COPY [[ICMP3]](s32)
    ; CHECK: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[COPY14]](s32), [[DEF4]], [[SELECT1]]
    ; CHECK: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[C18]]
    ; CHECK: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C18]], [[SUB1]]
    ; CHECK: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP4:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB1]](s32), [[C18]]
    ; CHECK: [[ICMP5:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB1]](s32), [[C19]]
    ; CHECK: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[DEF4]], [[SUB1]](s32)
    ; CHECK: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[LOAD1]], [[SUB1]](s32)
    ; CHECK: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[DEF4]], [[SUB5]](s32)
    ; CHECK: [[OR3:%[0-9]+]]:_(s32) = G_OR [[LSHR2]], [[SHL3]]
    ; CHECK: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[DEF4]], [[SUB4]](s32)
    ; CHECK: [[COPY15:%[0-9]+]]:_(s32) = COPY [[ICMP4]](s32)
    ; CHECK: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[COPY15]](s32), [[OR3]], [[LSHR3]]
    ; CHECK: [[COPY16:%[0-9]+]]:_(s32) = COPY [[ICMP5]](s32)
    ; CHECK: [[SELECT4:%[0-9]+]]:_(s32) = G_SELECT [[COPY16]](s32), [[LOAD1]], [[SELECT3]]
    ; CHECK: [[COPY17:%[0-9]+]]:_(s32) = COPY [[ICMP4]](s32)
    ; CHECK: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[COPY17]](s32), [[LSHR1]], [[C20]]
    ; CHECK: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF5]](s64)
    ; CHECK: [[SUB6:%[0-9]+]]:_(s32) = G_SUB [[C12]], [[C21]]
    ; CHECK: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[C21]], [[C12]]
    ; CHECK: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP6:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[C12]](s32), [[C21]]
    ; CHECK: [[ICMP7:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C12]](s32), [[C22]]
    ; CHECK: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[UV12]], [[C12]](s32)
    ; CHECK: [[LSHR4:%[0-9]+]]:_(s32) = G_LSHR [[UV12]], [[SUB7]](s32)
    ; CHECK: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[UV13]], [[C12]](s32)
    ; CHECK: [[OR4:%[0-9]+]]:_(s32) = G_OR [[LSHR4]], [[SHL5]]
    ; CHECK: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL6:%[0-9]+]]:_(s32) = G_SHL [[UV12]], [[SUB6]](s32)
    ; CHECK: [[COPY18:%[0-9]+]]:_(s32) = COPY [[ICMP6]](s32)
    ; CHECK: [[SELECT6:%[0-9]+]]:_(s32) = G_SELECT [[COPY18]](s32), [[SHL4]], [[C23]]
    ; CHECK: [[COPY19:%[0-9]+]]:_(s32) = COPY [[ICMP6]](s32)
    ; CHECK: [[SELECT7:%[0-9]+]]:_(s32) = G_SELECT [[COPY19]](s32), [[OR4]], [[SHL6]]
    ; CHECK: [[COPY20:%[0-9]+]]:_(s32) = COPY [[ICMP7]](s32)
    ; CHECK: [[SELECT8:%[0-9]+]]:_(s32) = G_SELECT [[COPY20]](s32), [[UV13]], [[SELECT7]]
    ; CHECK: [[OR5:%[0-9]+]]:_(s32) = G_OR [[SELECT4]], [[SELECT6]]
    ; CHECK: [[C24:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SUB]], [[C25]]
    ; CHECK: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[C25]], [[SUB]]
    ; CHECK: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP8:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB]](s32), [[C25]]
    ; CHECK: [[ICMP9:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB]](s32), [[C26]]
    ; CHECK: [[SHL7:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[SUB]](s32)
    ; CHECK: [[LSHR5:%[0-9]+]]:_(s32) = G_LSHR [[LOAD1]], [[SUB9]](s32)
    ; CHECK: [[SHL8:%[0-9]+]]:_(s32) = G_SHL [[DEF4]], [[SUB]](s32)
    ; CHECK: [[OR6:%[0-9]+]]:_(s32) = G_OR [[LSHR5]], [[SHL8]]
    ; CHECK: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL9:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[SUB8]](s32)
    ; CHECK: [[COPY21:%[0-9]+]]:_(s32) = COPY [[ICMP8]](s32)
    ; CHECK: [[SELECT9:%[0-9]+]]:_(s32) = G_SELECT [[COPY21]](s32), [[SHL7]], [[C27]]
    ; CHECK: [[COPY22:%[0-9]+]]:_(s32) = COPY [[ICMP8]](s32)
    ; CHECK: [[SELECT10:%[0-9]+]]:_(s32) = G_SELECT [[COPY22]](s32), [[OR6]], [[SHL9]]
    ; CHECK: [[COPY23:%[0-9]+]]:_(s32) = COPY [[ICMP9]](s32)
    ; CHECK: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C24]](s64)
    ; CHECK: [[COPY24:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT11:%[0-9]+]]:_(s32) = G_SELECT [[COPY24]](s32), [[SELECT]], [[UV14]]
    ; CHECK: [[COPY25:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT12:%[0-9]+]]:_(s32) = G_SELECT [[COPY25]](s32), [[SELECT2]], [[UV15]]
    ; CHECK: [[COPY26:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT13:%[0-9]+]]:_(s32) = G_SELECT [[COPY26]](s32), [[OR5]], [[SELECT9]]
    ; CHECK: [[COPY27:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF5]](s64)
    ; CHECK: [[COPY28:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[SELECT14:%[0-9]+]]:_(s32) = G_SELECT [[COPY28]](s32), [[UV16]], [[SELECT13]]
    ; CHECK: [[COPY29:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[UV18:%[0-9]+]]:_(s32), [[UV19:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[LOAD]](s64)
    ; CHECK: [[UV20:%[0-9]+]]:_(s32), [[UV21:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C9]](s64)
    ; CHECK: [[OR7:%[0-9]+]]:_(s32) = G_OR [[SELECT11]], [[UV18]]
    ; CHECK: [[OR8:%[0-9]+]]:_(s32) = G_OR [[SELECT12]], [[UV19]]
    ; CHECK: [[OR9:%[0-9]+]]:_(s32) = G_OR [[SELECT14]], [[UV20]]
    ; CHECK: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK: [[DEF6:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[DEF7:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[SUB10:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[C28]]
    ; CHECK: [[SUB11:%[0-9]+]]:_(s32) = G_SUB [[C28]], [[COPY1]]
    ; CHECK: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP10:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY1]](s32), [[C28]]
    ; CHECK: [[ICMP11:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[C29]]
    ; CHECK: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB12:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[C30]]
    ; CHECK: [[SUB13:%[0-9]+]]:_(s32) = G_SUB [[C30]], [[COPY1]]
    ; CHECK: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP12:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY1]](s32), [[C30]]
    ; CHECK: [[ICMP13:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[C31]]
    ; CHECK: [[SHL10:%[0-9]+]]:_(s32) = G_SHL [[OR7]], [[COPY1]](s32)
    ; CHECK: [[LSHR6:%[0-9]+]]:_(s32) = G_LSHR [[OR7]], [[SUB13]](s32)
    ; CHECK: [[SHL11:%[0-9]+]]:_(s32) = G_SHL [[OR8]], [[COPY1]](s32)
    ; CHECK: [[OR10:%[0-9]+]]:_(s32) = G_OR [[LSHR6]], [[SHL11]]
    ; CHECK: [[C32:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL12:%[0-9]+]]:_(s32) = G_SHL [[OR7]], [[SUB12]](s32)
    ; CHECK: [[COPY30:%[0-9]+]]:_(s32) = COPY [[ICMP12]](s32)
    ; CHECK: [[SELECT15:%[0-9]+]]:_(s32) = G_SELECT [[COPY30]](s32), [[SHL10]], [[C32]]
    ; CHECK: [[COPY31:%[0-9]+]]:_(s32) = COPY [[ICMP12]](s32)
    ; CHECK: [[SELECT16:%[0-9]+]]:_(s32) = G_SELECT [[COPY31]](s32), [[OR10]], [[SHL12]]
    ; CHECK: [[COPY32:%[0-9]+]]:_(s32) = COPY [[ICMP13]](s32)
    ; CHECK: [[SELECT17:%[0-9]+]]:_(s32) = G_SELECT [[COPY32]](s32), [[OR8]], [[SELECT16]]
    ; CHECK: [[C33:%[0-9]+]]:_(s64) = G_CONSTANT i64 281474976710655
    ; CHECK: [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C33]](s64)
    ; CHECK: [[AND4:%[0-9]+]]:_(s32) = G_AND [[OR7]], [[UV22]]
    ; CHECK: [[AND5:%[0-9]+]]:_(s32) = G_AND [[OR8]], [[UV23]]
    ; CHECK: [[C34:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB14:%[0-9]+]]:_(s32) = G_SUB [[SUB11]], [[C34]]
    ; CHECK: [[SUB15:%[0-9]+]]:_(s32) = G_SUB [[C34]], [[SUB11]]
    ; CHECK: [[C35:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP14:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB11]](s32), [[C34]]
    ; CHECK: [[ICMP15:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB11]](s32), [[C35]]
    ; CHECK: [[LSHR7:%[0-9]+]]:_(s32) = G_LSHR [[AND5]], [[SUB11]](s32)
    ; CHECK: [[LSHR8:%[0-9]+]]:_(s32) = G_LSHR [[AND4]], [[SUB11]](s32)
    ; CHECK: [[SHL13:%[0-9]+]]:_(s32) = G_SHL [[AND5]], [[SUB15]](s32)
    ; CHECK: [[OR11:%[0-9]+]]:_(s32) = G_OR [[LSHR8]], [[SHL13]]
    ; CHECK: [[C36:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[LSHR9:%[0-9]+]]:_(s32) = G_LSHR [[AND5]], [[SUB14]](s32)
    ; CHECK: [[COPY33:%[0-9]+]]:_(s32) = COPY [[ICMP14]](s32)
    ; CHECK: [[SELECT18:%[0-9]+]]:_(s32) = G_SELECT [[COPY33]](s32), [[OR11]], [[LSHR9]]
    ; CHECK: [[COPY34:%[0-9]+]]:_(s32) = COPY [[ICMP15]](s32)
    ; CHECK: [[SELECT19:%[0-9]+]]:_(s32) = G_SELECT [[COPY34]](s32), [[AND4]], [[SELECT18]]
    ; CHECK: [[COPY35:%[0-9]+]]:_(s32) = COPY [[ICMP14]](s32)
    ; CHECK: [[SELECT20:%[0-9]+]]:_(s32) = G_SELECT [[COPY35]](s32), [[LSHR7]], [[C36]]
    ; CHECK: [[C37:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB16:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[C37]]
    ; CHECK: [[SUB17:%[0-9]+]]:_(s32) = G_SUB [[C37]], [[COPY1]]
    ; CHECK: [[C38:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP16:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY1]](s32), [[C37]]
    ; CHECK: [[ICMP17:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[C38]]
    ; CHECK: [[SHL14:%[0-9]+]]:_(s32) = G_SHL [[OR9]], [[COPY1]](s32)
    ; CHECK: [[LSHR10:%[0-9]+]]:_(s32) = G_LSHR [[OR9]], [[SUB17]](s32)
    ; CHECK: [[SHL15:%[0-9]+]]:_(s32) = G_SHL [[DEF6]], [[COPY1]](s32)
    ; CHECK: [[OR12:%[0-9]+]]:_(s32) = G_OR [[LSHR10]], [[SHL15]]
    ; CHECK: [[C39:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL16:%[0-9]+]]:_(s32) = G_SHL [[OR9]], [[SUB16]](s32)
    ; CHECK: [[COPY36:%[0-9]+]]:_(s32) = COPY [[ICMP16]](s32)
    ; CHECK: [[SELECT21:%[0-9]+]]:_(s32) = G_SELECT [[COPY36]](s32), [[SHL14]], [[C39]]
    ; CHECK: [[COPY37:%[0-9]+]]:_(s32) = COPY [[ICMP16]](s32)
    ; CHECK: [[SELECT22:%[0-9]+]]:_(s32) = G_SELECT [[COPY37]](s32), [[OR12]], [[SHL16]]
    ; CHECK: [[COPY38:%[0-9]+]]:_(s32) = COPY [[ICMP17]](s32)
    ; CHECK: [[SELECT23:%[0-9]+]]:_(s32) = G_SELECT [[COPY38]](s32), [[DEF6]], [[SELECT22]]
    ; CHECK: [[COPY39:%[0-9]+]]:_(s32) = COPY [[SELECT19]](s32)
    ; CHECK: [[COPY40:%[0-9]+]]:_(s32) = COPY [[SELECT21]](s32)
    ; CHECK: [[OR13:%[0-9]+]]:_(s32) = G_OR [[COPY39]], [[COPY40]]
    ; CHECK: [[COPY41:%[0-9]+]]:_(s32) = COPY [[SELECT20]](s32)
    ; CHECK: [[COPY42:%[0-9]+]]:_(s32) = COPY [[SELECT23]](s32)
    ; CHECK: [[OR14:%[0-9]+]]:_(s32) = G_OR [[COPY41]], [[COPY42]]
    ; CHECK: [[DEF8:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY43:%[0-9]+]]:_(s64) = COPY [[DEF8]](s64)
    ; CHECK: [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY43]](s64)
    ; CHECK: [[C40:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY44:%[0-9]+]]:_(s32) = COPY [[OR14]](s32)
    ; CHECK: [[AND6:%[0-9]+]]:_(s32) = G_AND [[COPY44]], [[C40]]
    ; CHECK: [[C41:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND7:%[0-9]+]]:_(s32) = G_AND [[UV25]], [[C41]]
    ; CHECK: [[OR15:%[0-9]+]]:_(s32) = G_OR [[AND7]], [[AND6]]
    ; CHECK: [[COPY45:%[0-9]+]]:_(s32) = COPY [[OR15]](s32)
    ; CHECK: [[C42:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C43:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB18:%[0-9]+]]:_(s32) = G_SUB [[SUB10]], [[C43]]
    ; CHECK: [[SUB19:%[0-9]+]]:_(s32) = G_SUB [[C43]], [[SUB10]]
    ; CHECK: [[C44:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP18:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB10]](s32), [[C43]]
    ; CHECK: [[ICMP19:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB10]](s32), [[C44]]
    ; CHECK: [[SHL17:%[0-9]+]]:_(s32) = G_SHL [[OR7]], [[SUB10]](s32)
    ; CHECK: [[LSHR11:%[0-9]+]]:_(s32) = G_LSHR [[OR7]], [[SUB19]](s32)
    ; CHECK: [[SHL18:%[0-9]+]]:_(s32) = G_SHL [[OR8]], [[SUB10]](s32)
    ; CHECK: [[OR16:%[0-9]+]]:_(s32) = G_OR [[LSHR11]], [[SHL18]]
    ; CHECK: [[C45:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL19:%[0-9]+]]:_(s32) = G_SHL [[OR7]], [[SUB18]](s32)
    ; CHECK: [[COPY46:%[0-9]+]]:_(s32) = COPY [[ICMP18]](s32)
    ; CHECK: [[SELECT24:%[0-9]+]]:_(s32) = G_SELECT [[COPY46]](s32), [[SHL17]], [[C45]]
    ; CHECK: [[COPY47:%[0-9]+]]:_(s32) = COPY [[ICMP18]](s32)
    ; CHECK: [[SELECT25:%[0-9]+]]:_(s32) = G_SELECT [[COPY47]](s32), [[OR16]], [[SHL19]]
    ; CHECK: [[COPY48:%[0-9]+]]:_(s32) = COPY [[ICMP19]](s32)
    ; CHECK: [[SELECT26:%[0-9]+]]:_(s32) = G_SELECT [[COPY48]](s32), [[OR8]], [[SELECT25]]
    ; CHECK: [[COPY49:%[0-9]+]]:_(s32) = COPY [[SELECT15]](s32)
    ; CHECK: [[COPY50:%[0-9]+]]:_(s64) = COPY [[C42]](s64)
    ; CHECK: [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY50]](s64)
    ; CHECK: [[COPY51:%[0-9]+]]:_(s32) = COPY [[UV26]](s32)
    ; CHECK: [[COPY52:%[0-9]+]]:_(s64) = COPY [[C42]](s64)
    ; CHECK: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY52]](s64)
    ; CHECK: [[COPY53:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT27:%[0-9]+]]:_(s32) = G_SELECT [[COPY53]](s32), [[COPY49]], [[COPY51]]
    ; CHECK: [[COPY54:%[0-9]+]]:_(s32) = COPY [[SELECT17]](s32)
    ; CHECK: [[COPY55:%[0-9]+]]:_(s32) = COPY [[UV29]](s32)
    ; CHECK: [[COPY56:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT28:%[0-9]+]]:_(s32) = G_SELECT [[COPY56]](s32), [[COPY54]], [[COPY55]]
    ; CHECK: [[DEF9:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY57:%[0-9]+]]:_(s64) = COPY [[DEF9]](s64)
    ; CHECK: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY57]](s64)
    ; CHECK: [[C46:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY58:%[0-9]+]]:_(s32) = COPY [[SELECT28]](s32)
    ; CHECK: [[AND8:%[0-9]+]]:_(s32) = G_AND [[COPY58]], [[C46]]
    ; CHECK: [[C47:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND9:%[0-9]+]]:_(s32) = G_AND [[UV31]], [[C47]]
    ; CHECK: [[OR17:%[0-9]+]]:_(s32) = G_OR [[AND9]], [[AND8]]
    ; CHECK: [[COPY59:%[0-9]+]]:_(s32) = COPY [[OR17]](s32)
    ; CHECK: [[COPY60:%[0-9]+]]:_(s32) = COPY [[OR13]](s32)
    ; CHECK: [[COPY61:%[0-9]+]]:_(s32) = COPY [[SELECT24]](s32)
    ; CHECK: [[COPY62:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT29:%[0-9]+]]:_(s32) = G_SELECT [[COPY62]](s32), [[COPY60]], [[COPY61]]
    ; CHECK: [[COPY63:%[0-9]+]]:_(s32) = COPY [[COPY45]](s32)
    ; CHECK: [[COPY64:%[0-9]+]]:_(s32) = COPY [[SELECT26]](s32)
    ; CHECK: [[COPY65:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT30:%[0-9]+]]:_(s32) = G_SELECT [[COPY65]](s32), [[COPY63]], [[COPY64]]
    ; CHECK: [[DEF10:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY66:%[0-9]+]]:_(s64) = COPY [[DEF10]](s64)
    ; CHECK: [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY66]](s64)
    ; CHECK: [[C48:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY67:%[0-9]+]]:_(s32) = COPY [[SELECT30]](s32)
    ; CHECK: [[AND10:%[0-9]+]]:_(s32) = G_AND [[COPY67]], [[C48]]
    ; CHECK: [[C49:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND11:%[0-9]+]]:_(s32) = G_AND [[UV33]], [[C49]]
    ; CHECK: [[OR18:%[0-9]+]]:_(s32) = G_OR [[AND11]], [[AND10]]
    ; CHECK: [[COPY68:%[0-9]+]]:_(s32) = COPY [[OR18]](s32)
    ; CHECK: [[COPY69:%[0-9]+]]:_(s32) = COPY [[OR9]](s32)
    ; CHECK: [[COPY70:%[0-9]+]]:_(s32) = COPY [[SELECT29]](s32)
    ; CHECK: [[COPY71:%[0-9]+]]:_(s32) = COPY [[ICMP11]](s32)
    ; CHECK: [[SELECT31:%[0-9]+]]:_(s32) = G_SELECT [[COPY71]](s32), [[COPY69]], [[COPY70]]
    ; CHECK: [[COPY72:%[0-9]+]]:_(s32) = COPY [[DEF6]](s32)
    ; CHECK: [[COPY73:%[0-9]+]]:_(s32) = COPY [[COPY68]](s32)
    ; CHECK: [[COPY74:%[0-9]+]]:_(s32) = COPY [[ICMP11]](s32)
    ; CHECK: [[SELECT32:%[0-9]+]]:_(s32) = G_SELECT [[COPY74]](s32), [[COPY72]], [[COPY73]]
    ; CHECK: [[DEF11:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY75:%[0-9]+]]:_(s64) = COPY [[DEF11]](s64)
    ; CHECK: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY75]](s64)
    ; CHECK: [[C50:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY76:%[0-9]+]]:_(s32) = COPY [[SELECT32]](s32)
    ; CHECK: [[AND12:%[0-9]+]]:_(s32) = G_AND [[COPY76]], [[C50]]
    ; CHECK: [[C51:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND13:%[0-9]+]]:_(s32) = G_AND [[UV35]], [[C51]]
    ; CHECK: [[OR19:%[0-9]+]]:_(s32) = G_OR [[AND13]], [[AND12]]
    ; CHECK: [[COPY77:%[0-9]+]]:_(s32) = COPY [[OR19]](s32)
    ; CHECK: [[C52:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR12:%[0-9]+]]:_(s32) = G_LSHR [[SELECT27]], [[C52]](s32)
    ; CHECK: [[C53:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR13:%[0-9]+]]:_(s32) = G_LSHR [[COPY59]], [[C53]](s32)
    ; CHECK: [[C54:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR14:%[0-9]+]]:_(s32) = G_LSHR [[SELECT31]], [[C54]](s32)
    ; CHECK: [[C55:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR15:%[0-9]+]]:_(s32) = G_LSHR [[COPY77]], [[C55]](s32)
    ; CHECK: [[DEF12:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[C56:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY78:%[0-9]+]]:_(s32) = COPY [[SELECT27]](s32)
    ; CHECK: [[AND14:%[0-9]+]]:_(s32) = G_AND [[COPY78]], [[C56]]
    ; CHECK: [[C57:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY79:%[0-9]+]]:_(s32) = COPY [[LSHR12]](s32)
    ; CHECK: [[AND15:%[0-9]+]]:_(s32) = G_AND [[COPY79]], [[C57]]
    ; CHECK: [[C58:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL20:%[0-9]+]]:_(s32) = G_SHL [[AND15]], [[C58]](s32)
    ; CHECK: [[OR20:%[0-9]+]]:_(s32) = G_OR [[AND14]], [[SHL20]]
    ; CHECK: [[C59:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY80:%[0-9]+]]:_(s32) = COPY [[COPY59]](s32)
    ; CHECK: [[AND16:%[0-9]+]]:_(s32) = G_AND [[COPY80]], [[C59]]
    ; CHECK: [[C60:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY81:%[0-9]+]]:_(s32) = COPY [[SELECT31]](s32)
    ; CHECK: [[AND17:%[0-9]+]]:_(s32) = G_AND [[COPY81]], [[C60]]
    ; CHECK: [[C61:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL21:%[0-9]+]]:_(s32) = G_SHL [[AND17]], [[C61]](s32)
    ; CHECK: [[OR21:%[0-9]+]]:_(s32) = G_OR [[AND16]], [[SHL21]]
    ; CHECK: [[C62:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY82:%[0-9]+]]:_(s32) = COPY [[LSHR14]](s32)
    ; CHECK: [[AND18:%[0-9]+]]:_(s32) = G_AND [[COPY82]], [[C62]]
    ; CHECK: [[C63:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY83:%[0-9]+]]:_(s32) = COPY [[COPY77]](s32)
    ; CHECK: [[AND19:%[0-9]+]]:_(s32) = G_AND [[COPY83]], [[C63]]
    ; CHECK: [[C64:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL22:%[0-9]+]]:_(s32) = G_SHL [[AND19]], [[C64]](s32)
    ; CHECK: [[OR22:%[0-9]+]]:_(s32) = G_OR [[AND18]], [[SHL22]]
    ; CHECK: [[C65:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY84:%[0-9]+]]:_(s32) = COPY [[DEF12]](s32)
    ; CHECK: [[AND20:%[0-9]+]]:_(s32) = G_AND [[COPY84]], [[C65]]
    ; CHECK: [[C66:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY85:%[0-9]+]]:_(s32) = COPY [[DEF12]](s32)
    ; CHECK: [[AND21:%[0-9]+]]:_(s32) = G_AND [[COPY85]], [[C66]]
    ; CHECK: [[C67:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL23:%[0-9]+]]:_(s32) = G_SHL [[AND21]], [[C67]](s32)
    ; CHECK: [[OR23:%[0-9]+]]:_(s32) = G_OR [[AND20]], [[SHL23]]
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[OR22]](s32), [[OR23]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[MV]], 8
    ; CHECK: [[C68:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK: [[DEF13:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[SUB20:%[0-9]+]]:_(s32) = G_SUB [[COPY7]], [[C68]]
    ; CHECK: [[SUB21:%[0-9]+]]:_(s32) = G_SUB [[C68]], [[COPY7]]
    ; CHECK: [[C69:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP20:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY7]](s32), [[C68]]
    ; CHECK: [[ICMP21:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY7]](s32), [[C69]]
    ; CHECK: [[COPY86:%[0-9]+]]:_(s64) = COPY [[SEXT_INREG]](s64)
    ; CHECK: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY86]], 48
    ; CHECK: [[C70:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG1]](s64)
    ; CHECK: [[SUB22:%[0-9]+]]:_(s32) = G_SUB [[COPY7]], [[C70]]
    ; CHECK: [[SUB23:%[0-9]+]]:_(s32) = G_SUB [[C70]], [[COPY7]]
    ; CHECK: [[C71:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP22:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY7]](s32), [[C70]]
    ; CHECK: [[ICMP23:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY7]](s32), [[C71]]
    ; CHECK: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV37]], [[COPY7]](s32)
    ; CHECK: [[LSHR16:%[0-9]+]]:_(s32) = G_LSHR [[UV36]], [[COPY7]](s32)
    ; CHECK: [[SHL24:%[0-9]+]]:_(s32) = G_SHL [[UV37]], [[SUB23]](s32)
    ; CHECK: [[OR24:%[0-9]+]]:_(s32) = G_OR [[LSHR16]], [[SHL24]]
    ; CHECK: [[C72:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[UV37]], [[C72]](s32)
    ; CHECK: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[UV37]], [[SUB22]](s32)
    ; CHECK: [[COPY87:%[0-9]+]]:_(s32) = COPY [[ICMP22]](s32)
    ; CHECK: [[SELECT33:%[0-9]+]]:_(s32) = G_SELECT [[COPY87]](s32), [[OR24]], [[ASHR2]]
    ; CHECK: [[COPY88:%[0-9]+]]:_(s32) = COPY [[ICMP23]](s32)
    ; CHECK: [[SELECT34:%[0-9]+]]:_(s32) = G_SELECT [[COPY88]](s32), [[UV36]], [[SELECT33]]
    ; CHECK: [[COPY89:%[0-9]+]]:_(s32) = COPY [[ICMP22]](s32)
    ; CHECK: [[SELECT35:%[0-9]+]]:_(s32) = G_SELECT [[COPY89]](s32), [[ASHR]], [[ASHR1]]
    ; CHECK: [[C73:%[0-9]+]]:_(s64) = G_CONSTANT i64 281474976710655
    ; CHECK: [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C73]](s64)
    ; CHECK: [[AND22:%[0-9]+]]:_(s32) = G_AND [[OR20]], [[UV38]]
    ; CHECK: [[AND23:%[0-9]+]]:_(s32) = G_AND [[OR21]], [[UV39]]
    ; CHECK: [[C74:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB24:%[0-9]+]]:_(s32) = G_SUB [[COPY7]], [[C74]]
    ; CHECK: [[SUB25:%[0-9]+]]:_(s32) = G_SUB [[C74]], [[COPY7]]
    ; CHECK: [[C75:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP24:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY7]](s32), [[C74]]
    ; CHECK: [[ICMP25:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY7]](s32), [[C75]]
    ; CHECK: [[LSHR17:%[0-9]+]]:_(s32) = G_LSHR [[AND23]], [[COPY7]](s32)
    ; CHECK: [[LSHR18:%[0-9]+]]:_(s32) = G_LSHR [[AND22]], [[COPY7]](s32)
    ; CHECK: [[SHL25:%[0-9]+]]:_(s32) = G_SHL [[AND23]], [[SUB25]](s32)
    ; CHECK: [[OR25:%[0-9]+]]:_(s32) = G_OR [[LSHR18]], [[SHL25]]
    ; CHECK: [[C76:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[LSHR19:%[0-9]+]]:_(s32) = G_LSHR [[AND23]], [[SUB24]](s32)
    ; CHECK: [[COPY90:%[0-9]+]]:_(s32) = COPY [[ICMP24]](s32)
    ; CHECK: [[SELECT36:%[0-9]+]]:_(s32) = G_SELECT [[COPY90]](s32), [[OR25]], [[LSHR19]]
    ; CHECK: [[COPY91:%[0-9]+]]:_(s32) = COPY [[ICMP25]](s32)
    ; CHECK: [[SELECT37:%[0-9]+]]:_(s32) = G_SELECT [[COPY91]](s32), [[AND22]], [[SELECT36]]
    ; CHECK: [[COPY92:%[0-9]+]]:_(s32) = COPY [[ICMP24]](s32)
    ; CHECK: [[SELECT38:%[0-9]+]]:_(s32) = G_SELECT [[COPY92]](s32), [[LSHR17]], [[C76]]
    ; CHECK: [[COPY93:%[0-9]+]]:_(s64) = COPY [[SEXT_INREG]](s64)
    ; CHECK: [[C77:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY93]](s64)
    ; CHECK: [[SUB26:%[0-9]+]]:_(s32) = G_SUB [[SUB21]], [[C77]]
    ; CHECK: [[SUB27:%[0-9]+]]:_(s32) = G_SUB [[C77]], [[SUB21]]
    ; CHECK: [[C78:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP26:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB21]](s32), [[C77]]
    ; CHECK: [[ICMP27:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB21]](s32), [[C78]]
    ; CHECK: [[SHL26:%[0-9]+]]:_(s32) = G_SHL [[UV40]], [[SUB21]](s32)
    ; CHECK: [[LSHR20:%[0-9]+]]:_(s32) = G_LSHR [[UV40]], [[SUB27]](s32)
    ; CHECK: [[SHL27:%[0-9]+]]:_(s32) = G_SHL [[UV41]], [[SUB21]](s32)
    ; CHECK: [[OR26:%[0-9]+]]:_(s32) = G_OR [[LSHR20]], [[SHL27]]
    ; CHECK: [[C79:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL28:%[0-9]+]]:_(s32) = G_SHL [[UV40]], [[SUB26]](s32)
    ; CHECK: [[COPY94:%[0-9]+]]:_(s32) = COPY [[ICMP26]](s32)
    ; CHECK: [[SELECT39:%[0-9]+]]:_(s32) = G_SELECT [[COPY94]](s32), [[SHL26]], [[C79]]
    ; CHECK: [[COPY95:%[0-9]+]]:_(s32) = COPY [[ICMP26]](s32)
    ; CHECK: [[SELECT40:%[0-9]+]]:_(s32) = G_SELECT [[COPY95]](s32), [[OR26]], [[SHL28]]
    ; CHECK: [[COPY96:%[0-9]+]]:_(s32) = COPY [[ICMP27]](s32)
    ; CHECK: [[SELECT41:%[0-9]+]]:_(s32) = G_SELECT [[COPY96]](s32), [[UV41]], [[SELECT40]]
    ; CHECK: [[COPY97:%[0-9]+]]:_(s32) = COPY [[SELECT37]](s32)
    ; CHECK: [[COPY98:%[0-9]+]]:_(s32) = COPY [[SELECT39]](s32)
    ; CHECK: [[OR27:%[0-9]+]]:_(s32) = G_OR [[COPY97]], [[COPY98]]
    ; CHECK: [[COPY99:%[0-9]+]]:_(s32) = COPY [[SELECT38]](s32)
    ; CHECK: [[COPY100:%[0-9]+]]:_(s32) = COPY [[SELECT41]](s32)
    ; CHECK: [[OR28:%[0-9]+]]:_(s32) = G_OR [[COPY99]], [[COPY100]]
    ; CHECK: [[DEF14:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY101:%[0-9]+]]:_(s64) = COPY [[DEF14]](s64)
    ; CHECK: [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY101]](s64)
    ; CHECK: [[C80:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY102:%[0-9]+]]:_(s32) = COPY [[OR28]](s32)
    ; CHECK: [[AND24:%[0-9]+]]:_(s32) = G_AND [[COPY102]], [[C80]]
    ; CHECK: [[C81:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND25:%[0-9]+]]:_(s32) = G_AND [[UV43]], [[C81]]
    ; CHECK: [[OR29:%[0-9]+]]:_(s32) = G_OR [[AND25]], [[AND24]]
    ; CHECK: [[COPY103:%[0-9]+]]:_(s32) = COPY [[OR29]](s32)
    ; CHECK: [[COPY104:%[0-9]+]]:_(s64) = COPY [[SEXT_INREG]](s64)
    ; CHECK: [[SEXT_INREG2:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY104]], 48
    ; CHECK: [[UV44:%[0-9]+]]:_(s32), [[UV45:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG2]](s64)
    ; CHECK: [[C82:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[UV45]], [[C82]](s32)
    ; CHECK: [[C83:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR4:%[0-9]+]]:_(s32) = G_ASHR [[UV45]], [[C83]](s32)
    ; CHECK: [[COPY105:%[0-9]+]]:_(s64) = COPY [[SEXT_INREG]](s64)
    ; CHECK: [[SEXT_INREG3:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY105]], 48
    ; CHECK: [[C84:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG3]](s64)
    ; CHECK: [[SUB28:%[0-9]+]]:_(s32) = G_SUB [[SUB20]], [[C84]]
    ; CHECK: [[SUB29:%[0-9]+]]:_(s32) = G_SUB [[C84]], [[SUB20]]
    ; CHECK: [[C85:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP28:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB20]](s32), [[C84]]
    ; CHECK: [[ICMP29:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB20]](s32), [[C85]]
    ; CHECK: [[ASHR5:%[0-9]+]]:_(s32) = G_ASHR [[UV47]], [[SUB20]](s32)
    ; CHECK: [[LSHR21:%[0-9]+]]:_(s32) = G_LSHR [[UV46]], [[SUB20]](s32)
    ; CHECK: [[SHL29:%[0-9]+]]:_(s32) = G_SHL [[UV47]], [[SUB29]](s32)
    ; CHECK: [[OR30:%[0-9]+]]:_(s32) = G_OR [[LSHR21]], [[SHL29]]
    ; CHECK: [[C86:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR6:%[0-9]+]]:_(s32) = G_ASHR [[UV47]], [[C86]](s32)
    ; CHECK: [[ASHR7:%[0-9]+]]:_(s32) = G_ASHR [[UV47]], [[SUB28]](s32)
    ; CHECK: [[COPY106:%[0-9]+]]:_(s32) = COPY [[ICMP28]](s32)
    ; CHECK: [[SELECT42:%[0-9]+]]:_(s32) = G_SELECT [[COPY106]](s32), [[OR30]], [[ASHR7]]
    ; CHECK: [[COPY107:%[0-9]+]]:_(s32) = COPY [[ICMP29]](s32)
    ; CHECK: [[SELECT43:%[0-9]+]]:_(s32) = G_SELECT [[COPY107]](s32), [[UV46]], [[SELECT42]]
    ; CHECK: [[COPY108:%[0-9]+]]:_(s32) = COPY [[ICMP28]](s32)
    ; CHECK: [[SELECT44:%[0-9]+]]:_(s32) = G_SELECT [[COPY108]](s32), [[ASHR5]], [[ASHR6]]
    ; CHECK: [[COPY109:%[0-9]+]]:_(s32) = COPY [[OR27]](s32)
    ; CHECK: [[COPY110:%[0-9]+]]:_(s32) = COPY [[SELECT43]](s32)
    ; CHECK: [[COPY111:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT45:%[0-9]+]]:_(s32) = G_SELECT [[COPY111]](s32), [[COPY109]], [[COPY110]]
    ; CHECK: [[COPY112:%[0-9]+]]:_(s32) = COPY [[COPY103]](s32)
    ; CHECK: [[COPY113:%[0-9]+]]:_(s32) = COPY [[SELECT44]](s32)
    ; CHECK: [[COPY114:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT46:%[0-9]+]]:_(s32) = G_SELECT [[COPY114]](s32), [[COPY112]], [[COPY113]]
    ; CHECK: [[DEF15:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY115:%[0-9]+]]:_(s64) = COPY [[DEF15]](s64)
    ; CHECK: [[UV48:%[0-9]+]]:_(s32), [[UV49:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY115]](s64)
    ; CHECK: [[C87:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY116:%[0-9]+]]:_(s32) = COPY [[SELECT46]](s32)
    ; CHECK: [[AND26:%[0-9]+]]:_(s32) = G_AND [[COPY116]], [[C87]]
    ; CHECK: [[C88:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND27:%[0-9]+]]:_(s32) = G_AND [[UV49]], [[C88]]
    ; CHECK: [[OR31:%[0-9]+]]:_(s32) = G_OR [[AND27]], [[AND26]]
    ; CHECK: [[COPY117:%[0-9]+]]:_(s32) = COPY [[OR31]](s32)
    ; CHECK: [[COPY118:%[0-9]+]]:_(s32) = COPY [[OR20]](s32)
    ; CHECK: [[COPY119:%[0-9]+]]:_(s32) = COPY [[SELECT45]](s32)
    ; CHECK: [[COPY120:%[0-9]+]]:_(s32) = COPY [[ICMP21]](s32)
    ; CHECK: [[SELECT47:%[0-9]+]]:_(s32) = G_SELECT [[COPY120]](s32), [[COPY118]], [[COPY119]]
    ; CHECK: [[COPY121:%[0-9]+]]:_(s32) = COPY [[COPY59]](s32)
    ; CHECK: [[COPY122:%[0-9]+]]:_(s32) = COPY [[COPY117]](s32)
    ; CHECK: [[COPY123:%[0-9]+]]:_(s32) = COPY [[ICMP21]](s32)
    ; CHECK: [[SELECT48:%[0-9]+]]:_(s32) = G_SELECT [[COPY123]](s32), [[COPY121]], [[COPY122]]
    ; CHECK: [[DEF16:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY124:%[0-9]+]]:_(s64) = COPY [[DEF16]](s64)
    ; CHECK: [[UV50:%[0-9]+]]:_(s32), [[UV51:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY124]](s64)
    ; CHECK: [[C89:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY125:%[0-9]+]]:_(s32) = COPY [[SELECT48]](s32)
    ; CHECK: [[AND28:%[0-9]+]]:_(s32) = G_AND [[COPY125]], [[C89]]
    ; CHECK: [[C90:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND29:%[0-9]+]]:_(s32) = G_AND [[UV51]], [[C90]]
    ; CHECK: [[OR32:%[0-9]+]]:_(s32) = G_OR [[AND29]], [[AND28]]
    ; CHECK: [[COPY126:%[0-9]+]]:_(s32) = COPY [[OR32]](s32)
    ; CHECK: [[COPY127:%[0-9]+]]:_(s32) = COPY [[SELECT34]](s32)
    ; CHECK: [[COPY128:%[0-9]+]]:_(s32) = COPY [[ASHR3]](s32)
    ; CHECK: [[COPY129:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT49:%[0-9]+]]:_(s32) = G_SELECT [[COPY129]](s32), [[COPY127]], [[COPY128]]
    ; CHECK: [[COPY130:%[0-9]+]]:_(s32) = COPY [[SELECT35]](s32)
    ; CHECK: [[COPY131:%[0-9]+]]:_(s32) = COPY [[ASHR4]](s32)
    ; CHECK: [[COPY132:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT50:%[0-9]+]]:_(s32) = G_SELECT [[COPY132]](s32), [[COPY130]], [[COPY131]]
    ; CHECK: [[DEF17:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY133:%[0-9]+]]:_(s64) = COPY [[DEF17]](s64)
    ; CHECK: [[UV52:%[0-9]+]]:_(s32), [[UV53:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY133]](s64)
    ; CHECK: [[C91:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY134:%[0-9]+]]:_(s32) = COPY [[SELECT50]](s32)
    ; CHECK: [[AND30:%[0-9]+]]:_(s32) = G_AND [[COPY134]], [[C91]]
    ; CHECK: [[C92:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND31:%[0-9]+]]:_(s32) = G_AND [[UV53]], [[C92]]
    ; CHECK: [[OR33:%[0-9]+]]:_(s32) = G_OR [[AND31]], [[AND30]]
    ; CHECK: [[COPY135:%[0-9]+]]:_(s32) = COPY [[OR33]](s32)
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $d4 = COPY [[SELECT47]](s32)
    ; CHECK: CALL @a, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $d2 = COPY [[C8]](s32)
    ; CHECK: RET implicit $a11, implicit $d2
    %2:_(s72) = G_CONSTANT i72 7
    %4:_(s72) = G_CONSTANT i72 66
    %7:_(s32) = G_CONSTANT i32 0
    %0:_(p0) = G_FRAME_INDEX %stack.0.e
    %1:_(s72) = G_LOAD %0(p0) :: (dereferenceable load 9 from %ir.0, align 2)
    %3:_(s72) = G_SHL %1, %2(s72)
    %5:_(s72) = G_ASHR %3, %4(s72)
    %6:_(s32) = G_TRUNC %5(s72)
    ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    $d4 = COPY %6(s32)
    CALL @a, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4
    ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    $d2 = COPY %7(s32)
    RET implicit $a11, implicit $d2

...
