# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=tricore -mattr=-tc18 -mattr=-tc162 -run-pass=legalizer -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefixes=NOTC162OPS %s
# RUN: llc -mtriple=tricore -mattr=-tc18 -run-pass=legalizer -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefixes=NOTC18OPS %s

---
name: test_fpext_f16_to_f32
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fpext_f16_to_f32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; CHECK: [[FPEXT:%[0-9]+]]:_(s32) = G_FPEXT [[TRUNC]](s16)
    ; CHECK: $d2 = COPY [[FPEXT]](s32)
    ; NOTC162OPS-LABEL: name: test_fpext_f16_to_f32
    ; NOTC162OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC162OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; NOTC162OPS: $d4 = COPY [[COPY1]](s32)
    ; NOTC162OPS: CALL &__gnu_h2f_ieee, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $d2
    ; NOTC162OPS: [[COPY2:%[0-9]+]]:_(s32) = COPY $d2
    ; NOTC162OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: $d2 = COPY [[COPY2]](s32)
    ; NOTC18OPS-LABEL: name: test_fpext_f16_to_f32
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC18OPS: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; NOTC18OPS: [[FPEXT:%[0-9]+]]:_(s32) = G_FPEXT [[TRUNC]](s16)
    ; NOTC18OPS: $d2 = COPY [[FPEXT]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_TRUNC %0
    %2:_(s32) = G_FPEXT %1
    $d2 = COPY %2
...

---
name: test_fpext_f32_to_f64
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fpext_f32_to_f64
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[FPEXT:%[0-9]+]]:_(s64) = G_FPEXT [[COPY]](s32)
    ; CHECK: $e2 = COPY [[FPEXT]](s64)
    ; NOTC162OPS-LABEL: name: test_fpext_f32_to_f64
    ; NOTC162OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC162OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: $d4 = COPY [[COPY]](s32)
    ; NOTC162OPS: CALL &__extendsfdf2, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $e2
    ; NOTC162OPS: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; NOTC162OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: $e2 = COPY [[COPY1]](s64)
    ; NOTC18OPS-LABEL: name: test_fpext_f32_to_f64
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC18OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $d4 = COPY [[COPY]](s32)
    ; NOTC18OPS: CALL &__extendsfdf2, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $e2
    ; NOTC18OPS: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; NOTC18OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $e2 = COPY [[COPY1]](s64)
    %0:_(s32) = COPY $d4
    %1:_(s64) = G_FPEXT %0
    $e2 = COPY %1
...
