# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name:            insert_s32_s16
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: insert_s32_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: $d4 = COPY [[COPY3]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s16) = G_TRUNC %1(s32)
    %3:_(s32) = G_INSERT %0, %2, 0
    $d4 = COPY %3
...

---
name:            insert_s32_s31
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: insert_s32_s31
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 2147483647
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2147483648
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: $d4 = COPY [[COPY3]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s31) = G_TRUNC %1(s32)
    %3:_(s32) = G_INSERT %0, %2, 0
    $d4 = COPY %3
...

---
name:            insert_s32_s1
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: insert_s32_s1
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: $d4 = COPY [[COPY3]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s1) = G_TRUNC %1(s32)
    %3:_(s32) = G_INSERT %0, %2, 0
    $d4 = COPY %3
...

---
name:            insert_p0_s16
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: insert_p0_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY]](p0)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -2
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[PTRTOINT]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[OR]](s32)
    ; CHECK: $d4 = COPY [[INTTOPTR]](p0)
    %0:_(p0) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s1) = G_TRUNC %1(s32)
    %3:_(p0) = G_INSERT %0, %2, 0
    $d4 = COPY %3
...

---
name:            insert_s64_p0
body:             |
  bb.0:
    liveins: $e4, $d5


    ; CHECK-LABEL: name: insert_s64_p0
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(p0) = COPY $d5
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY1]](p0)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[PTRTOINT]](s32), [[UV1]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    %0:_(s64) = COPY $e4
    %1:_(p0) = COPY $d5
    %3:_(s64) = G_INSERT %0, %1, 0
    $e4 = COPY %3
...

---
name:            insert_s64_s16
body:             |
  bb.0:
    liveins: $e4, $d5

    ; CHECK-LABEL: name: insert_s64_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY3]](s32), [[UV1]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s32) = COPY $d5
    %2:_(s16) = G_TRUNC %1(s32)
    %3:_(s64) = G_INSERT %0, %2, 0
    $e4 = COPY %3
...

---
name:            insert_s24_s16
body:             |
  bb.0:
    liveins: $d4, $d5


    ; CHECK-LABEL: name: insert_s24_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY3]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY [[COPY4]](s32)
    ; CHECK: $d4 = COPY [[COPY5]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s24) = G_TRUNC %0(s32)
    %3:_(s16) = G_TRUNC %1(s32)
    %4:_(s24) = G_INSERT %2, %3, 0
    %5:_(s32) = G_ANYEXT %4(s24)
    $d4 = COPY %5
...

---
name:            insert_s64_s32
body:             |
  bb.0:
    liveins: $e4, $d4


    ; CHECK-LABEL: name: insert_s64_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY1]](s32), [[UV1]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s32) = COPY $d5
    %2:_(s64) = G_INSERT %0, %1, 0
    $e4 = COPY %2
...

---
name:            insert_s64_s32_off32
body:             |
  bb.0:
    liveins: $e4, $d4


    ; CHECK-LABEL: name: insert_s64_s32_off32
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UV]](s32), [[COPY1]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s32) = COPY $d5
    %2:_(s64) = G_INSERT %0, %1, 32
    $e4 = COPY %2
...

---
name:            insert_s40_s8
body:             |
  bb.0:
    liveins: $d4, $d5


    ; CHECK-LABEL: name: insert_s40_s8
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[COPY]](s32)
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ANYEXT]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -256
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV1]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: $d4 = COPY [[UV]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s40) = G_ANYEXT %0
    %3:_(s8) = G_TRUNC %1
    %4:_(s40) = G_INSERT %2, %3, 32
    %5:_(s32) = G_TRUNC %4
    $d4 = COPY %5
...

---
name:            insert_s80_s8
body:             |
  bb.0:
    liveins: $d4, $e4

    ; CHECK-LABEL: name: insert_s80_s8
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -256
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV2]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UV]](s32), [[UV1]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s32) = COPY $d4
    %2:_(s80) = G_ANYEXT %0
    %3:_(s8) = G_TRUNC %1
    %4:_(s80) = G_INSERT %2, %3, 64
    %5:_(s64) = G_TRUNC %4
    $e4 = COPY %5
...

---
name:            insert_s64_s48
body:             |
  bb.0:
    liveins: $e4, $e6

    ; CHECK-LABEL: name: insert_s64_s48
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY2]](s64)
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[UV2]](s32)
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[COPY3]](s32)
    ; CHECK: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; CHECK: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY5]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[UV5]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY6]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV1]], [[C1]]
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND1]], [[AND]]
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY4]](s32), [[COPY7]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = COPY $e6
    %2:_(s48) = G_TRUNC %1(s64)
    %3:_(s64) = G_INSERT %0, %2, 0
    $e4 = COPY %3
...
