# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name:            fcopysign_s32
body:             |
  bb.0.entry:

    ; CHECK-LABEL: name: fcopysign_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[FCOPYSIGN:%[0-9]+]]:_(s32) = G_FCOPYSIGN [[COPY]], [[COPY1]](s32)
    ; CHECK: $d4 = COPY [[FCOPYSIGN]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s32) = G_FCOPYSIGN %0, %1
    $d4 = COPY %2(s32)
...

---
name:            fcopysign_s64
body:             |
  bb.0.entry:

    ; CHECK-LABEL: name: fcopysign_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: [[FCOPYSIGN:%[0-9]+]]:_(s64) = G_FCOPYSIGN [[COPY]], [[COPY1]](s64)
    ; CHECK: $e4 = COPY [[FCOPYSIGN]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = COPY $e6
    %2:_(s64) = G_FCOPYSIGN %0, %1
    $e4 = COPY %2(s64)
...
