# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_freeze_s3
body:             |
  bb.0.entry:
    liveins: $d4
    ; CHECK-LABEL: name: test_freeze_s3
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY1]]
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[FREEZE]](s32)
    ; CHECK: $d2 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s3) = G_TRUNC %0
    %2:_(s3) = G_FREEZE %1
    %3:_(s32) = G_ANYEXT %2
    $d2 = COPY %3
...

---
name:            test_freeze_s8
body:             |
  bb.0.entry:
    liveins: $d4
    ; CHECK-LABEL: name: test_freeze_s8
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY1]]
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[FREEZE]](s32)
    ; CHECK: $d2 = COPY [[COPY2]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s8) = G_TRUNC %0
    %2:_(s8) = G_FREEZE %1
    %3:_(s32) = G_ANYEXT %2
    $d2 = COPY %3
...

---
name:            test_freeze_s32
body:             |
  bb.0.entry:
    liveins: $a4, $d4, $e4
    ; CHECK-LABEL: name: test_freeze_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[FREEZE:%[0-9]+]]:_(s32) = G_FREEZE [[COPY]]
    ; CHECK: $d2 = COPY [[FREEZE]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = G_FREEZE %0
    $d2 = COPY %1
...

---
name:            test_freeze_s33
body:             |
  bb.0.entry:
    liveins: $e4
    ; CHECK-LABEL: name: test_freeze_s33
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[FREEZE:%[0-9]+]]:_(s64) = G_FREEZE [[COPY1]]
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY [[FREEZE]](s64)
    ; CHECK: $e2 = COPY [[COPY2]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s33) = G_TRUNC %0
    %2:_(s33) = G_FREEZE %1
    %3:_(s64) = G_ANYEXT %2
    $e2 = COPY %3
...

---
name:            test_freeze_s48
body:             |
  bb.0.entry:
    liveins: $e4
    ; CHECK-LABEL: name: test_freeze_s48
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[FREEZE:%[0-9]+]]:_(s64) = G_FREEZE [[COPY1]]
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY [[FREEZE]](s64)
    ; CHECK: $e2 = COPY [[COPY2]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s48) = G_TRUNC %0
    %2:_(s48) = G_FREEZE %1
    %3:_(s64) = G_ANYEXT %2
    $e2 = COPY %3
...

---
name:            test_freeze_s64
body:             |
  bb.0.entry:
    liveins: $e4
    ; CHECK-LABEL: name: test_freeze_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[FREEZE:%[0-9]+]]:_(s64) = G_FREEZE [[COPY]]
    ; CHECK: $e2 = COPY [[FREEZE]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = G_FREEZE %0
    $e2 = COPY %1
...

---
name:            test_freeze_s65
body:             |
  bb.0.entry:
    liveins: $e4
    ; CHECK-LABEL: name: test_freeze_s65
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C1]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C2]](s32)
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C3]](s32)
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[LSHR4:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C4]](s32)
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK: [[LSHR5:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C5]](s32)
    ; CHECK: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[LSHR6:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C6]](s32)
    ; CHECK: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[LSHR7:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C7]](s32)
    ; CHECK: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK: [[LSHR8:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C8]](s32)
    ; CHECK: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK: [[LSHR9:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C9]](s32)
    ; CHECK: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK: [[LSHR10:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C10]](s32)
    ; CHECK: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK: [[LSHR11:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C11]](s32)
    ; CHECK: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK: [[LSHR12:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C12]](s32)
    ; CHECK: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK: [[LSHR13:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C13]](s32)
    ; CHECK: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[LSHR14:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C14]](s32)
    ; CHECK: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR15:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C15]](s32)
    ; CHECK: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK: [[LSHR16:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C16]](s32)
    ; CHECK: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK: [[LSHR17:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C17]](s32)
    ; CHECK: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK: [[LSHR18:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C18]](s32)
    ; CHECK: [[C19:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK: [[LSHR19:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C19]](s32)
    ; CHECK: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK: [[LSHR20:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C20]](s32)
    ; CHECK: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK: [[LSHR21:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C21]](s32)
    ; CHECK: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK: [[LSHR22:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C22]](s32)
    ; CHECK: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK: [[LSHR23:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C23]](s32)
    ; CHECK: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK: [[LSHR24:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C24]](s32)
    ; CHECK: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK: [[LSHR25:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C25]](s32)
    ; CHECK: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK: [[LSHR26:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C26]](s32)
    ; CHECK: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK: [[LSHR27:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C27]](s32)
    ; CHECK: [[C28:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK: [[LSHR28:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C28]](s32)
    ; CHECK: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK: [[LSHR29:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C29]](s32)
    ; CHECK: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[LSHR30:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C30]](s32)
    ; CHECK: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[LSHR31:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C31]](s32)
    ; CHECK: [[C32:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[LSHR32:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C32]](s32)
    ; CHECK: [[C33:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[LSHR33:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C33]](s32)
    ; CHECK: [[C34:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[LSHR34:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C34]](s32)
    ; CHECK: [[C35:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[LSHR35:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C35]](s32)
    ; CHECK: [[C36:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK: [[LSHR36:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C36]](s32)
    ; CHECK: [[C37:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[LSHR37:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C37]](s32)
    ; CHECK: [[C38:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[LSHR38:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C38]](s32)
    ; CHECK: [[C39:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK: [[LSHR39:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C39]](s32)
    ; CHECK: [[C40:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK: [[LSHR40:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C40]](s32)
    ; CHECK: [[C41:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK: [[LSHR41:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C41]](s32)
    ; CHECK: [[C42:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK: [[LSHR42:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C42]](s32)
    ; CHECK: [[C43:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK: [[LSHR43:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C43]](s32)
    ; CHECK: [[C44:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK: [[LSHR44:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C44]](s32)
    ; CHECK: [[C45:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[LSHR45:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C45]](s32)
    ; CHECK: [[C46:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR46:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C46]](s32)
    ; CHECK: [[C47:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK: [[LSHR47:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C47]](s32)
    ; CHECK: [[C48:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK: [[LSHR48:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C48]](s32)
    ; CHECK: [[C49:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK: [[LSHR49:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C49]](s32)
    ; CHECK: [[C50:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK: [[LSHR50:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C50]](s32)
    ; CHECK: [[C51:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK: [[LSHR51:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C51]](s32)
    ; CHECK: [[C52:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK: [[LSHR52:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C52]](s32)
    ; CHECK: [[C53:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK: [[LSHR53:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C53]](s32)
    ; CHECK: [[C54:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK: [[LSHR54:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C54]](s32)
    ; CHECK: [[C55:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK: [[LSHR55:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C55]](s32)
    ; CHECK: [[C56:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK: [[LSHR56:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C56]](s32)
    ; CHECK: [[C57:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK: [[LSHR57:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C57]](s32)
    ; CHECK: [[C58:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK: [[LSHR58:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C58]](s32)
    ; CHECK: [[C59:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK: [[LSHR59:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C59]](s32)
    ; CHECK: [[C60:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK: [[LSHR60:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C60]](s32)
    ; CHECK: [[C61:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[LSHR61:%[0-9]+]]:_(s32) = G_LSHR [[UV1]], [[C61]](s32)
    ; CHECK: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF]](s64)
    ; CHECK: [[C62:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[LSHR62:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C62]](s32)
    ; CHECK: [[C63:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[LSHR63:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C63]](s32)
    ; CHECK: [[C64:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[LSHR64:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C64]](s32)
    ; CHECK: [[C65:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[LSHR65:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C65]](s32)
    ; CHECK: [[C66:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[LSHR66:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C66]](s32)
    ; CHECK: [[C67:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK: [[LSHR67:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C67]](s32)
    ; CHECK: [[C68:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[LSHR68:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C68]](s32)
    ; CHECK: [[C69:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[LSHR69:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C69]](s32)
    ; CHECK: [[C70:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK: [[LSHR70:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C70]](s32)
    ; CHECK: [[C71:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK: [[LSHR71:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C71]](s32)
    ; CHECK: [[C72:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK: [[LSHR72:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C72]](s32)
    ; CHECK: [[C73:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK: [[LSHR73:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C73]](s32)
    ; CHECK: [[C74:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK: [[LSHR74:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C74]](s32)
    ; CHECK: [[C75:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK: [[LSHR75:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C75]](s32)
    ; CHECK: [[C76:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[LSHR76:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C76]](s32)
    ; CHECK: [[C77:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR77:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C77]](s32)
    ; CHECK: [[C78:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK: [[LSHR78:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C78]](s32)
    ; CHECK: [[C79:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK: [[LSHR79:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C79]](s32)
    ; CHECK: [[C80:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK: [[LSHR80:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C80]](s32)
    ; CHECK: [[C81:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK: [[LSHR81:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C81]](s32)
    ; CHECK: [[C82:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK: [[LSHR82:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C82]](s32)
    ; CHECK: [[C83:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK: [[LSHR83:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C83]](s32)
    ; CHECK: [[C84:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK: [[LSHR84:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C84]](s32)
    ; CHECK: [[C85:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK: [[LSHR85:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C85]](s32)
    ; CHECK: [[C86:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK: [[LSHR86:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C86]](s32)
    ; CHECK: [[C87:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK: [[LSHR87:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C87]](s32)
    ; CHECK: [[C88:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK: [[LSHR88:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C88]](s32)
    ; CHECK: [[C89:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK: [[LSHR89:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C89]](s32)
    ; CHECK: [[C90:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK: [[LSHR90:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C90]](s32)
    ; CHECK: [[C91:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK: [[LSHR91:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C91]](s32)
    ; CHECK: [[C92:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[LSHR92:%[0-9]+]]:_(s32) = G_LSHR [[UV2]], [[C92]](s32)
    ; CHECK: [[DEF1:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[C93:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[UV]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C93]]
    ; CHECK: [[C94:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[LSHR]](s32)
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C94]]
    ; CHECK: [[C95:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[C95]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; CHECK: [[C96:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[LSHR1]](s32)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[COPY3]], [[C96]]
    ; CHECK: [[C97:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[AND2]], [[C97]](s32)
    ; CHECK: [[OR1:%[0-9]+]]:_(s32) = G_OR [[OR]], [[SHL1]]
    ; CHECK: [[C98:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[LSHR2]](s32)
    ; CHECK: [[AND3:%[0-9]+]]:_(s32) = G_AND [[COPY4]], [[C98]]
    ; CHECK: [[C99:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[AND3]], [[C99]](s32)
    ; CHECK: [[OR2:%[0-9]+]]:_(s32) = G_OR [[OR1]], [[SHL2]]
    ; CHECK: [[C100:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY [[LSHR3]](s32)
    ; CHECK: [[AND4:%[0-9]+]]:_(s32) = G_AND [[COPY5]], [[C100]]
    ; CHECK: [[C101:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[AND4]], [[C101]](s32)
    ; CHECK: [[OR3:%[0-9]+]]:_(s32) = G_OR [[OR2]], [[SHL3]]
    ; CHECK: [[C102:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[LSHR4]](s32)
    ; CHECK: [[AND5:%[0-9]+]]:_(s32) = G_AND [[COPY6]], [[C102]]
    ; CHECK: [[C103:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[AND5]], [[C103]](s32)
    ; CHECK: [[OR4:%[0-9]+]]:_(s32) = G_OR [[OR3]], [[SHL4]]
    ; CHECK: [[C104:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[LSHR5]](s32)
    ; CHECK: [[AND6:%[0-9]+]]:_(s32) = G_AND [[COPY7]], [[C104]]
    ; CHECK: [[C105:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[AND6]], [[C105]](s32)
    ; CHECK: [[OR5:%[0-9]+]]:_(s32) = G_OR [[OR4]], [[SHL5]]
    ; CHECK: [[C106:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY8:%[0-9]+]]:_(s32) = COPY [[LSHR6]](s32)
    ; CHECK: [[AND7:%[0-9]+]]:_(s32) = G_AND [[COPY8]], [[C106]]
    ; CHECK: [[C107:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[SHL6:%[0-9]+]]:_(s32) = G_SHL [[AND7]], [[C107]](s32)
    ; CHECK: [[OR6:%[0-9]+]]:_(s32) = G_OR [[OR5]], [[SHL6]]
    ; CHECK: [[C108:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY9:%[0-9]+]]:_(s32) = COPY [[LSHR7]](s32)
    ; CHECK: [[AND8:%[0-9]+]]:_(s32) = G_AND [[COPY9]], [[C108]]
    ; CHECK: [[C109:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[SHL7:%[0-9]+]]:_(s32) = G_SHL [[AND8]], [[C109]](s32)
    ; CHECK: [[OR7:%[0-9]+]]:_(s32) = G_OR [[OR6]], [[SHL7]]
    ; CHECK: [[C110:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY10:%[0-9]+]]:_(s32) = COPY [[LSHR8]](s32)
    ; CHECK: [[AND9:%[0-9]+]]:_(s32) = G_AND [[COPY10]], [[C110]]
    ; CHECK: [[C111:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK: [[SHL8:%[0-9]+]]:_(s32) = G_SHL [[AND9]], [[C111]](s32)
    ; CHECK: [[OR8:%[0-9]+]]:_(s32) = G_OR [[OR7]], [[SHL8]]
    ; CHECK: [[C112:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY11:%[0-9]+]]:_(s32) = COPY [[LSHR9]](s32)
    ; CHECK: [[AND10:%[0-9]+]]:_(s32) = G_AND [[COPY11]], [[C112]]
    ; CHECK: [[C113:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK: [[SHL9:%[0-9]+]]:_(s32) = G_SHL [[AND10]], [[C113]](s32)
    ; CHECK: [[OR9:%[0-9]+]]:_(s32) = G_OR [[OR8]], [[SHL9]]
    ; CHECK: [[C114:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY12:%[0-9]+]]:_(s32) = COPY [[LSHR10]](s32)
    ; CHECK: [[AND11:%[0-9]+]]:_(s32) = G_AND [[COPY12]], [[C114]]
    ; CHECK: [[C115:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK: [[SHL10:%[0-9]+]]:_(s32) = G_SHL [[AND11]], [[C115]](s32)
    ; CHECK: [[OR10:%[0-9]+]]:_(s32) = G_OR [[OR9]], [[SHL10]]
    ; CHECK: [[C116:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY13:%[0-9]+]]:_(s32) = COPY [[LSHR11]](s32)
    ; CHECK: [[AND12:%[0-9]+]]:_(s32) = G_AND [[COPY13]], [[C116]]
    ; CHECK: [[C117:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK: [[SHL11:%[0-9]+]]:_(s32) = G_SHL [[AND12]], [[C117]](s32)
    ; CHECK: [[OR11:%[0-9]+]]:_(s32) = G_OR [[OR10]], [[SHL11]]
    ; CHECK: [[C118:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY14:%[0-9]+]]:_(s32) = COPY [[LSHR12]](s32)
    ; CHECK: [[AND13:%[0-9]+]]:_(s32) = G_AND [[COPY14]], [[C118]]
    ; CHECK: [[C119:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK: [[SHL12:%[0-9]+]]:_(s32) = G_SHL [[AND13]], [[C119]](s32)
    ; CHECK: [[OR12:%[0-9]+]]:_(s32) = G_OR [[OR11]], [[SHL12]]
    ; CHECK: [[C120:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY15:%[0-9]+]]:_(s32) = COPY [[LSHR13]](s32)
    ; CHECK: [[AND14:%[0-9]+]]:_(s32) = G_AND [[COPY15]], [[C120]]
    ; CHECK: [[C121:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK: [[SHL13:%[0-9]+]]:_(s32) = G_SHL [[AND14]], [[C121]](s32)
    ; CHECK: [[OR13:%[0-9]+]]:_(s32) = G_OR [[OR12]], [[SHL13]]
    ; CHECK: [[C122:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY16:%[0-9]+]]:_(s32) = COPY [[LSHR14]](s32)
    ; CHECK: [[AND15:%[0-9]+]]:_(s32) = G_AND [[COPY16]], [[C122]]
    ; CHECK: [[C123:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[SHL14:%[0-9]+]]:_(s32) = G_SHL [[AND15]], [[C123]](s32)
    ; CHECK: [[OR14:%[0-9]+]]:_(s32) = G_OR [[OR13]], [[SHL14]]
    ; CHECK: [[C124:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY17:%[0-9]+]]:_(s32) = COPY [[LSHR15]](s32)
    ; CHECK: [[AND16:%[0-9]+]]:_(s32) = G_AND [[COPY17]], [[C124]]
    ; CHECK: [[C125:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL15:%[0-9]+]]:_(s32) = G_SHL [[AND16]], [[C125]](s32)
    ; CHECK: [[OR15:%[0-9]+]]:_(s32) = G_OR [[OR14]], [[SHL15]]
    ; CHECK: [[C126:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY18:%[0-9]+]]:_(s32) = COPY [[LSHR16]](s32)
    ; CHECK: [[AND17:%[0-9]+]]:_(s32) = G_AND [[COPY18]], [[C126]]
    ; CHECK: [[C127:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK: [[SHL16:%[0-9]+]]:_(s32) = G_SHL [[AND17]], [[C127]](s32)
    ; CHECK: [[OR16:%[0-9]+]]:_(s32) = G_OR [[OR15]], [[SHL16]]
    ; CHECK: [[C128:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY19:%[0-9]+]]:_(s32) = COPY [[LSHR17]](s32)
    ; CHECK: [[AND18:%[0-9]+]]:_(s32) = G_AND [[COPY19]], [[C128]]
    ; CHECK: [[C129:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK: [[SHL17:%[0-9]+]]:_(s32) = G_SHL [[AND18]], [[C129]](s32)
    ; CHECK: [[OR17:%[0-9]+]]:_(s32) = G_OR [[OR16]], [[SHL17]]
    ; CHECK: [[C130:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY20:%[0-9]+]]:_(s32) = COPY [[LSHR18]](s32)
    ; CHECK: [[AND19:%[0-9]+]]:_(s32) = G_AND [[COPY20]], [[C130]]
    ; CHECK: [[C131:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK: [[SHL18:%[0-9]+]]:_(s32) = G_SHL [[AND19]], [[C131]](s32)
    ; CHECK: [[OR18:%[0-9]+]]:_(s32) = G_OR [[OR17]], [[SHL18]]
    ; CHECK: [[C132:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY21:%[0-9]+]]:_(s32) = COPY [[LSHR19]](s32)
    ; CHECK: [[AND20:%[0-9]+]]:_(s32) = G_AND [[COPY21]], [[C132]]
    ; CHECK: [[C133:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK: [[SHL19:%[0-9]+]]:_(s32) = G_SHL [[AND20]], [[C133]](s32)
    ; CHECK: [[OR19:%[0-9]+]]:_(s32) = G_OR [[OR18]], [[SHL19]]
    ; CHECK: [[C134:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY22:%[0-9]+]]:_(s32) = COPY [[LSHR20]](s32)
    ; CHECK: [[AND21:%[0-9]+]]:_(s32) = G_AND [[COPY22]], [[C134]]
    ; CHECK: [[C135:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK: [[SHL20:%[0-9]+]]:_(s32) = G_SHL [[AND21]], [[C135]](s32)
    ; CHECK: [[OR20:%[0-9]+]]:_(s32) = G_OR [[OR19]], [[SHL20]]
    ; CHECK: [[C136:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY23:%[0-9]+]]:_(s32) = COPY [[LSHR21]](s32)
    ; CHECK: [[AND22:%[0-9]+]]:_(s32) = G_AND [[COPY23]], [[C136]]
    ; CHECK: [[C137:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK: [[SHL21:%[0-9]+]]:_(s32) = G_SHL [[AND22]], [[C137]](s32)
    ; CHECK: [[OR21:%[0-9]+]]:_(s32) = G_OR [[OR20]], [[SHL21]]
    ; CHECK: [[C138:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY24:%[0-9]+]]:_(s32) = COPY [[LSHR22]](s32)
    ; CHECK: [[AND23:%[0-9]+]]:_(s32) = G_AND [[COPY24]], [[C138]]
    ; CHECK: [[C139:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK: [[SHL22:%[0-9]+]]:_(s32) = G_SHL [[AND23]], [[C139]](s32)
    ; CHECK: [[OR22:%[0-9]+]]:_(s32) = G_OR [[OR21]], [[SHL22]]
    ; CHECK: [[C140:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY25:%[0-9]+]]:_(s32) = COPY [[LSHR23]](s32)
    ; CHECK: [[AND24:%[0-9]+]]:_(s32) = G_AND [[COPY25]], [[C140]]
    ; CHECK: [[C141:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK: [[SHL23:%[0-9]+]]:_(s32) = G_SHL [[AND24]], [[C141]](s32)
    ; CHECK: [[OR23:%[0-9]+]]:_(s32) = G_OR [[OR22]], [[SHL23]]
    ; CHECK: [[C142:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY26:%[0-9]+]]:_(s32) = COPY [[LSHR24]](s32)
    ; CHECK: [[AND25:%[0-9]+]]:_(s32) = G_AND [[COPY26]], [[C142]]
    ; CHECK: [[C143:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK: [[SHL24:%[0-9]+]]:_(s32) = G_SHL [[AND25]], [[C143]](s32)
    ; CHECK: [[OR24:%[0-9]+]]:_(s32) = G_OR [[OR23]], [[SHL24]]
    ; CHECK: [[C144:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY27:%[0-9]+]]:_(s32) = COPY [[LSHR25]](s32)
    ; CHECK: [[AND26:%[0-9]+]]:_(s32) = G_AND [[COPY27]], [[C144]]
    ; CHECK: [[C145:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK: [[SHL25:%[0-9]+]]:_(s32) = G_SHL [[AND26]], [[C145]](s32)
    ; CHECK: [[OR25:%[0-9]+]]:_(s32) = G_OR [[OR24]], [[SHL25]]
    ; CHECK: [[C146:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY28:%[0-9]+]]:_(s32) = COPY [[LSHR26]](s32)
    ; CHECK: [[AND27:%[0-9]+]]:_(s32) = G_AND [[COPY28]], [[C146]]
    ; CHECK: [[C147:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK: [[SHL26:%[0-9]+]]:_(s32) = G_SHL [[AND27]], [[C147]](s32)
    ; CHECK: [[OR26:%[0-9]+]]:_(s32) = G_OR [[OR25]], [[SHL26]]
    ; CHECK: [[C148:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY29:%[0-9]+]]:_(s32) = COPY [[LSHR27]](s32)
    ; CHECK: [[AND28:%[0-9]+]]:_(s32) = G_AND [[COPY29]], [[C148]]
    ; CHECK: [[C149:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK: [[SHL27:%[0-9]+]]:_(s32) = G_SHL [[AND28]], [[C149]](s32)
    ; CHECK: [[OR27:%[0-9]+]]:_(s32) = G_OR [[OR26]], [[SHL27]]
    ; CHECK: [[C150:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY30:%[0-9]+]]:_(s32) = COPY [[LSHR28]](s32)
    ; CHECK: [[AND29:%[0-9]+]]:_(s32) = G_AND [[COPY30]], [[C150]]
    ; CHECK: [[C151:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK: [[SHL28:%[0-9]+]]:_(s32) = G_SHL [[AND29]], [[C151]](s32)
    ; CHECK: [[OR28:%[0-9]+]]:_(s32) = G_OR [[OR27]], [[SHL28]]
    ; CHECK: [[C152:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY31:%[0-9]+]]:_(s32) = COPY [[LSHR29]](s32)
    ; CHECK: [[AND30:%[0-9]+]]:_(s32) = G_AND [[COPY31]], [[C152]]
    ; CHECK: [[C153:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK: [[SHL29:%[0-9]+]]:_(s32) = G_SHL [[AND30]], [[C153]](s32)
    ; CHECK: [[OR29:%[0-9]+]]:_(s32) = G_OR [[OR28]], [[SHL29]]
    ; CHECK: [[C154:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY32:%[0-9]+]]:_(s32) = COPY [[LSHR30]](s32)
    ; CHECK: [[AND31:%[0-9]+]]:_(s32) = G_AND [[COPY32]], [[C154]]
    ; CHECK: [[C155:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[SHL30:%[0-9]+]]:_(s32) = G_SHL [[AND31]], [[C155]](s32)
    ; CHECK: [[OR30:%[0-9]+]]:_(s32) = G_OR [[OR29]], [[SHL30]]
    ; CHECK: [[C156:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY33:%[0-9]+]]:_(s32) = COPY [[UV1]](s32)
    ; CHECK: [[AND32:%[0-9]+]]:_(s32) = G_AND [[COPY33]], [[C156]]
    ; CHECK: [[C157:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY34:%[0-9]+]]:_(s32) = COPY [[LSHR31]](s32)
    ; CHECK: [[AND33:%[0-9]+]]:_(s32) = G_AND [[COPY34]], [[C157]]
    ; CHECK: [[C158:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[SHL31:%[0-9]+]]:_(s32) = G_SHL [[AND33]], [[C158]](s32)
    ; CHECK: [[OR31:%[0-9]+]]:_(s32) = G_OR [[AND32]], [[SHL31]]
    ; CHECK: [[C159:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY35:%[0-9]+]]:_(s32) = COPY [[LSHR32]](s32)
    ; CHECK: [[AND34:%[0-9]+]]:_(s32) = G_AND [[COPY35]], [[C159]]
    ; CHECK: [[C160:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[SHL32:%[0-9]+]]:_(s32) = G_SHL [[AND34]], [[C160]](s32)
    ; CHECK: [[OR32:%[0-9]+]]:_(s32) = G_OR [[OR31]], [[SHL32]]
    ; CHECK: [[C161:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY36:%[0-9]+]]:_(s32) = COPY [[LSHR33]](s32)
    ; CHECK: [[AND35:%[0-9]+]]:_(s32) = G_AND [[COPY36]], [[C161]]
    ; CHECK: [[C162:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[SHL33:%[0-9]+]]:_(s32) = G_SHL [[AND35]], [[C162]](s32)
    ; CHECK: [[OR33:%[0-9]+]]:_(s32) = G_OR [[OR32]], [[SHL33]]
    ; CHECK: [[C163:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY37:%[0-9]+]]:_(s32) = COPY [[LSHR34]](s32)
    ; CHECK: [[AND36:%[0-9]+]]:_(s32) = G_AND [[COPY37]], [[C163]]
    ; CHECK: [[C164:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[SHL34:%[0-9]+]]:_(s32) = G_SHL [[AND36]], [[C164]](s32)
    ; CHECK: [[OR34:%[0-9]+]]:_(s32) = G_OR [[OR33]], [[SHL34]]
    ; CHECK: [[C165:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY38:%[0-9]+]]:_(s32) = COPY [[LSHR35]](s32)
    ; CHECK: [[AND37:%[0-9]+]]:_(s32) = G_AND [[COPY38]], [[C165]]
    ; CHECK: [[C166:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[SHL35:%[0-9]+]]:_(s32) = G_SHL [[AND37]], [[C166]](s32)
    ; CHECK: [[OR35:%[0-9]+]]:_(s32) = G_OR [[OR34]], [[SHL35]]
    ; CHECK: [[C167:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY39:%[0-9]+]]:_(s32) = COPY [[LSHR36]](s32)
    ; CHECK: [[AND38:%[0-9]+]]:_(s32) = G_AND [[COPY39]], [[C167]]
    ; CHECK: [[C168:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK: [[SHL36:%[0-9]+]]:_(s32) = G_SHL [[AND38]], [[C168]](s32)
    ; CHECK: [[OR36:%[0-9]+]]:_(s32) = G_OR [[OR35]], [[SHL36]]
    ; CHECK: [[C169:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY40:%[0-9]+]]:_(s32) = COPY [[LSHR37]](s32)
    ; CHECK: [[AND39:%[0-9]+]]:_(s32) = G_AND [[COPY40]], [[C169]]
    ; CHECK: [[C170:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[SHL37:%[0-9]+]]:_(s32) = G_SHL [[AND39]], [[C170]](s32)
    ; CHECK: [[OR37:%[0-9]+]]:_(s32) = G_OR [[OR36]], [[SHL37]]
    ; CHECK: [[C171:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY41:%[0-9]+]]:_(s32) = COPY [[LSHR38]](s32)
    ; CHECK: [[AND40:%[0-9]+]]:_(s32) = G_AND [[COPY41]], [[C171]]
    ; CHECK: [[C172:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[SHL38:%[0-9]+]]:_(s32) = G_SHL [[AND40]], [[C172]](s32)
    ; CHECK: [[OR38:%[0-9]+]]:_(s32) = G_OR [[OR37]], [[SHL38]]
    ; CHECK: [[C173:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY42:%[0-9]+]]:_(s32) = COPY [[LSHR39]](s32)
    ; CHECK: [[AND41:%[0-9]+]]:_(s32) = G_AND [[COPY42]], [[C173]]
    ; CHECK: [[C174:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK: [[SHL39:%[0-9]+]]:_(s32) = G_SHL [[AND41]], [[C174]](s32)
    ; CHECK: [[OR39:%[0-9]+]]:_(s32) = G_OR [[OR38]], [[SHL39]]
    ; CHECK: [[C175:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY43:%[0-9]+]]:_(s32) = COPY [[LSHR40]](s32)
    ; CHECK: [[AND42:%[0-9]+]]:_(s32) = G_AND [[COPY43]], [[C175]]
    ; CHECK: [[C176:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK: [[SHL40:%[0-9]+]]:_(s32) = G_SHL [[AND42]], [[C176]](s32)
    ; CHECK: [[OR40:%[0-9]+]]:_(s32) = G_OR [[OR39]], [[SHL40]]
    ; CHECK: [[C177:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY44:%[0-9]+]]:_(s32) = COPY [[LSHR41]](s32)
    ; CHECK: [[AND43:%[0-9]+]]:_(s32) = G_AND [[COPY44]], [[C177]]
    ; CHECK: [[C178:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK: [[SHL41:%[0-9]+]]:_(s32) = G_SHL [[AND43]], [[C178]](s32)
    ; CHECK: [[OR41:%[0-9]+]]:_(s32) = G_OR [[OR40]], [[SHL41]]
    ; CHECK: [[C179:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY45:%[0-9]+]]:_(s32) = COPY [[LSHR42]](s32)
    ; CHECK: [[AND44:%[0-9]+]]:_(s32) = G_AND [[COPY45]], [[C179]]
    ; CHECK: [[C180:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK: [[SHL42:%[0-9]+]]:_(s32) = G_SHL [[AND44]], [[C180]](s32)
    ; CHECK: [[OR42:%[0-9]+]]:_(s32) = G_OR [[OR41]], [[SHL42]]
    ; CHECK: [[C181:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY46:%[0-9]+]]:_(s32) = COPY [[LSHR43]](s32)
    ; CHECK: [[AND45:%[0-9]+]]:_(s32) = G_AND [[COPY46]], [[C181]]
    ; CHECK: [[C182:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK: [[SHL43:%[0-9]+]]:_(s32) = G_SHL [[AND45]], [[C182]](s32)
    ; CHECK: [[OR43:%[0-9]+]]:_(s32) = G_OR [[OR42]], [[SHL43]]
    ; CHECK: [[C183:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY47:%[0-9]+]]:_(s32) = COPY [[LSHR44]](s32)
    ; CHECK: [[AND46:%[0-9]+]]:_(s32) = G_AND [[COPY47]], [[C183]]
    ; CHECK: [[C184:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK: [[SHL44:%[0-9]+]]:_(s32) = G_SHL [[AND46]], [[C184]](s32)
    ; CHECK: [[OR44:%[0-9]+]]:_(s32) = G_OR [[OR43]], [[SHL44]]
    ; CHECK: [[C185:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY48:%[0-9]+]]:_(s32) = COPY [[LSHR45]](s32)
    ; CHECK: [[AND47:%[0-9]+]]:_(s32) = G_AND [[COPY48]], [[C185]]
    ; CHECK: [[C186:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[SHL45:%[0-9]+]]:_(s32) = G_SHL [[AND47]], [[C186]](s32)
    ; CHECK: [[OR45:%[0-9]+]]:_(s32) = G_OR [[OR44]], [[SHL45]]
    ; CHECK: [[C187:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY49:%[0-9]+]]:_(s32) = COPY [[LSHR46]](s32)
    ; CHECK: [[AND48:%[0-9]+]]:_(s32) = G_AND [[COPY49]], [[C187]]
    ; CHECK: [[C188:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL46:%[0-9]+]]:_(s32) = G_SHL [[AND48]], [[C188]](s32)
    ; CHECK: [[OR46:%[0-9]+]]:_(s32) = G_OR [[OR45]], [[SHL46]]
    ; CHECK: [[C189:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY50:%[0-9]+]]:_(s32) = COPY [[LSHR47]](s32)
    ; CHECK: [[AND49:%[0-9]+]]:_(s32) = G_AND [[COPY50]], [[C189]]
    ; CHECK: [[C190:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK: [[SHL47:%[0-9]+]]:_(s32) = G_SHL [[AND49]], [[C190]](s32)
    ; CHECK: [[OR47:%[0-9]+]]:_(s32) = G_OR [[OR46]], [[SHL47]]
    ; CHECK: [[C191:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY51:%[0-9]+]]:_(s32) = COPY [[LSHR48]](s32)
    ; CHECK: [[AND50:%[0-9]+]]:_(s32) = G_AND [[COPY51]], [[C191]]
    ; CHECK: [[C192:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK: [[SHL48:%[0-9]+]]:_(s32) = G_SHL [[AND50]], [[C192]](s32)
    ; CHECK: [[OR48:%[0-9]+]]:_(s32) = G_OR [[OR47]], [[SHL48]]
    ; CHECK: [[C193:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY52:%[0-9]+]]:_(s32) = COPY [[LSHR49]](s32)
    ; CHECK: [[AND51:%[0-9]+]]:_(s32) = G_AND [[COPY52]], [[C193]]
    ; CHECK: [[C194:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK: [[SHL49:%[0-9]+]]:_(s32) = G_SHL [[AND51]], [[C194]](s32)
    ; CHECK: [[OR49:%[0-9]+]]:_(s32) = G_OR [[OR48]], [[SHL49]]
    ; CHECK: [[C195:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY53:%[0-9]+]]:_(s32) = COPY [[LSHR50]](s32)
    ; CHECK: [[AND52:%[0-9]+]]:_(s32) = G_AND [[COPY53]], [[C195]]
    ; CHECK: [[C196:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK: [[SHL50:%[0-9]+]]:_(s32) = G_SHL [[AND52]], [[C196]](s32)
    ; CHECK: [[OR50:%[0-9]+]]:_(s32) = G_OR [[OR49]], [[SHL50]]
    ; CHECK: [[C197:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY54:%[0-9]+]]:_(s32) = COPY [[LSHR51]](s32)
    ; CHECK: [[AND53:%[0-9]+]]:_(s32) = G_AND [[COPY54]], [[C197]]
    ; CHECK: [[C198:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK: [[SHL51:%[0-9]+]]:_(s32) = G_SHL [[AND53]], [[C198]](s32)
    ; CHECK: [[OR51:%[0-9]+]]:_(s32) = G_OR [[OR50]], [[SHL51]]
    ; CHECK: [[C199:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY55:%[0-9]+]]:_(s32) = COPY [[LSHR52]](s32)
    ; CHECK: [[AND54:%[0-9]+]]:_(s32) = G_AND [[COPY55]], [[C199]]
    ; CHECK: [[C200:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK: [[SHL52:%[0-9]+]]:_(s32) = G_SHL [[AND54]], [[C200]](s32)
    ; CHECK: [[OR52:%[0-9]+]]:_(s32) = G_OR [[OR51]], [[SHL52]]
    ; CHECK: [[C201:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY56:%[0-9]+]]:_(s32) = COPY [[LSHR53]](s32)
    ; CHECK: [[AND55:%[0-9]+]]:_(s32) = G_AND [[COPY56]], [[C201]]
    ; CHECK: [[C202:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK: [[SHL53:%[0-9]+]]:_(s32) = G_SHL [[AND55]], [[C202]](s32)
    ; CHECK: [[OR53:%[0-9]+]]:_(s32) = G_OR [[OR52]], [[SHL53]]
    ; CHECK: [[C203:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY57:%[0-9]+]]:_(s32) = COPY [[LSHR54]](s32)
    ; CHECK: [[AND56:%[0-9]+]]:_(s32) = G_AND [[COPY57]], [[C203]]
    ; CHECK: [[C204:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK: [[SHL54:%[0-9]+]]:_(s32) = G_SHL [[AND56]], [[C204]](s32)
    ; CHECK: [[OR54:%[0-9]+]]:_(s32) = G_OR [[OR53]], [[SHL54]]
    ; CHECK: [[C205:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY58:%[0-9]+]]:_(s32) = COPY [[LSHR55]](s32)
    ; CHECK: [[AND57:%[0-9]+]]:_(s32) = G_AND [[COPY58]], [[C205]]
    ; CHECK: [[C206:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK: [[SHL55:%[0-9]+]]:_(s32) = G_SHL [[AND57]], [[C206]](s32)
    ; CHECK: [[OR55:%[0-9]+]]:_(s32) = G_OR [[OR54]], [[SHL55]]
    ; CHECK: [[C207:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY59:%[0-9]+]]:_(s32) = COPY [[LSHR56]](s32)
    ; CHECK: [[AND58:%[0-9]+]]:_(s32) = G_AND [[COPY59]], [[C207]]
    ; CHECK: [[C208:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK: [[SHL56:%[0-9]+]]:_(s32) = G_SHL [[AND58]], [[C208]](s32)
    ; CHECK: [[OR56:%[0-9]+]]:_(s32) = G_OR [[OR55]], [[SHL56]]
    ; CHECK: [[C209:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY60:%[0-9]+]]:_(s32) = COPY [[LSHR57]](s32)
    ; CHECK: [[AND59:%[0-9]+]]:_(s32) = G_AND [[COPY60]], [[C209]]
    ; CHECK: [[C210:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK: [[SHL57:%[0-9]+]]:_(s32) = G_SHL [[AND59]], [[C210]](s32)
    ; CHECK: [[OR57:%[0-9]+]]:_(s32) = G_OR [[OR56]], [[SHL57]]
    ; CHECK: [[C211:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY61:%[0-9]+]]:_(s32) = COPY [[LSHR58]](s32)
    ; CHECK: [[AND60:%[0-9]+]]:_(s32) = G_AND [[COPY61]], [[C211]]
    ; CHECK: [[C212:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK: [[SHL58:%[0-9]+]]:_(s32) = G_SHL [[AND60]], [[C212]](s32)
    ; CHECK: [[OR58:%[0-9]+]]:_(s32) = G_OR [[OR57]], [[SHL58]]
    ; CHECK: [[C213:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY62:%[0-9]+]]:_(s32) = COPY [[LSHR59]](s32)
    ; CHECK: [[AND61:%[0-9]+]]:_(s32) = G_AND [[COPY62]], [[C213]]
    ; CHECK: [[C214:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK: [[SHL59:%[0-9]+]]:_(s32) = G_SHL [[AND61]], [[C214]](s32)
    ; CHECK: [[OR59:%[0-9]+]]:_(s32) = G_OR [[OR58]], [[SHL59]]
    ; CHECK: [[C215:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY63:%[0-9]+]]:_(s32) = COPY [[LSHR60]](s32)
    ; CHECK: [[AND62:%[0-9]+]]:_(s32) = G_AND [[COPY63]], [[C215]]
    ; CHECK: [[C216:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK: [[SHL60:%[0-9]+]]:_(s32) = G_SHL [[AND62]], [[C216]](s32)
    ; CHECK: [[OR60:%[0-9]+]]:_(s32) = G_OR [[OR59]], [[SHL60]]
    ; CHECK: [[C217:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY64:%[0-9]+]]:_(s32) = COPY [[LSHR61]](s32)
    ; CHECK: [[AND63:%[0-9]+]]:_(s32) = G_AND [[COPY64]], [[C217]]
    ; CHECK: [[C218:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[SHL61:%[0-9]+]]:_(s32) = G_SHL [[AND63]], [[C218]](s32)
    ; CHECK: [[OR61:%[0-9]+]]:_(s32) = G_OR [[OR60]], [[SHL61]]
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[OR30]](s32), [[OR61]](s32)
    ; CHECK: [[C219:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY65:%[0-9]+]]:_(s32) = COPY [[UV2]](s32)
    ; CHECK: [[AND64:%[0-9]+]]:_(s32) = G_AND [[COPY65]], [[C219]]
    ; CHECK: [[C220:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY66:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND65:%[0-9]+]]:_(s32) = G_AND [[COPY66]], [[C220]]
    ; CHECK: [[C221:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[SHL62:%[0-9]+]]:_(s32) = G_SHL [[AND65]], [[C221]](s32)
    ; CHECK: [[OR62:%[0-9]+]]:_(s32) = G_OR [[AND64]], [[SHL62]]
    ; CHECK: [[C222:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY67:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND66:%[0-9]+]]:_(s32) = G_AND [[COPY67]], [[C222]]
    ; CHECK: [[C223:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[SHL63:%[0-9]+]]:_(s32) = G_SHL [[AND66]], [[C223]](s32)
    ; CHECK: [[OR63:%[0-9]+]]:_(s32) = G_OR [[OR62]], [[SHL63]]
    ; CHECK: [[C224:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY68:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND67:%[0-9]+]]:_(s32) = G_AND [[COPY68]], [[C224]]
    ; CHECK: [[C225:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[SHL64:%[0-9]+]]:_(s32) = G_SHL [[AND67]], [[C225]](s32)
    ; CHECK: [[OR64:%[0-9]+]]:_(s32) = G_OR [[OR63]], [[SHL64]]
    ; CHECK: [[C226:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY69:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND68:%[0-9]+]]:_(s32) = G_AND [[COPY69]], [[C226]]
    ; CHECK: [[C227:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[SHL65:%[0-9]+]]:_(s32) = G_SHL [[AND68]], [[C227]](s32)
    ; CHECK: [[OR65:%[0-9]+]]:_(s32) = G_OR [[OR64]], [[SHL65]]
    ; CHECK: [[C228:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY70:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND69:%[0-9]+]]:_(s32) = G_AND [[COPY70]], [[C228]]
    ; CHECK: [[C229:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[SHL66:%[0-9]+]]:_(s32) = G_SHL [[AND69]], [[C229]](s32)
    ; CHECK: [[OR66:%[0-9]+]]:_(s32) = G_OR [[OR65]], [[SHL66]]
    ; CHECK: [[C230:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY71:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND70:%[0-9]+]]:_(s32) = G_AND [[COPY71]], [[C230]]
    ; CHECK: [[C231:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK: [[SHL67:%[0-9]+]]:_(s32) = G_SHL [[AND70]], [[C231]](s32)
    ; CHECK: [[OR67:%[0-9]+]]:_(s32) = G_OR [[OR66]], [[SHL67]]
    ; CHECK: [[C232:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY72:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND71:%[0-9]+]]:_(s32) = G_AND [[COPY72]], [[C232]]
    ; CHECK: [[C233:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[SHL68:%[0-9]+]]:_(s32) = G_SHL [[AND71]], [[C233]](s32)
    ; CHECK: [[OR68:%[0-9]+]]:_(s32) = G_OR [[OR67]], [[SHL68]]
    ; CHECK: [[C234:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY73:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND72:%[0-9]+]]:_(s32) = G_AND [[COPY73]], [[C234]]
    ; CHECK: [[C235:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[SHL69:%[0-9]+]]:_(s32) = G_SHL [[AND72]], [[C235]](s32)
    ; CHECK: [[OR69:%[0-9]+]]:_(s32) = G_OR [[OR68]], [[SHL69]]
    ; CHECK: [[C236:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY74:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND73:%[0-9]+]]:_(s32) = G_AND [[COPY74]], [[C236]]
    ; CHECK: [[C237:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK: [[SHL70:%[0-9]+]]:_(s32) = G_SHL [[AND73]], [[C237]](s32)
    ; CHECK: [[OR70:%[0-9]+]]:_(s32) = G_OR [[OR69]], [[SHL70]]
    ; CHECK: [[C238:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY75:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND74:%[0-9]+]]:_(s32) = G_AND [[COPY75]], [[C238]]
    ; CHECK: [[C239:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK: [[SHL71:%[0-9]+]]:_(s32) = G_SHL [[AND74]], [[C239]](s32)
    ; CHECK: [[OR71:%[0-9]+]]:_(s32) = G_OR [[OR70]], [[SHL71]]
    ; CHECK: [[C240:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY76:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND75:%[0-9]+]]:_(s32) = G_AND [[COPY76]], [[C240]]
    ; CHECK: [[C241:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK: [[SHL72:%[0-9]+]]:_(s32) = G_SHL [[AND75]], [[C241]](s32)
    ; CHECK: [[OR72:%[0-9]+]]:_(s32) = G_OR [[OR71]], [[SHL72]]
    ; CHECK: [[C242:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY77:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND76:%[0-9]+]]:_(s32) = G_AND [[COPY77]], [[C242]]
    ; CHECK: [[C243:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK: [[SHL73:%[0-9]+]]:_(s32) = G_SHL [[AND76]], [[C243]](s32)
    ; CHECK: [[OR73:%[0-9]+]]:_(s32) = G_OR [[OR72]], [[SHL73]]
    ; CHECK: [[C244:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY78:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND77:%[0-9]+]]:_(s32) = G_AND [[COPY78]], [[C244]]
    ; CHECK: [[C245:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK: [[SHL74:%[0-9]+]]:_(s32) = G_SHL [[AND77]], [[C245]](s32)
    ; CHECK: [[OR74:%[0-9]+]]:_(s32) = G_OR [[OR73]], [[SHL74]]
    ; CHECK: [[C246:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY79:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND78:%[0-9]+]]:_(s32) = G_AND [[COPY79]], [[C246]]
    ; CHECK: [[C247:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK: [[SHL75:%[0-9]+]]:_(s32) = G_SHL [[AND78]], [[C247]](s32)
    ; CHECK: [[OR75:%[0-9]+]]:_(s32) = G_OR [[OR74]], [[SHL75]]
    ; CHECK: [[C248:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY80:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND79:%[0-9]+]]:_(s32) = G_AND [[COPY80]], [[C248]]
    ; CHECK: [[C249:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[SHL76:%[0-9]+]]:_(s32) = G_SHL [[AND79]], [[C249]](s32)
    ; CHECK: [[OR76:%[0-9]+]]:_(s32) = G_OR [[OR75]], [[SHL76]]
    ; CHECK: [[C250:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY81:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND80:%[0-9]+]]:_(s32) = G_AND [[COPY81]], [[C250]]
    ; CHECK: [[C251:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL77:%[0-9]+]]:_(s32) = G_SHL [[AND80]], [[C251]](s32)
    ; CHECK: [[OR77:%[0-9]+]]:_(s32) = G_OR [[OR76]], [[SHL77]]
    ; CHECK: [[C252:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY82:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND81:%[0-9]+]]:_(s32) = G_AND [[COPY82]], [[C252]]
    ; CHECK: [[C253:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK: [[SHL78:%[0-9]+]]:_(s32) = G_SHL [[AND81]], [[C253]](s32)
    ; CHECK: [[OR78:%[0-9]+]]:_(s32) = G_OR [[OR77]], [[SHL78]]
    ; CHECK: [[C254:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY83:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND82:%[0-9]+]]:_(s32) = G_AND [[COPY83]], [[C254]]
    ; CHECK: [[C255:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK: [[SHL79:%[0-9]+]]:_(s32) = G_SHL [[AND82]], [[C255]](s32)
    ; CHECK: [[OR79:%[0-9]+]]:_(s32) = G_OR [[OR78]], [[SHL79]]
    ; CHECK: [[C256:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY84:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND83:%[0-9]+]]:_(s32) = G_AND [[COPY84]], [[C256]]
    ; CHECK: [[C257:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK: [[SHL80:%[0-9]+]]:_(s32) = G_SHL [[AND83]], [[C257]](s32)
    ; CHECK: [[OR80:%[0-9]+]]:_(s32) = G_OR [[OR79]], [[SHL80]]
    ; CHECK: [[C258:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY85:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND84:%[0-9]+]]:_(s32) = G_AND [[COPY85]], [[C258]]
    ; CHECK: [[C259:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK: [[SHL81:%[0-9]+]]:_(s32) = G_SHL [[AND84]], [[C259]](s32)
    ; CHECK: [[OR81:%[0-9]+]]:_(s32) = G_OR [[OR80]], [[SHL81]]
    ; CHECK: [[C260:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY86:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND85:%[0-9]+]]:_(s32) = G_AND [[COPY86]], [[C260]]
    ; CHECK: [[C261:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK: [[SHL82:%[0-9]+]]:_(s32) = G_SHL [[AND85]], [[C261]](s32)
    ; CHECK: [[OR82:%[0-9]+]]:_(s32) = G_OR [[OR81]], [[SHL82]]
    ; CHECK: [[C262:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY87:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND86:%[0-9]+]]:_(s32) = G_AND [[COPY87]], [[C262]]
    ; CHECK: [[C263:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK: [[SHL83:%[0-9]+]]:_(s32) = G_SHL [[AND86]], [[C263]](s32)
    ; CHECK: [[OR83:%[0-9]+]]:_(s32) = G_OR [[OR82]], [[SHL83]]
    ; CHECK: [[C264:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY88:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND87:%[0-9]+]]:_(s32) = G_AND [[COPY88]], [[C264]]
    ; CHECK: [[C265:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK: [[SHL84:%[0-9]+]]:_(s32) = G_SHL [[AND87]], [[C265]](s32)
    ; CHECK: [[OR84:%[0-9]+]]:_(s32) = G_OR [[OR83]], [[SHL84]]
    ; CHECK: [[C266:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY89:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND88:%[0-9]+]]:_(s32) = G_AND [[COPY89]], [[C266]]
    ; CHECK: [[C267:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK: [[SHL85:%[0-9]+]]:_(s32) = G_SHL [[AND88]], [[C267]](s32)
    ; CHECK: [[OR85:%[0-9]+]]:_(s32) = G_OR [[OR84]], [[SHL85]]
    ; CHECK: [[C268:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY90:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND89:%[0-9]+]]:_(s32) = G_AND [[COPY90]], [[C268]]
    ; CHECK: [[C269:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK: [[SHL86:%[0-9]+]]:_(s32) = G_SHL [[AND89]], [[C269]](s32)
    ; CHECK: [[OR86:%[0-9]+]]:_(s32) = G_OR [[OR85]], [[SHL86]]
    ; CHECK: [[C270:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY91:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND90:%[0-9]+]]:_(s32) = G_AND [[COPY91]], [[C270]]
    ; CHECK: [[C271:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK: [[SHL87:%[0-9]+]]:_(s32) = G_SHL [[AND90]], [[C271]](s32)
    ; CHECK: [[OR87:%[0-9]+]]:_(s32) = G_OR [[OR86]], [[SHL87]]
    ; CHECK: [[C272:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY92:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND91:%[0-9]+]]:_(s32) = G_AND [[COPY92]], [[C272]]
    ; CHECK: [[C273:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK: [[SHL88:%[0-9]+]]:_(s32) = G_SHL [[AND91]], [[C273]](s32)
    ; CHECK: [[OR88:%[0-9]+]]:_(s32) = G_OR [[OR87]], [[SHL88]]
    ; CHECK: [[C274:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY93:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND92:%[0-9]+]]:_(s32) = G_AND [[COPY93]], [[C274]]
    ; CHECK: [[C275:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK: [[SHL89:%[0-9]+]]:_(s32) = G_SHL [[AND92]], [[C275]](s32)
    ; CHECK: [[OR89:%[0-9]+]]:_(s32) = G_OR [[OR88]], [[SHL89]]
    ; CHECK: [[C276:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY94:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND93:%[0-9]+]]:_(s32) = G_AND [[COPY94]], [[C276]]
    ; CHECK: [[C277:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK: [[SHL90:%[0-9]+]]:_(s32) = G_SHL [[AND93]], [[C277]](s32)
    ; CHECK: [[OR90:%[0-9]+]]:_(s32) = G_OR [[OR89]], [[SHL90]]
    ; CHECK: [[C278:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY95:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND94:%[0-9]+]]:_(s32) = G_AND [[COPY95]], [[C278]]
    ; CHECK: [[C279:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK: [[SHL91:%[0-9]+]]:_(s32) = G_SHL [[AND94]], [[C279]](s32)
    ; CHECK: [[OR91:%[0-9]+]]:_(s32) = G_OR [[OR90]], [[SHL91]]
    ; CHECK: [[C280:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY96:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND95:%[0-9]+]]:_(s32) = G_AND [[COPY96]], [[C280]]
    ; CHECK: [[C281:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[SHL92:%[0-9]+]]:_(s32) = G_SHL [[AND95]], [[C281]](s32)
    ; CHECK: [[OR92:%[0-9]+]]:_(s32) = G_OR [[OR91]], [[SHL92]]
    ; CHECK: [[C282:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY97:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND96:%[0-9]+]]:_(s32) = G_AND [[COPY97]], [[C282]]
    ; CHECK: [[C283:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY98:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND97:%[0-9]+]]:_(s32) = G_AND [[COPY98]], [[C283]]
    ; CHECK: [[C284:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[SHL93:%[0-9]+]]:_(s32) = G_SHL [[AND97]], [[C284]](s32)
    ; CHECK: [[OR93:%[0-9]+]]:_(s32) = G_OR [[AND96]], [[SHL93]]
    ; CHECK: [[C285:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY99:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND98:%[0-9]+]]:_(s32) = G_AND [[COPY99]], [[C285]]
    ; CHECK: [[C286:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[SHL94:%[0-9]+]]:_(s32) = G_SHL [[AND98]], [[C286]](s32)
    ; CHECK: [[OR94:%[0-9]+]]:_(s32) = G_OR [[OR93]], [[SHL94]]
    ; CHECK: [[C287:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY100:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND99:%[0-9]+]]:_(s32) = G_AND [[COPY100]], [[C287]]
    ; CHECK: [[C288:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[SHL95:%[0-9]+]]:_(s32) = G_SHL [[AND99]], [[C288]](s32)
    ; CHECK: [[OR95:%[0-9]+]]:_(s32) = G_OR [[OR94]], [[SHL95]]
    ; CHECK: [[C289:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY101:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND100:%[0-9]+]]:_(s32) = G_AND [[COPY101]], [[C289]]
    ; CHECK: [[C290:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[SHL96:%[0-9]+]]:_(s32) = G_SHL [[AND100]], [[C290]](s32)
    ; CHECK: [[OR96:%[0-9]+]]:_(s32) = G_OR [[OR95]], [[SHL96]]
    ; CHECK: [[C291:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY102:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND101:%[0-9]+]]:_(s32) = G_AND [[COPY102]], [[C291]]
    ; CHECK: [[C292:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[SHL97:%[0-9]+]]:_(s32) = G_SHL [[AND101]], [[C292]](s32)
    ; CHECK: [[OR97:%[0-9]+]]:_(s32) = G_OR [[OR96]], [[SHL97]]
    ; CHECK: [[C293:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY103:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND102:%[0-9]+]]:_(s32) = G_AND [[COPY103]], [[C293]]
    ; CHECK: [[C294:%[0-9]+]]:_(s32) = G_CONSTANT i32 6
    ; CHECK: [[SHL98:%[0-9]+]]:_(s32) = G_SHL [[AND102]], [[C294]](s32)
    ; CHECK: [[OR98:%[0-9]+]]:_(s32) = G_OR [[OR97]], [[SHL98]]
    ; CHECK: [[C295:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY104:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND103:%[0-9]+]]:_(s32) = G_AND [[COPY104]], [[C295]]
    ; CHECK: [[C296:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[SHL99:%[0-9]+]]:_(s32) = G_SHL [[AND103]], [[C296]](s32)
    ; CHECK: [[OR99:%[0-9]+]]:_(s32) = G_OR [[OR98]], [[SHL99]]
    ; CHECK: [[C297:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY105:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND104:%[0-9]+]]:_(s32) = G_AND [[COPY105]], [[C297]]
    ; CHECK: [[C298:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[SHL100:%[0-9]+]]:_(s32) = G_SHL [[AND104]], [[C298]](s32)
    ; CHECK: [[OR100:%[0-9]+]]:_(s32) = G_OR [[OR99]], [[SHL100]]
    ; CHECK: [[C299:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY106:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND105:%[0-9]+]]:_(s32) = G_AND [[COPY106]], [[C299]]
    ; CHECK: [[C300:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK: [[SHL101:%[0-9]+]]:_(s32) = G_SHL [[AND105]], [[C300]](s32)
    ; CHECK: [[OR101:%[0-9]+]]:_(s32) = G_OR [[OR100]], [[SHL101]]
    ; CHECK: [[C301:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY107:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND106:%[0-9]+]]:_(s32) = G_AND [[COPY107]], [[C301]]
    ; CHECK: [[C302:%[0-9]+]]:_(s32) = G_CONSTANT i32 10
    ; CHECK: [[SHL102:%[0-9]+]]:_(s32) = G_SHL [[AND106]], [[C302]](s32)
    ; CHECK: [[OR102:%[0-9]+]]:_(s32) = G_OR [[OR101]], [[SHL102]]
    ; CHECK: [[C303:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY108:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND107:%[0-9]+]]:_(s32) = G_AND [[COPY108]], [[C303]]
    ; CHECK: [[C304:%[0-9]+]]:_(s32) = G_CONSTANT i32 11
    ; CHECK: [[SHL103:%[0-9]+]]:_(s32) = G_SHL [[AND107]], [[C304]](s32)
    ; CHECK: [[OR103:%[0-9]+]]:_(s32) = G_OR [[OR102]], [[SHL103]]
    ; CHECK: [[C305:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY109:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND108:%[0-9]+]]:_(s32) = G_AND [[COPY109]], [[C305]]
    ; CHECK: [[C306:%[0-9]+]]:_(s32) = G_CONSTANT i32 12
    ; CHECK: [[SHL104:%[0-9]+]]:_(s32) = G_SHL [[AND108]], [[C306]](s32)
    ; CHECK: [[OR104:%[0-9]+]]:_(s32) = G_OR [[OR103]], [[SHL104]]
    ; CHECK: [[C307:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY110:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND109:%[0-9]+]]:_(s32) = G_AND [[COPY110]], [[C307]]
    ; CHECK: [[C308:%[0-9]+]]:_(s32) = G_CONSTANT i32 13
    ; CHECK: [[SHL105:%[0-9]+]]:_(s32) = G_SHL [[AND109]], [[C308]](s32)
    ; CHECK: [[OR105:%[0-9]+]]:_(s32) = G_OR [[OR104]], [[SHL105]]
    ; CHECK: [[C309:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY111:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND110:%[0-9]+]]:_(s32) = G_AND [[COPY111]], [[C309]]
    ; CHECK: [[C310:%[0-9]+]]:_(s32) = G_CONSTANT i32 14
    ; CHECK: [[SHL106:%[0-9]+]]:_(s32) = G_SHL [[AND110]], [[C310]](s32)
    ; CHECK: [[OR106:%[0-9]+]]:_(s32) = G_OR [[OR105]], [[SHL106]]
    ; CHECK: [[C311:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY112:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND111:%[0-9]+]]:_(s32) = G_AND [[COPY112]], [[C311]]
    ; CHECK: [[C312:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[SHL107:%[0-9]+]]:_(s32) = G_SHL [[AND111]], [[C312]](s32)
    ; CHECK: [[OR107:%[0-9]+]]:_(s32) = G_OR [[OR106]], [[SHL107]]
    ; CHECK: [[C313:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY113:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND112:%[0-9]+]]:_(s32) = G_AND [[COPY113]], [[C313]]
    ; CHECK: [[C314:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL108:%[0-9]+]]:_(s32) = G_SHL [[AND112]], [[C314]](s32)
    ; CHECK: [[OR108:%[0-9]+]]:_(s32) = G_OR [[OR107]], [[SHL108]]
    ; CHECK: [[C315:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY114:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND113:%[0-9]+]]:_(s32) = G_AND [[COPY114]], [[C315]]
    ; CHECK: [[C316:%[0-9]+]]:_(s32) = G_CONSTANT i32 17
    ; CHECK: [[SHL109:%[0-9]+]]:_(s32) = G_SHL [[AND113]], [[C316]](s32)
    ; CHECK: [[OR109:%[0-9]+]]:_(s32) = G_OR [[OR108]], [[SHL109]]
    ; CHECK: [[C317:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY115:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND114:%[0-9]+]]:_(s32) = G_AND [[COPY115]], [[C317]]
    ; CHECK: [[C318:%[0-9]+]]:_(s32) = G_CONSTANT i32 18
    ; CHECK: [[SHL110:%[0-9]+]]:_(s32) = G_SHL [[AND114]], [[C318]](s32)
    ; CHECK: [[OR110:%[0-9]+]]:_(s32) = G_OR [[OR109]], [[SHL110]]
    ; CHECK: [[C319:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY116:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND115:%[0-9]+]]:_(s32) = G_AND [[COPY116]], [[C319]]
    ; CHECK: [[C320:%[0-9]+]]:_(s32) = G_CONSTANT i32 19
    ; CHECK: [[SHL111:%[0-9]+]]:_(s32) = G_SHL [[AND115]], [[C320]](s32)
    ; CHECK: [[OR111:%[0-9]+]]:_(s32) = G_OR [[OR110]], [[SHL111]]
    ; CHECK: [[C321:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY117:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND116:%[0-9]+]]:_(s32) = G_AND [[COPY117]], [[C321]]
    ; CHECK: [[C322:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
    ; CHECK: [[SHL112:%[0-9]+]]:_(s32) = G_SHL [[AND116]], [[C322]](s32)
    ; CHECK: [[OR112:%[0-9]+]]:_(s32) = G_OR [[OR111]], [[SHL112]]
    ; CHECK: [[C323:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY118:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND117:%[0-9]+]]:_(s32) = G_AND [[COPY118]], [[C323]]
    ; CHECK: [[C324:%[0-9]+]]:_(s32) = G_CONSTANT i32 21
    ; CHECK: [[SHL113:%[0-9]+]]:_(s32) = G_SHL [[AND117]], [[C324]](s32)
    ; CHECK: [[OR113:%[0-9]+]]:_(s32) = G_OR [[OR112]], [[SHL113]]
    ; CHECK: [[C325:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY119:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND118:%[0-9]+]]:_(s32) = G_AND [[COPY119]], [[C325]]
    ; CHECK: [[C326:%[0-9]+]]:_(s32) = G_CONSTANT i32 22
    ; CHECK: [[SHL114:%[0-9]+]]:_(s32) = G_SHL [[AND118]], [[C326]](s32)
    ; CHECK: [[OR114:%[0-9]+]]:_(s32) = G_OR [[OR113]], [[SHL114]]
    ; CHECK: [[C327:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY120:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND119:%[0-9]+]]:_(s32) = G_AND [[COPY120]], [[C327]]
    ; CHECK: [[C328:%[0-9]+]]:_(s32) = G_CONSTANT i32 23
    ; CHECK: [[SHL115:%[0-9]+]]:_(s32) = G_SHL [[AND119]], [[C328]](s32)
    ; CHECK: [[OR115:%[0-9]+]]:_(s32) = G_OR [[OR114]], [[SHL115]]
    ; CHECK: [[C329:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY121:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND120:%[0-9]+]]:_(s32) = G_AND [[COPY121]], [[C329]]
    ; CHECK: [[C330:%[0-9]+]]:_(s32) = G_CONSTANT i32 24
    ; CHECK: [[SHL116:%[0-9]+]]:_(s32) = G_SHL [[AND120]], [[C330]](s32)
    ; CHECK: [[OR116:%[0-9]+]]:_(s32) = G_OR [[OR115]], [[SHL116]]
    ; CHECK: [[C331:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY122:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND121:%[0-9]+]]:_(s32) = G_AND [[COPY122]], [[C331]]
    ; CHECK: [[C332:%[0-9]+]]:_(s32) = G_CONSTANT i32 25
    ; CHECK: [[SHL117:%[0-9]+]]:_(s32) = G_SHL [[AND121]], [[C332]](s32)
    ; CHECK: [[OR117:%[0-9]+]]:_(s32) = G_OR [[OR116]], [[SHL117]]
    ; CHECK: [[C333:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY123:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND122:%[0-9]+]]:_(s32) = G_AND [[COPY123]], [[C333]]
    ; CHECK: [[C334:%[0-9]+]]:_(s32) = G_CONSTANT i32 26
    ; CHECK: [[SHL118:%[0-9]+]]:_(s32) = G_SHL [[AND122]], [[C334]](s32)
    ; CHECK: [[OR118:%[0-9]+]]:_(s32) = G_OR [[OR117]], [[SHL118]]
    ; CHECK: [[C335:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY124:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND123:%[0-9]+]]:_(s32) = G_AND [[COPY124]], [[C335]]
    ; CHECK: [[C336:%[0-9]+]]:_(s32) = G_CONSTANT i32 27
    ; CHECK: [[SHL119:%[0-9]+]]:_(s32) = G_SHL [[AND123]], [[C336]](s32)
    ; CHECK: [[OR119:%[0-9]+]]:_(s32) = G_OR [[OR118]], [[SHL119]]
    ; CHECK: [[C337:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY125:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND124:%[0-9]+]]:_(s32) = G_AND [[COPY125]], [[C337]]
    ; CHECK: [[C338:%[0-9]+]]:_(s32) = G_CONSTANT i32 28
    ; CHECK: [[SHL120:%[0-9]+]]:_(s32) = G_SHL [[AND124]], [[C338]](s32)
    ; CHECK: [[OR120:%[0-9]+]]:_(s32) = G_OR [[OR119]], [[SHL120]]
    ; CHECK: [[C339:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY126:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND125:%[0-9]+]]:_(s32) = G_AND [[COPY126]], [[C339]]
    ; CHECK: [[C340:%[0-9]+]]:_(s32) = G_CONSTANT i32 29
    ; CHECK: [[SHL121:%[0-9]+]]:_(s32) = G_SHL [[AND125]], [[C340]](s32)
    ; CHECK: [[OR121:%[0-9]+]]:_(s32) = G_OR [[OR120]], [[SHL121]]
    ; CHECK: [[C341:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY127:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND126:%[0-9]+]]:_(s32) = G_AND [[COPY127]], [[C341]]
    ; CHECK: [[C342:%[0-9]+]]:_(s32) = G_CONSTANT i32 30
    ; CHECK: [[SHL122:%[0-9]+]]:_(s32) = G_SHL [[AND126]], [[C342]](s32)
    ; CHECK: [[OR122:%[0-9]+]]:_(s32) = G_OR [[OR121]], [[SHL122]]
    ; CHECK: [[C343:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY128:%[0-9]+]]:_(s32) = COPY [[DEF1]](s32)
    ; CHECK: [[AND127:%[0-9]+]]:_(s32) = G_AND [[COPY128]], [[C343]]
    ; CHECK: [[C344:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[SHL123:%[0-9]+]]:_(s32) = G_SHL [[AND127]], [[C344]](s32)
    ; CHECK: [[OR123:%[0-9]+]]:_(s32) = G_OR [[OR122]], [[SHL123]]
    ; CHECK: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[OR92]](s32), [[OR123]](s32)
    ; CHECK: [[FREEZE:%[0-9]+]]:_(s64) = G_FREEZE [[MV]]
    ; CHECK: [[FREEZE1:%[0-9]+]]:_(s64) = G_FREEZE [[MV1]]
    ; CHECK: [[DEF2:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: $e2 = COPY [[FREEZE]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s65) = G_ANYEXT %0
    %2:_(s65) = G_FREEZE %1
    %3:_(s64) = G_TRUNC %2
    $e2 = COPY %3
...

---
name:            test_freeze_p0
body:             |
  bb.0.entry:
    liveins: $a4
    ; CHECK-LABEL: name: test_freeze_p0
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[FREEZE:%[0-9]+]]:_(p0) = G_FREEZE [[COPY]]
    ; CHECK: $a2 = COPY [[FREEZE]](p0)
    %0:_(p0) = COPY $a4
    %1:_(p0) = G_FREEZE %0
    $a2 = COPY %1
...
