# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_ptr_to_int_s8
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_ptr_to_int_s8
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY]](p0)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[PTRTOINT]](s32)
    ; CHECK: $d2 = COPY [[COPY1]](s32)
    %0:_(p0) = COPY $a4
    %1:_(s8) = G_PTRTOINT %0(p0)
    %2:_(s32) = G_ANYEXT %1(s8)
    $d2 = COPY %2(s32)
...

---
name:            test_ptr_to_int_s32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_ptr_to_int_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY]](p0)
    ; CHECK: $d2 = COPY [[PTRTOINT]](s32)
    %0:_(p0) = COPY $a4
    %1:_(s32) = G_PTRTOINT %0(p0)
    $d2 = COPY %1(s32)
...

---
name:            test_ptr_to_int_s64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_ptr_to_int_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY]](p0)
    ; CHECK: [[ZEXT:%[0-9]+]]:_(s64) = G_ZEXT [[PTRTOINT]](s32)
    ; CHECK: $e2 = COPY [[ZEXT]](s64)
    %0:_(p0) = COPY $a4
    %1:_(s64) = G_PTRTOINT %0(p0)
    $e2 = COPY %1(s64)
...

---
name:            test_int_to_ptr
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_int_to_ptr
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[COPY]](s32)
    ; CHECK: $a2 = COPY [[INTTOPTR]](p0)
    %0:_(s32) = COPY $d4
    %1:_(p0) = G_INTTOPTR %0(s32)
    $a2 = COPY %1(p0)
...

---
name:            test_int_to_ptr_s64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_int_to_ptr_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY]](s64)
    ; CHECK: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[TRUNC]](s32)
    ; CHECK: $a2 = COPY [[INTTOPTR]](p0)
    %0:_(s64) = COPY $e4
    %1:_(p0) = G_INTTOPTR %0(s64)
    $a2 = COPY %1(p0)
...

---
name:            test_int_to_ptr_s16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_int_to_ptr_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d2
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[AND]](s32)
    ; CHECK: $a2 = COPY [[INTTOPTR]](p0)
    %0:_(s32) = COPY $d2
    %1:_(s16) = G_TRUNC %0(s32)
    %2:_(p0) = G_INTTOPTR %1(s16)
    $a2 = COPY %2(p0)
...
