# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer \
# RUN: -verify-machineinstrs %s -o - | FileCheck %s


---
name:            test_vaarg
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_vaarg
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $d4
    ; CHECK: [[LOAD:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load 4)
    ; CHECK: [[LOAD1:%[0-9]+]]:_(p0) = G_LOAD [[LOAD]](p0) :: (load 4)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[LOAD]], [[C]](s32)
    ; CHECK: G_STORE [[PTR_ADD]](p0), [[COPY]](p0) :: (store 4)
    ; CHECK: [[LOAD2:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load 4)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[LOAD2]], [[C1]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -8
    ; CHECK: [[PTRMASK:%[0-9]+]]:_(p0) = G_PTRMASK [[PTR_ADD1]], [[C2]](s32)
    ; CHECK: [[LOAD3:%[0-9]+]]:_(p0) = G_LOAD [[PTRMASK]](p0) :: (load 4, align 8)
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[PTR_ADD2:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTRMASK]], [[C3]](s32)
    ; CHECK: G_STORE [[PTR_ADD2]](p0), [[COPY]](p0) :: (store 4)
    ; CHECK: [[LOAD4:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load 4)
    ; CHECK: [[LOAD5:%[0-9]+]]:_(s32) = G_LOAD [[LOAD4]](p0) :: (load 4)
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[PTR_ADD3:%[0-9]+]]:_(p0) = G_PTR_ADD [[LOAD4]], [[C4]](s32)
    ; CHECK: G_STORE [[PTR_ADD3]](p0), [[COPY]](p0) :: (store 4)
    ; CHECK: [[LOAD6:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load 4)
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[PTR_ADD4:%[0-9]+]]:_(p0) = G_PTR_ADD [[LOAD6]], [[C5]](s32)
    ; CHECK: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 -8
    ; CHECK: [[PTRMASK1:%[0-9]+]]:_(p0) = G_PTRMASK [[PTR_ADD4]], [[C6]](s32)
    ; CHECK: [[LOAD7:%[0-9]+]]:_(s32) = G_LOAD [[PTRMASK1]](p0) :: (load 4, align 8)
    ; CHECK: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[PTR_ADD5:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTRMASK1]], [[C7]](s32)
    ; CHECK: G_STORE [[PTR_ADD5]](p0), [[COPY]](p0) :: (store 4)
    ; CHECK: [[LOAD8:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load 4)
    ; CHECK: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[PTR_ADD6:%[0-9]+]]:_(p0) = G_PTR_ADD [[LOAD8]], [[C8]](s32)
    ; CHECK: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 -8
    ; CHECK: [[PTRMASK2:%[0-9]+]]:_(p0) = G_PTRMASK [[PTR_ADD6]], [[C9]](s32)
    ; CHECK: [[LOAD9:%[0-9]+]]:_(s64) = G_LOAD [[PTRMASK2]](p0) :: (load 8)
    ; CHECK: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[PTR_ADD7:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTRMASK2]], [[C10]](s32)
    ; CHECK: G_STORE [[PTR_ADD7]](p0), [[COPY]](p0) :: (store 4)
    ; CHECK: [[LOAD10:%[0-9]+]]:_(p0) = G_LOAD [[COPY]](p0) :: (load 4)
    ; CHECK: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[PTR_ADD8:%[0-9]+]]:_(p0) = G_PTR_ADD [[LOAD10]], [[C11]](s32)
    ; CHECK: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK: [[PTRMASK3:%[0-9]+]]:_(p0) = G_PTRMASK [[PTR_ADD8]], [[C12]](s32)
    ; CHECK: [[LOAD11:%[0-9]+]]:_(s64) = G_LOAD [[PTRMASK3]](p0) :: (load 8, align 16)
    ; CHECK: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[PTR_ADD9:%[0-9]+]]:_(p0) = G_PTR_ADD [[PTRMASK3]], [[C13]](s32)
    ; CHECK: G_STORE [[PTR_ADD9]](p0), [[COPY]](p0) :: (store 4)
    ; CHECK: $d2 = COPY [[LOAD1]](p0)
    ; CHECK: $d2 = COPY [[LOAD3]](p0)
    ; CHECK: $d2 = COPY [[LOAD5]](s32)
    ; CHECK: $d2 = COPY [[LOAD7]](s32)
    ; CHECK: $e2 = COPY [[LOAD9]](s64)
    ; CHECK: $e2 = COPY [[LOAD11]](s64)
    %0:_(p0) = COPY $d4
    %1:_(p0) = G_VAARG %0(p0), 4
    %2:_(p0) = G_VAARG %0(p0), 8
    %3:_(s32) = G_VAARG %0(p0), 4
    %4:_(s32) = G_VAARG %0(p0), 8
    %5:_(s64) = G_VAARG %0(p0), 8
    %6:_(s64) = G_VAARG %0(p0), 16
    $d2 = COPY %1(p0)
    $d2 = COPY %2(p0)
    $d2 = COPY %3(s32)
    $d2 = COPY %4(s32)
    $e2 = COPY %5(s64)
    $e2 = COPY %6(s64)
...
