# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
---
name:            test_udiv_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_udiv_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[UDIV:%[0-9]+]]:_(s32) = G_UDIV [[COPY]], [[COPY1]]
    ; CHECK: $d2 = COPY [[UDIV]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s32) = G_UDIV %0, %1
    $d2 = COPY %2(s32)
...
---
name:            test_udiv_small_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_udiv_small_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY3]], [[C1]]
    ; CHECK: [[UDIV:%[0-9]+]]:_(s32) = G_UDIV [[AND]], [[AND1]]
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[UDIV]](s32)
    ; CHECK: $d2 = COPY [[COPY4]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s8) = G_TRUNC %0:_(s32)
    %3:_(s8) = G_TRUNC %1:_(s32)
    %4:_(s8) = G_UDIV %2, %3
    %5:_(s32) = G_ANYEXT %4:_(s8)
    $d2 = COPY %5(s32)
...
---
name:            test_udiv_big_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_udiv_big_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e4 = COPY [[COPY]](s64)
    ; CHECK: $e6 = COPY [[COPY1]](s64)
    ; CHECK: CALL &__udivdi3, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit $e6, implicit-def $e2
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY $e2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e2 = COPY [[COPY2]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = COPY $e6
    %2:_(s64) = G_UDIV %0, %1
    $e2 = COPY %2(s64)
...
---
name:            test_udiv_nonpow2_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_udiv_nonpow2_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 281474976710655
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY2]](s64)
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C]](s64)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[UV]], [[UV2]]
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV1]], [[UV3]]
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[AND]](s32), [[AND1]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 281474976710655
    ; CHECK: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; CHECK: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY3]](s64)
    ; CHECK: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C1]](s64)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[UV4]], [[UV6]]
    ; CHECK: [[AND3:%[0-9]+]]:_(s32) = G_AND [[UV5]], [[UV7]]
    ; CHECK: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[AND2]](s32), [[AND3]](s32)
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e4 = COPY [[MV]](s64)
    ; CHECK: $e6 = COPY [[MV1]](s64)
    ; CHECK: CALL &__udivdi3, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit $e6, implicit-def $e2
    ; CHECK: [[COPY4:%[0-9]+]]:_(s64) = COPY $e2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY4]](s64)
    ; CHECK: $e2 = COPY [[COPY5]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = COPY $e6
    %2:_(s48) = G_TRUNC %0:_(s64)
    %3:_(s48) = G_TRUNC %1:_(s64)
    %4:_(s48) = G_UDIV %2, %3
    %5:_(s64) = G_ANYEXT %4:_(s48)
    $e2 = COPY %5(s64)
...
