# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer \
# RUN:   -verify-machineinstrs %s -o - | FileCheck -check-prefixes=TC18OPS %s
# RUN: llc -O0 -mtriple=tricore -mattr=-tc18 -global-isel -run-pass=legalizer \
# RUN:   -verify-machineinstrs %s -o - | FileCheck -check-prefixes=NOTC18OPS %s

---
name:            fptoui_s32_s32
body:             |
  bb.0:
    liveins: $d4

    ; TC18OPS-LABEL: name: fptoui_s32_s32
    ; TC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC18OPS: [[FPTOUI:%[0-9]+]]:_(s32) = G_FPTOUI [[COPY]](s32)
    ; TC18OPS: $d4 = COPY [[FPTOUI]](s32)
    ; NOTC18OPS-LABEL: name: fptoui_s32_s32
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC18OPS: [[FPTOUI:%[0-9]+]]:_(s32) = G_FPTOUI [[COPY]](s32)
    ; NOTC18OPS: $d4 = COPY [[FPTOUI]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = G_FPTOUI %0(s32)
    $d4 = COPY %1(s32)
...

---
name:            fptoui_s32_s64
body:             |
  bb.0:
    liveins: $e4

    ; TC18OPS-LABEL: name: fptoui_s32_s64
    ; TC18OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC18OPS: [[FPTOUI:%[0-9]+]]:_(s32) = G_FPTOUI [[COPY]](s64)
    ; TC18OPS: $d4 = COPY [[FPTOUI]](s32)
    ; NOTC18OPS-LABEL: name: fptoui_s32_s64
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; NOTC18OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $e4 = COPY [[COPY]](s64)
    ; NOTC18OPS: CALL &__fixunsdfsi, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $d2
    ; NOTC18OPS: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; NOTC18OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $d4 = COPY [[COPY1]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s32) = G_FPTOUI %0(s64)
    $d4 = COPY %1(s32)
...

---
name:            fptoui_s64_s64
body:             |
  bb.0:
    liveins: $e4

    ; TC18OPS-LABEL: name: fptoui_s64_s64
    ; TC18OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC18OPS: [[FPTOUI:%[0-9]+]]:_(s64) = G_FPTOUI [[COPY]](s64)
    ; TC18OPS: $e4 = COPY [[FPTOUI]](s64)
    ; NOTC18OPS-LABEL: name: fptoui_s64_s64
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; NOTC18OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $e4 = COPY [[COPY]](s64)
    ; NOTC18OPS: CALL &__fixunsdfdi, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $e2
    ; NOTC18OPS: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; NOTC18OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $e4 = COPY [[COPY1]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = G_FPTOUI %0(s64)
    $e4 = COPY %1(s64)
...

---
name:            fptoui_smaller_than_s32
body:             |
  bb.0:
    liveins: $d4

    ; TC18OPS-LABEL: name: fptoui_smaller_than_s32
    ; TC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC18OPS: [[FPTOUI:%[0-9]+]]:_(s32) = G_FPTOUI [[COPY]](s32)
    ; TC18OPS: [[COPY1:%[0-9]+]]:_(s32) = COPY [[FPTOUI]](s32)
    ; TC18OPS: $d4 = COPY [[COPY1]](s32)
    ; NOTC18OPS-LABEL: name: fptoui_smaller_than_s32
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC18OPS: [[FPTOUI:%[0-9]+]]:_(s32) = G_FPTOUI [[COPY]](s32)
    ; NOTC18OPS: [[COPY1:%[0-9]+]]:_(s32) = COPY [[FPTOUI]](s32)
    ; NOTC18OPS: $d4 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_FPTOUI %0
    %2:_(s32) = G_ANYEXT %1
    $d4 = COPY %2
...

---
name:            fptoui_between_s32_and_s64
body:             |
  bb.0:
    liveins: $e4

    ; TC18OPS-LABEL: name: fptoui_between_s32_and_s64
    ; TC18OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC18OPS: [[FPTOUI:%[0-9]+]]:_(s64) = G_FPTOUI [[COPY]](s64)
    ; TC18OPS: [[COPY1:%[0-9]+]]:_(s64) = COPY [[FPTOUI]](s64)
    ; TC18OPS: $e4 = COPY [[COPY1]](s64)
    ; NOTC18OPS-LABEL: name: fptoui_between_s32_and_s64
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; NOTC18OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $e4 = COPY [[COPY]](s64)
    ; NOTC18OPS: CALL &__fixunsdfdi, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $e2
    ; NOTC18OPS: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; NOTC18OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; NOTC18OPS: $e4 = COPY [[COPY2]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s48) = G_FPTOUI %0
    %2:_(s64) = G_ANYEXT %1
    $e4 = COPY %2
...

---
name:            fptoui_s64_s32
body:             |
  bb.0:
    liveins: $d4

    ; TC18OPS-LABEL: name: fptoui_s64_s32
    ; TC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC18OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; TC18OPS: $d4 = COPY [[COPY]](s32)
    ; TC18OPS: CALL &__fixunssfdi, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $e2
    ; TC18OPS: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; TC18OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; TC18OPS: $e4 = COPY [[COPY1]](s64)
    ; NOTC18OPS-LABEL: name: fptoui_s64_s32
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC18OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $d4 = COPY [[COPY]](s32)
    ; NOTC18OPS: CALL &__fixunssfdi, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $e2
    ; NOTC18OPS: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; NOTC18OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $e4 = COPY [[COPY1]](s64)
    %0:_(s32) = COPY $d4
    %1:_(s64) = G_FPTOUI %0
    $e4 = COPY %1
...
