# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -mtriple=tricore -mattr=-tc18 -mattr=-tc162 -run-pass=legalizer -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefixes=NOTC162OPS %s
# RUN: llc -mtriple=tricore -mattr=-tc18 -run-pass=legalizer -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefixes=NOTC18OPS %s

---
name: test_fptrunc_f32_to_f16
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fptrunc_f32_to_f16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[FPTRUNC:%[0-9]+]]:_(s16) = G_FPTRUNC [[COPY]](s32)
    ; CHECK: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[FPTRUNC]](s16)
    ; CHECK: $d2 = COPY [[ANYEXT]](s32)
    ; NOTC162OPS-LABEL: name: test_fptrunc_f32_to_f16
    ; NOTC162OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC162OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: $d4 = COPY [[COPY]](s32)
    ; NOTC162OPS: CALL &__gnu_f2h_ieee, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $d2
    ; NOTC162OPS: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; NOTC162OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; NOTC162OPS: $d2 = COPY [[COPY2]](s32)
    ; NOTC18OPS-LABEL: name: test_fptrunc_f32_to_f16
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; NOTC18OPS: [[FPTRUNC:%[0-9]+]]:_(s16) = G_FPTRUNC [[COPY]](s32)
    ; NOTC18OPS: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[FPTRUNC]](s16)
    ; NOTC18OPS: $d2 = COPY [[ANYEXT]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_FPTRUNC %0
    %2:_(s32) = G_ANYEXT %1
    $d2 = COPY %2
...

---
name: test_fptrunc_f64_to_f32
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fptrunc_f64_to_f32
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[FPTRUNC:%[0-9]+]]:_(s32) = G_FPTRUNC [[COPY]](s64)
    ; CHECK: $d2 = COPY [[FPTRUNC]](s32)
    ; NOTC162OPS-LABEL: name: test_fptrunc_f64_to_f32
    ; NOTC162OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; NOTC162OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: $e4 = COPY [[COPY]](s64)
    ; NOTC162OPS: CALL &__truncdfsf2, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $d2
    ; NOTC162OPS: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; NOTC162OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC162OPS: $d2 = COPY [[COPY1]](s32)
    ; NOTC18OPS-LABEL: name: test_fptrunc_f64_to_f32
    ; NOTC18OPS: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; NOTC18OPS: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $e4 = COPY [[COPY]](s64)
    ; NOTC18OPS: CALL &__truncdfsf2, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $d2
    ; NOTC18OPS: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; NOTC18OPS: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; NOTC18OPS: $d2 = COPY [[COPY1]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s32) = G_FPTRUNC %0
    $d2 = COPY %1
...
