# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name:            frint_s16
body:             |
  bb.0:
    liveins: $d4

    ; CHECK-LABEL: name: frint_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[FPTRUNC:%[0-9]+]]:_(s16) = G_FPTRUNC [[COPY]](s32)
    ; CHECK: [[FPEXT:%[0-9]+]]:_(s32) = G_FPEXT [[FPTRUNC]](s16)
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $d4 = COPY [[FPEXT]](s32)
    ; CHECK: CALL &rintf, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $d2
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: [[FPTRUNC1:%[0-9]+]]:_(s16) = G_FPTRUNC [[COPY1]](s32)
    ; CHECK: [[FPEXT1:%[0-9]+]]:_(s32) = G_FPEXT [[FPTRUNC1]](s16)
    ; CHECK: $d4 = COPY [[FPEXT1]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_FPTRUNC %0:_(s32)
    %2:_(s16) = G_FRINT %1(s16)
    %3:_(s32) = G_FPEXT %2:_(s16)
    $d4 = COPY %3(s32)
...

---
name:            frint_s32
body:             |
  bb.0:
    liveins: $d4


    ; CHECK-LABEL: name: frint_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $d4 = COPY [[COPY]](s32)
    ; CHECK: CALL &rintf, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $d2
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $d4 = COPY [[COPY1]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = G_FRINT %0(s32)
    $d4 = COPY %1(s32)
...

---
name:            frint_s64
body:             |
  bb.0:
    liveins: $e4


    ; CHECK-LABEL: name: frint_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e4 = COPY [[COPY]](s64)
    ; CHECK: CALL &rint, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $e2
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e4 = COPY [[COPY1]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = G_FRINT %0(s64)
    $e4 = COPY %1(s64)
...
