# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

# This is a reduced test case from SuperTest 3/3/2/3/t15_20acase3.c, which
# was failing due to an s96 G_MERGE_VALUES.

--- |
  source_filename = "t15_20acase3.i"
  target datalayout = "e-m:e-i64:32-p:32:32-f64:32-n32-a:0:32-S64"
  target triple = "tricore"

  %struct.a = type { i72, i32 }

  define dso_local void @supertest_t15_20acase3(%struct.a* noalias sret align 4 %agg.result) {
  entry:
    %result.ptr = alloca i8*, align 4
    %e = alloca %struct.a, align 4
    %0 = bitcast %struct.a* %agg.result to i8*
    store i8* %0, i8** %result.ptr, align 4
    %1 = bitcast %struct.a* %e to i96*
    %bf.load = load i96, i96* %1, align 4
    %bf.shl = shl i96 %bf.load, 31
    %bf.ashr = ashr i96 %bf.shl, 83
    %bf.cast = trunc i96 %bf.ashr to i32
    %call = call i32 bitcast (i32 (...)* @f to i32 (i32)*)(i32 %bf.cast)
    ret void
  }

  declare dso_local i32 @f(...)

...

---
name:            supertest_t15_20acase3
tracksRegLiveness: true
stack:
  - { id: 0, name: result.ptr, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: e, type: default, offset: 0, size: 16, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.1.entry:
    liveins: $a4

    ; CHECK-LABEL: name: supertest_t15_20acase3
    ; CHECK: liveins: $a4
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 31
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C]](s64)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[UV]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C]](s64)
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[UV3]](s32)
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[COPY3]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s64) = G_CONSTANT i64 83
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[DEF1:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C2]](s64)
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY [[UV4]](s32)
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[COPY5]](s32)
    ; CHECK: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C2]](s64)
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[UV7]](s32)
    ; CHECK: [[COPY8:%[0-9]+]]:_(s32) = COPY [[COPY7]](s32)
    ; CHECK: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.result.ptr
    ; CHECK: [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.e
    ; CHECK: G_STORE [[COPY]](p0), [[FRAME_INDEX]](p0) :: (store 4 into %ir.result.ptr)
    ; CHECK: [[LOAD:%[0-9]+]]:_(s64) = G_LOAD [[FRAME_INDEX1]](p0) :: (dereferenceable load 8 from %ir.1, align 4)
    ; CHECK: [[C4:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[FRAME_INDEX1]], [[C5]](s32)
    ; CHECK: [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[PTR_ADD]](p0) :: (dereferenceable load 4 from %ir.1 + 8)
    ; CHECK: [[DEF2:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[DEF3:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[C6:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 64
    ; CHECK: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 64
    ; CHECK: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C7]], [[C8]]
    ; CHECK: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[C8]], [[C7]]
    ; CHECK: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[C7]](s32), [[C8]]
    ; CHECK: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C7]](s32), [[C9]]
    ; CHECK: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB2:%[0-9]+]]:_(s32) = G_SUB [[C7]], [[C10]]
    ; CHECK: [[SUB3:%[0-9]+]]:_(s32) = G_SUB [[C10]], [[C7]]
    ; CHECK: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[C7]](s32), [[C10]]
    ; CHECK: [[ICMP3:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C7]](s32), [[C11]]
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[C7]](s32)
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[LOAD1]], [[SUB3]](s32)
    ; CHECK: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[DEF2]], [[C7]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[LSHR]], [[SHL1]]
    ; CHECK: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[SUB2]](s32)
    ; CHECK: [[COPY9:%[0-9]+]]:_(s32) = COPY [[ICMP2]](s32)
    ; CHECK: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[COPY9]](s32), [[SHL]], [[C12]]
    ; CHECK: [[COPY10:%[0-9]+]]:_(s32) = COPY [[ICMP2]](s32)
    ; CHECK: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[COPY10]](s32), [[OR]], [[SHL2]]
    ; CHECK: [[COPY11:%[0-9]+]]:_(s32) = COPY [[ICMP3]](s32)
    ; CHECK: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[COPY11]](s32), [[DEF2]], [[SELECT1]]
    ; CHECK: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB4:%[0-9]+]]:_(s32) = G_SUB [[SUB1]], [[C13]]
    ; CHECK: [[SUB5:%[0-9]+]]:_(s32) = G_SUB [[C13]], [[SUB1]]
    ; CHECK: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP4:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB1]](s32), [[C13]]
    ; CHECK: [[ICMP5:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB1]](s32), [[C14]]
    ; CHECK: [[LSHR1:%[0-9]+]]:_(s32) = G_LSHR [[DEF2]], [[SUB1]](s32)
    ; CHECK: [[LSHR2:%[0-9]+]]:_(s32) = G_LSHR [[LOAD1]], [[SUB1]](s32)
    ; CHECK: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[DEF2]], [[SUB5]](s32)
    ; CHECK: [[OR1:%[0-9]+]]:_(s32) = G_OR [[LSHR2]], [[SHL3]]
    ; CHECK: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[LSHR3:%[0-9]+]]:_(s32) = G_LSHR [[DEF2]], [[SUB4]](s32)
    ; CHECK: [[COPY12:%[0-9]+]]:_(s32) = COPY [[ICMP4]](s32)
    ; CHECK: [[SELECT3:%[0-9]+]]:_(s32) = G_SELECT [[COPY12]](s32), [[OR1]], [[LSHR3]]
    ; CHECK: [[COPY13:%[0-9]+]]:_(s32) = COPY [[ICMP5]](s32)
    ; CHECK: [[SELECT4:%[0-9]+]]:_(s32) = G_SELECT [[COPY13]](s32), [[LOAD1]], [[SELECT3]]
    ; CHECK: [[COPY14:%[0-9]+]]:_(s32) = COPY [[ICMP4]](s32)
    ; CHECK: [[SELECT5:%[0-9]+]]:_(s32) = G_SELECT [[COPY14]](s32), [[LSHR1]], [[C15]]
    ; CHECK: [[C16:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF3]](s64)
    ; CHECK: [[SUB6:%[0-9]+]]:_(s32) = G_SUB [[C7]], [[C16]]
    ; CHECK: [[SUB7:%[0-9]+]]:_(s32) = G_SUB [[C16]], [[C7]]
    ; CHECK: [[C17:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP6:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[C7]](s32), [[C16]]
    ; CHECK: [[ICMP7:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[C7]](s32), [[C17]]
    ; CHECK: [[SHL4:%[0-9]+]]:_(s32) = G_SHL [[UV8]], [[C7]](s32)
    ; CHECK: [[LSHR4:%[0-9]+]]:_(s32) = G_LSHR [[UV8]], [[SUB7]](s32)
    ; CHECK: [[SHL5:%[0-9]+]]:_(s32) = G_SHL [[UV9]], [[C7]](s32)
    ; CHECK: [[OR2:%[0-9]+]]:_(s32) = G_OR [[LSHR4]], [[SHL5]]
    ; CHECK: [[C18:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL6:%[0-9]+]]:_(s32) = G_SHL [[UV8]], [[SUB6]](s32)
    ; CHECK: [[COPY15:%[0-9]+]]:_(s32) = COPY [[ICMP6]](s32)
    ; CHECK: [[SELECT6:%[0-9]+]]:_(s32) = G_SELECT [[COPY15]](s32), [[SHL4]], [[C18]]
    ; CHECK: [[COPY16:%[0-9]+]]:_(s32) = COPY [[ICMP6]](s32)
    ; CHECK: [[SELECT7:%[0-9]+]]:_(s32) = G_SELECT [[COPY16]](s32), [[OR2]], [[SHL6]]
    ; CHECK: [[COPY17:%[0-9]+]]:_(s32) = COPY [[ICMP7]](s32)
    ; CHECK: [[SELECT8:%[0-9]+]]:_(s32) = G_SELECT [[COPY17]](s32), [[UV9]], [[SELECT7]]
    ; CHECK: [[OR3:%[0-9]+]]:_(s32) = G_OR [[SELECT4]], [[SELECT6]]
    ; CHECK: [[C19:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C20:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB8:%[0-9]+]]:_(s32) = G_SUB [[SUB]], [[C20]]
    ; CHECK: [[SUB9:%[0-9]+]]:_(s32) = G_SUB [[C20]], [[SUB]]
    ; CHECK: [[C21:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP8:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB]](s32), [[C20]]
    ; CHECK: [[ICMP9:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB]](s32), [[C21]]
    ; CHECK: [[SHL7:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[SUB]](s32)
    ; CHECK: [[LSHR5:%[0-9]+]]:_(s32) = G_LSHR [[LOAD1]], [[SUB9]](s32)
    ; CHECK: [[SHL8:%[0-9]+]]:_(s32) = G_SHL [[DEF2]], [[SUB]](s32)
    ; CHECK: [[OR4:%[0-9]+]]:_(s32) = G_OR [[LSHR5]], [[SHL8]]
    ; CHECK: [[C22:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL9:%[0-9]+]]:_(s32) = G_SHL [[LOAD1]], [[SUB8]](s32)
    ; CHECK: [[COPY18:%[0-9]+]]:_(s32) = COPY [[ICMP8]](s32)
    ; CHECK: [[SELECT9:%[0-9]+]]:_(s32) = G_SELECT [[COPY18]](s32), [[SHL7]], [[C22]]
    ; CHECK: [[COPY19:%[0-9]+]]:_(s32) = COPY [[ICMP8]](s32)
    ; CHECK: [[SELECT10:%[0-9]+]]:_(s32) = G_SELECT [[COPY19]](s32), [[OR4]], [[SHL9]]
    ; CHECK: [[COPY20:%[0-9]+]]:_(s32) = COPY [[ICMP9]](s32)
    ; CHECK: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C19]](s64)
    ; CHECK: [[COPY21:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT11:%[0-9]+]]:_(s32) = G_SELECT [[COPY21]](s32), [[SELECT]], [[UV10]]
    ; CHECK: [[COPY22:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT12:%[0-9]+]]:_(s32) = G_SELECT [[COPY22]](s32), [[SELECT2]], [[UV11]]
    ; CHECK: [[COPY23:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT13:%[0-9]+]]:_(s32) = G_SELECT [[COPY23]](s32), [[OR3]], [[SELECT9]]
    ; CHECK: [[COPY24:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[DEF3]](s64)
    ; CHECK: [[COPY25:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[SELECT14:%[0-9]+]]:_(s32) = G_SELECT [[COPY25]](s32), [[UV12]], [[SELECT13]]
    ; CHECK: [[COPY26:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[UV14:%[0-9]+]]:_(s32), [[UV15:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[LOAD]](s64)
    ; CHECK: [[UV16:%[0-9]+]]:_(s32), [[UV17:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C4]](s64)
    ; CHECK: [[OR5:%[0-9]+]]:_(s32) = G_OR [[SELECT11]], [[UV14]]
    ; CHECK: [[OR6:%[0-9]+]]:_(s32) = G_OR [[SELECT12]], [[UV15]]
    ; CHECK: [[OR7:%[0-9]+]]:_(s32) = G_OR [[SELECT14]], [[UV16]]
    ; CHECK: [[C23:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK: [[DEF4:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[DEF5:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[SUB10:%[0-9]+]]:_(s32) = G_SUB [[COPY2]], [[C23]]
    ; CHECK: [[SUB11:%[0-9]+]]:_(s32) = G_SUB [[C23]], [[COPY2]]
    ; CHECK: [[C24:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP10:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C23]]
    ; CHECK: [[ICMP11:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C24]]
    ; CHECK: [[C25:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB12:%[0-9]+]]:_(s32) = G_SUB [[COPY2]], [[C25]]
    ; CHECK: [[SUB13:%[0-9]+]]:_(s32) = G_SUB [[C25]], [[COPY2]]
    ; CHECK: [[C26:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP12:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C25]]
    ; CHECK: [[ICMP13:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C26]]
    ; CHECK: [[SHL10:%[0-9]+]]:_(s32) = G_SHL [[OR5]], [[COPY2]](s32)
    ; CHECK: [[LSHR6:%[0-9]+]]:_(s32) = G_LSHR [[OR5]], [[SUB13]](s32)
    ; CHECK: [[SHL11:%[0-9]+]]:_(s32) = G_SHL [[OR6]], [[COPY2]](s32)
    ; CHECK: [[OR8:%[0-9]+]]:_(s32) = G_OR [[LSHR6]], [[SHL11]]
    ; CHECK: [[C27:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL12:%[0-9]+]]:_(s32) = G_SHL [[OR5]], [[SUB12]](s32)
    ; CHECK: [[COPY27:%[0-9]+]]:_(s32) = COPY [[ICMP12]](s32)
    ; CHECK: [[SELECT15:%[0-9]+]]:_(s32) = G_SELECT [[COPY27]](s32), [[SHL10]], [[C27]]
    ; CHECK: [[COPY28:%[0-9]+]]:_(s32) = COPY [[ICMP12]](s32)
    ; CHECK: [[SELECT16:%[0-9]+]]:_(s32) = G_SELECT [[COPY28]](s32), [[OR8]], [[SHL12]]
    ; CHECK: [[COPY29:%[0-9]+]]:_(s32) = COPY [[ICMP13]](s32)
    ; CHECK: [[SELECT17:%[0-9]+]]:_(s32) = G_SELECT [[COPY29]](s32), [[OR6]], [[SELECT16]]
    ; CHECK: [[C28:%[0-9]+]]:_(s64) = G_CONSTANT i64 281474976710655
    ; CHECK: [[UV18:%[0-9]+]]:_(s32), [[UV19:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C28]](s64)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[OR5]], [[UV18]]
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[OR6]], [[UV19]]
    ; CHECK: [[C29:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB14:%[0-9]+]]:_(s32) = G_SUB [[SUB11]], [[C29]]
    ; CHECK: [[SUB15:%[0-9]+]]:_(s32) = G_SUB [[C29]], [[SUB11]]
    ; CHECK: [[C30:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP14:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB11]](s32), [[C29]]
    ; CHECK: [[ICMP15:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB11]](s32), [[C30]]
    ; CHECK: [[LSHR7:%[0-9]+]]:_(s32) = G_LSHR [[AND1]], [[SUB11]](s32)
    ; CHECK: [[LSHR8:%[0-9]+]]:_(s32) = G_LSHR [[AND]], [[SUB11]](s32)
    ; CHECK: [[SHL13:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[SUB15]](s32)
    ; CHECK: [[OR9:%[0-9]+]]:_(s32) = G_OR [[LSHR8]], [[SHL13]]
    ; CHECK: [[C31:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[LSHR9:%[0-9]+]]:_(s32) = G_LSHR [[AND1]], [[SUB14]](s32)
    ; CHECK: [[COPY30:%[0-9]+]]:_(s32) = COPY [[ICMP14]](s32)
    ; CHECK: [[SELECT18:%[0-9]+]]:_(s32) = G_SELECT [[COPY30]](s32), [[OR9]], [[LSHR9]]
    ; CHECK: [[COPY31:%[0-9]+]]:_(s32) = COPY [[ICMP15]](s32)
    ; CHECK: [[SELECT19:%[0-9]+]]:_(s32) = G_SELECT [[COPY31]](s32), [[AND]], [[SELECT18]]
    ; CHECK: [[COPY32:%[0-9]+]]:_(s32) = COPY [[ICMP14]](s32)
    ; CHECK: [[SELECT20:%[0-9]+]]:_(s32) = G_SELECT [[COPY32]](s32), [[LSHR7]], [[C31]]
    ; CHECK: [[C32:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB16:%[0-9]+]]:_(s32) = G_SUB [[COPY2]], [[C32]]
    ; CHECK: [[SUB17:%[0-9]+]]:_(s32) = G_SUB [[C32]], [[COPY2]]
    ; CHECK: [[C33:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP16:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C32]]
    ; CHECK: [[ICMP17:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C33]]
    ; CHECK: [[SHL14:%[0-9]+]]:_(s32) = G_SHL [[OR7]], [[COPY2]](s32)
    ; CHECK: [[LSHR10:%[0-9]+]]:_(s32) = G_LSHR [[OR7]], [[SUB17]](s32)
    ; CHECK: [[SHL15:%[0-9]+]]:_(s32) = G_SHL [[DEF4]], [[COPY2]](s32)
    ; CHECK: [[OR10:%[0-9]+]]:_(s32) = G_OR [[LSHR10]], [[SHL15]]
    ; CHECK: [[C34:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL16:%[0-9]+]]:_(s32) = G_SHL [[OR7]], [[SUB16]](s32)
    ; CHECK: [[COPY33:%[0-9]+]]:_(s32) = COPY [[ICMP16]](s32)
    ; CHECK: [[SELECT21:%[0-9]+]]:_(s32) = G_SELECT [[COPY33]](s32), [[SHL14]], [[C34]]
    ; CHECK: [[COPY34:%[0-9]+]]:_(s32) = COPY [[ICMP16]](s32)
    ; CHECK: [[SELECT22:%[0-9]+]]:_(s32) = G_SELECT [[COPY34]](s32), [[OR10]], [[SHL16]]
    ; CHECK: [[COPY35:%[0-9]+]]:_(s32) = COPY [[ICMP17]](s32)
    ; CHECK: [[SELECT23:%[0-9]+]]:_(s32) = G_SELECT [[COPY35]](s32), [[DEF4]], [[SELECT22]]
    ; CHECK: [[COPY36:%[0-9]+]]:_(s32) = COPY [[SELECT19]](s32)
    ; CHECK: [[COPY37:%[0-9]+]]:_(s32) = COPY [[SELECT21]](s32)
    ; CHECK: [[OR11:%[0-9]+]]:_(s32) = G_OR [[COPY36]], [[COPY37]]
    ; CHECK: [[COPY38:%[0-9]+]]:_(s32) = COPY [[SELECT20]](s32)
    ; CHECK: [[COPY39:%[0-9]+]]:_(s32) = COPY [[SELECT23]](s32)
    ; CHECK: [[OR12:%[0-9]+]]:_(s32) = G_OR [[COPY38]], [[COPY39]]
    ; CHECK: [[DEF6:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY40:%[0-9]+]]:_(s64) = COPY [[DEF6]](s64)
    ; CHECK: [[UV20:%[0-9]+]]:_(s32), [[UV21:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY40]](s64)
    ; CHECK: [[C35:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY41:%[0-9]+]]:_(s32) = COPY [[OR12]](s32)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[COPY41]], [[C35]]
    ; CHECK: [[C36:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND3:%[0-9]+]]:_(s32) = G_AND [[UV21]], [[C36]]
    ; CHECK: [[OR13:%[0-9]+]]:_(s32) = G_OR [[AND3]], [[AND2]]
    ; CHECK: [[COPY42:%[0-9]+]]:_(s32) = COPY [[OR13]](s32)
    ; CHECK: [[C37:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[C38:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB18:%[0-9]+]]:_(s32) = G_SUB [[SUB10]], [[C38]]
    ; CHECK: [[SUB19:%[0-9]+]]:_(s32) = G_SUB [[C38]], [[SUB10]]
    ; CHECK: [[C39:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP18:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB10]](s32), [[C38]]
    ; CHECK: [[ICMP19:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB10]](s32), [[C39]]
    ; CHECK: [[SHL17:%[0-9]+]]:_(s32) = G_SHL [[OR5]], [[SUB10]](s32)
    ; CHECK: [[LSHR11:%[0-9]+]]:_(s32) = G_LSHR [[OR5]], [[SUB19]](s32)
    ; CHECK: [[SHL18:%[0-9]+]]:_(s32) = G_SHL [[OR6]], [[SUB10]](s32)
    ; CHECK: [[OR14:%[0-9]+]]:_(s32) = G_OR [[LSHR11]], [[SHL18]]
    ; CHECK: [[C40:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL19:%[0-9]+]]:_(s32) = G_SHL [[OR5]], [[SUB18]](s32)
    ; CHECK: [[COPY43:%[0-9]+]]:_(s32) = COPY [[ICMP18]](s32)
    ; CHECK: [[SELECT24:%[0-9]+]]:_(s32) = G_SELECT [[COPY43]](s32), [[SHL17]], [[C40]]
    ; CHECK: [[COPY44:%[0-9]+]]:_(s32) = COPY [[ICMP18]](s32)
    ; CHECK: [[SELECT25:%[0-9]+]]:_(s32) = G_SELECT [[COPY44]](s32), [[OR14]], [[SHL19]]
    ; CHECK: [[COPY45:%[0-9]+]]:_(s32) = COPY [[ICMP19]](s32)
    ; CHECK: [[SELECT26:%[0-9]+]]:_(s32) = G_SELECT [[COPY45]](s32), [[OR6]], [[SELECT25]]
    ; CHECK: [[COPY46:%[0-9]+]]:_(s32) = COPY [[SELECT15]](s32)
    ; CHECK: [[COPY47:%[0-9]+]]:_(s64) = COPY [[C37]](s64)
    ; CHECK: [[UV22:%[0-9]+]]:_(s32), [[UV23:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY47]](s64)
    ; CHECK: [[COPY48:%[0-9]+]]:_(s32) = COPY [[UV22]](s32)
    ; CHECK: [[COPY49:%[0-9]+]]:_(s64) = COPY [[C37]](s64)
    ; CHECK: [[UV24:%[0-9]+]]:_(s32), [[UV25:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY49]](s64)
    ; CHECK: [[COPY50:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT27:%[0-9]+]]:_(s32) = G_SELECT [[COPY50]](s32), [[COPY46]], [[COPY48]]
    ; CHECK: [[COPY51:%[0-9]+]]:_(s32) = COPY [[SELECT17]](s32)
    ; CHECK: [[COPY52:%[0-9]+]]:_(s32) = COPY [[UV25]](s32)
    ; CHECK: [[COPY53:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT28:%[0-9]+]]:_(s32) = G_SELECT [[COPY53]](s32), [[COPY51]], [[COPY52]]
    ; CHECK: [[DEF7:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY54:%[0-9]+]]:_(s64) = COPY [[DEF7]](s64)
    ; CHECK: [[UV26:%[0-9]+]]:_(s32), [[UV27:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY54]](s64)
    ; CHECK: [[C41:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY55:%[0-9]+]]:_(s32) = COPY [[SELECT28]](s32)
    ; CHECK: [[AND4:%[0-9]+]]:_(s32) = G_AND [[COPY55]], [[C41]]
    ; CHECK: [[C42:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND5:%[0-9]+]]:_(s32) = G_AND [[UV27]], [[C42]]
    ; CHECK: [[OR15:%[0-9]+]]:_(s32) = G_OR [[AND5]], [[AND4]]
    ; CHECK: [[COPY56:%[0-9]+]]:_(s32) = COPY [[OR15]](s32)
    ; CHECK: [[COPY57:%[0-9]+]]:_(s32) = COPY [[OR11]](s32)
    ; CHECK: [[COPY58:%[0-9]+]]:_(s32) = COPY [[SELECT24]](s32)
    ; CHECK: [[COPY59:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT29:%[0-9]+]]:_(s32) = G_SELECT [[COPY59]](s32), [[COPY57]], [[COPY58]]
    ; CHECK: [[COPY60:%[0-9]+]]:_(s32) = COPY [[COPY42]](s32)
    ; CHECK: [[COPY61:%[0-9]+]]:_(s32) = COPY [[SELECT26]](s32)
    ; CHECK: [[COPY62:%[0-9]+]]:_(s32) = COPY [[ICMP10]](s32)
    ; CHECK: [[SELECT30:%[0-9]+]]:_(s32) = G_SELECT [[COPY62]](s32), [[COPY60]], [[COPY61]]
    ; CHECK: [[DEF8:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY63:%[0-9]+]]:_(s64) = COPY [[DEF8]](s64)
    ; CHECK: [[UV28:%[0-9]+]]:_(s32), [[UV29:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY63]](s64)
    ; CHECK: [[C43:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY64:%[0-9]+]]:_(s32) = COPY [[SELECT30]](s32)
    ; CHECK: [[AND6:%[0-9]+]]:_(s32) = G_AND [[COPY64]], [[C43]]
    ; CHECK: [[C44:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND7:%[0-9]+]]:_(s32) = G_AND [[UV29]], [[C44]]
    ; CHECK: [[OR16:%[0-9]+]]:_(s32) = G_OR [[AND7]], [[AND6]]
    ; CHECK: [[COPY65:%[0-9]+]]:_(s32) = COPY [[OR16]](s32)
    ; CHECK: [[COPY66:%[0-9]+]]:_(s32) = COPY [[OR7]](s32)
    ; CHECK: [[COPY67:%[0-9]+]]:_(s32) = COPY [[SELECT29]](s32)
    ; CHECK: [[COPY68:%[0-9]+]]:_(s32) = COPY [[ICMP11]](s32)
    ; CHECK: [[SELECT31:%[0-9]+]]:_(s32) = G_SELECT [[COPY68]](s32), [[COPY66]], [[COPY67]]
    ; CHECK: [[COPY69:%[0-9]+]]:_(s32) = COPY [[DEF4]](s32)
    ; CHECK: [[COPY70:%[0-9]+]]:_(s32) = COPY [[COPY65]](s32)
    ; CHECK: [[COPY71:%[0-9]+]]:_(s32) = COPY [[ICMP11]](s32)
    ; CHECK: [[SELECT32:%[0-9]+]]:_(s32) = G_SELECT [[COPY71]](s32), [[COPY69]], [[COPY70]]
    ; CHECK: [[DEF9:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY72:%[0-9]+]]:_(s64) = COPY [[DEF9]](s64)
    ; CHECK: [[UV30:%[0-9]+]]:_(s32), [[UV31:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY72]](s64)
    ; CHECK: [[C45:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY73:%[0-9]+]]:_(s32) = COPY [[SELECT32]](s32)
    ; CHECK: [[AND8:%[0-9]+]]:_(s32) = G_AND [[COPY73]], [[C45]]
    ; CHECK: [[C46:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND9:%[0-9]+]]:_(s32) = G_AND [[UV31]], [[C46]]
    ; CHECK: [[OR17:%[0-9]+]]:_(s32) = G_OR [[AND9]], [[AND8]]
    ; CHECK: [[COPY74:%[0-9]+]]:_(s32) = COPY [[OR17]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[SELECT31]](s32), [[COPY74]](s32)
    ; CHECK: [[C47:%[0-9]+]]:_(s32) = G_CONSTANT i32 48
    ; CHECK: [[SUB20:%[0-9]+]]:_(s32) = G_SUB [[COPY6]], [[C47]]
    ; CHECK: [[SUB21:%[0-9]+]]:_(s32) = G_SUB [[C47]], [[COPY6]]
    ; CHECK: [[C48:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP20:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY6]](s32), [[C47]]
    ; CHECK: [[ICMP21:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY6]](s32), [[C48]]
    ; CHECK: [[COPY75:%[0-9]+]]:_(s64) = COPY [[MV]](s64)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY75]], 48
    ; CHECK: [[C49:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV32:%[0-9]+]]:_(s32), [[UV33:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG]](s64)
    ; CHECK: [[SUB22:%[0-9]+]]:_(s32) = G_SUB [[COPY6]], [[C49]]
    ; CHECK: [[SUB23:%[0-9]+]]:_(s32) = G_SUB [[C49]], [[COPY6]]
    ; CHECK: [[C50:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP22:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY6]](s32), [[C49]]
    ; CHECK: [[ICMP23:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY6]](s32), [[C50]]
    ; CHECK: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV33]], [[COPY6]](s32)
    ; CHECK: [[LSHR12:%[0-9]+]]:_(s32) = G_LSHR [[UV32]], [[COPY6]](s32)
    ; CHECK: [[SHL20:%[0-9]+]]:_(s32) = G_SHL [[UV33]], [[SUB23]](s32)
    ; CHECK: [[OR18:%[0-9]+]]:_(s32) = G_OR [[LSHR12]], [[SHL20]]
    ; CHECK: [[C51:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR1:%[0-9]+]]:_(s32) = G_ASHR [[UV33]], [[C51]](s32)
    ; CHECK: [[ASHR2:%[0-9]+]]:_(s32) = G_ASHR [[UV33]], [[SUB22]](s32)
    ; CHECK: [[COPY76:%[0-9]+]]:_(s32) = COPY [[ICMP22]](s32)
    ; CHECK: [[SELECT33:%[0-9]+]]:_(s32) = G_SELECT [[COPY76]](s32), [[OR18]], [[ASHR2]]
    ; CHECK: [[COPY77:%[0-9]+]]:_(s32) = COPY [[ICMP23]](s32)
    ; CHECK: [[SELECT34:%[0-9]+]]:_(s32) = G_SELECT [[COPY77]](s32), [[UV32]], [[SELECT33]]
    ; CHECK: [[COPY78:%[0-9]+]]:_(s32) = COPY [[ICMP22]](s32)
    ; CHECK: [[SELECT35:%[0-9]+]]:_(s32) = G_SELECT [[COPY78]](s32), [[ASHR]], [[ASHR1]]
    ; CHECK: [[C52:%[0-9]+]]:_(s64) = G_CONSTANT i64 281474976710655
    ; CHECK: [[UV34:%[0-9]+]]:_(s32), [[UV35:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C52]](s64)
    ; CHECK: [[AND10:%[0-9]+]]:_(s32) = G_AND [[SELECT27]], [[UV34]]
    ; CHECK: [[AND11:%[0-9]+]]:_(s32) = G_AND [[COPY56]], [[UV35]]
    ; CHECK: [[C53:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB24:%[0-9]+]]:_(s32) = G_SUB [[COPY6]], [[C53]]
    ; CHECK: [[SUB25:%[0-9]+]]:_(s32) = G_SUB [[C53]], [[COPY6]]
    ; CHECK: [[C54:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP24:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY6]](s32), [[C53]]
    ; CHECK: [[ICMP25:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY6]](s32), [[C54]]
    ; CHECK: [[LSHR13:%[0-9]+]]:_(s32) = G_LSHR [[AND11]], [[COPY6]](s32)
    ; CHECK: [[LSHR14:%[0-9]+]]:_(s32) = G_LSHR [[AND10]], [[COPY6]](s32)
    ; CHECK: [[SHL21:%[0-9]+]]:_(s32) = G_SHL [[AND11]], [[SUB25]](s32)
    ; CHECK: [[OR19:%[0-9]+]]:_(s32) = G_OR [[LSHR14]], [[SHL21]]
    ; CHECK: [[C55:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[LSHR15:%[0-9]+]]:_(s32) = G_LSHR [[AND11]], [[SUB24]](s32)
    ; CHECK: [[COPY79:%[0-9]+]]:_(s32) = COPY [[ICMP24]](s32)
    ; CHECK: [[SELECT36:%[0-9]+]]:_(s32) = G_SELECT [[COPY79]](s32), [[OR19]], [[LSHR15]]
    ; CHECK: [[COPY80:%[0-9]+]]:_(s32) = COPY [[ICMP25]](s32)
    ; CHECK: [[SELECT37:%[0-9]+]]:_(s32) = G_SELECT [[COPY80]](s32), [[AND10]], [[SELECT36]]
    ; CHECK: [[COPY81:%[0-9]+]]:_(s32) = COPY [[ICMP24]](s32)
    ; CHECK: [[SELECT38:%[0-9]+]]:_(s32) = G_SELECT [[COPY81]](s32), [[LSHR13]], [[C55]]
    ; CHECK: [[C56:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB26:%[0-9]+]]:_(s32) = G_SUB [[SUB21]], [[C56]]
    ; CHECK: [[SUB27:%[0-9]+]]:_(s32) = G_SUB [[C56]], [[SUB21]]
    ; CHECK: [[C57:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP26:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB21]](s32), [[C56]]
    ; CHECK: [[ICMP27:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB21]](s32), [[C57]]
    ; CHECK: [[SHL22:%[0-9]+]]:_(s32) = G_SHL [[SELECT31]], [[SUB21]](s32)
    ; CHECK: [[LSHR16:%[0-9]+]]:_(s32) = G_LSHR [[SELECT31]], [[SUB27]](s32)
    ; CHECK: [[SHL23:%[0-9]+]]:_(s32) = G_SHL [[COPY74]], [[SUB21]](s32)
    ; CHECK: [[OR20:%[0-9]+]]:_(s32) = G_OR [[LSHR16]], [[SHL23]]
    ; CHECK: [[C58:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL24:%[0-9]+]]:_(s32) = G_SHL [[SELECT31]], [[SUB26]](s32)
    ; CHECK: [[COPY82:%[0-9]+]]:_(s32) = COPY [[ICMP26]](s32)
    ; CHECK: [[SELECT39:%[0-9]+]]:_(s32) = G_SELECT [[COPY82]](s32), [[SHL22]], [[C58]]
    ; CHECK: [[COPY83:%[0-9]+]]:_(s32) = COPY [[ICMP26]](s32)
    ; CHECK: [[SELECT40:%[0-9]+]]:_(s32) = G_SELECT [[COPY83]](s32), [[OR20]], [[SHL24]]
    ; CHECK: [[COPY84:%[0-9]+]]:_(s32) = COPY [[ICMP27]](s32)
    ; CHECK: [[SELECT41:%[0-9]+]]:_(s32) = G_SELECT [[COPY84]](s32), [[COPY74]], [[SELECT40]]
    ; CHECK: [[COPY85:%[0-9]+]]:_(s32) = COPY [[SELECT37]](s32)
    ; CHECK: [[COPY86:%[0-9]+]]:_(s32) = COPY [[SELECT39]](s32)
    ; CHECK: [[OR21:%[0-9]+]]:_(s32) = G_OR [[COPY85]], [[COPY86]]
    ; CHECK: [[COPY87:%[0-9]+]]:_(s32) = COPY [[SELECT38]](s32)
    ; CHECK: [[COPY88:%[0-9]+]]:_(s32) = COPY [[SELECT41]](s32)
    ; CHECK: [[OR22:%[0-9]+]]:_(s32) = G_OR [[COPY87]], [[COPY88]]
    ; CHECK: [[DEF10:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY89:%[0-9]+]]:_(s64) = COPY [[DEF10]](s64)
    ; CHECK: [[UV36:%[0-9]+]]:_(s32), [[UV37:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY89]](s64)
    ; CHECK: [[C59:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY90:%[0-9]+]]:_(s32) = COPY [[OR22]](s32)
    ; CHECK: [[AND12:%[0-9]+]]:_(s32) = G_AND [[COPY90]], [[C59]]
    ; CHECK: [[C60:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND13:%[0-9]+]]:_(s32) = G_AND [[UV37]], [[C60]]
    ; CHECK: [[OR23:%[0-9]+]]:_(s32) = G_OR [[AND13]], [[AND12]]
    ; CHECK: [[COPY91:%[0-9]+]]:_(s32) = COPY [[OR23]](s32)
    ; CHECK: [[COPY92:%[0-9]+]]:_(s64) = COPY [[MV]](s64)
    ; CHECK: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY92]], 48
    ; CHECK: [[UV38:%[0-9]+]]:_(s32), [[UV39:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG1]](s64)
    ; CHECK: [[C61:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[ASHR3:%[0-9]+]]:_(s32) = G_ASHR [[UV39]], [[C61]](s32)
    ; CHECK: [[C62:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR4:%[0-9]+]]:_(s32) = G_ASHR [[UV39]], [[C62]](s32)
    ; CHECK: [[COPY93:%[0-9]+]]:_(s64) = COPY [[MV]](s64)
    ; CHECK: [[SEXT_INREG2:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY93]], 48
    ; CHECK: [[C63:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV40:%[0-9]+]]:_(s32), [[UV41:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[SEXT_INREG2]](s64)
    ; CHECK: [[SUB28:%[0-9]+]]:_(s32) = G_SUB [[SUB20]], [[C63]]
    ; CHECK: [[SUB29:%[0-9]+]]:_(s32) = G_SUB [[C63]], [[SUB20]]
    ; CHECK: [[C64:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP28:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[SUB20]](s32), [[C63]]
    ; CHECK: [[ICMP29:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[SUB20]](s32), [[C64]]
    ; CHECK: [[ASHR5:%[0-9]+]]:_(s32) = G_ASHR [[UV41]], [[SUB20]](s32)
    ; CHECK: [[LSHR17:%[0-9]+]]:_(s32) = G_LSHR [[UV40]], [[SUB20]](s32)
    ; CHECK: [[SHL25:%[0-9]+]]:_(s32) = G_SHL [[UV41]], [[SUB29]](s32)
    ; CHECK: [[OR24:%[0-9]+]]:_(s32) = G_OR [[LSHR17]], [[SHL25]]
    ; CHECK: [[C65:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR6:%[0-9]+]]:_(s32) = G_ASHR [[UV41]], [[C65]](s32)
    ; CHECK: [[ASHR7:%[0-9]+]]:_(s32) = G_ASHR [[UV41]], [[SUB28]](s32)
    ; CHECK: [[COPY94:%[0-9]+]]:_(s32) = COPY [[ICMP28]](s32)
    ; CHECK: [[SELECT42:%[0-9]+]]:_(s32) = G_SELECT [[COPY94]](s32), [[OR24]], [[ASHR7]]
    ; CHECK: [[COPY95:%[0-9]+]]:_(s32) = COPY [[ICMP29]](s32)
    ; CHECK: [[SELECT43:%[0-9]+]]:_(s32) = G_SELECT [[COPY95]](s32), [[UV40]], [[SELECT42]]
    ; CHECK: [[COPY96:%[0-9]+]]:_(s32) = COPY [[ICMP28]](s32)
    ; CHECK: [[SELECT44:%[0-9]+]]:_(s32) = G_SELECT [[COPY96]](s32), [[ASHR5]], [[ASHR6]]
    ; CHECK: [[COPY97:%[0-9]+]]:_(s32) = COPY [[OR21]](s32)
    ; CHECK: [[COPY98:%[0-9]+]]:_(s32) = COPY [[SELECT43]](s32)
    ; CHECK: [[COPY99:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT45:%[0-9]+]]:_(s32) = G_SELECT [[COPY99]](s32), [[COPY97]], [[COPY98]]
    ; CHECK: [[COPY100:%[0-9]+]]:_(s32) = COPY [[COPY91]](s32)
    ; CHECK: [[COPY101:%[0-9]+]]:_(s32) = COPY [[SELECT44]](s32)
    ; CHECK: [[COPY102:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT46:%[0-9]+]]:_(s32) = G_SELECT [[COPY102]](s32), [[COPY100]], [[COPY101]]
    ; CHECK: [[DEF11:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY103:%[0-9]+]]:_(s64) = COPY [[DEF11]](s64)
    ; CHECK: [[UV42:%[0-9]+]]:_(s32), [[UV43:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY103]](s64)
    ; CHECK: [[C66:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY104:%[0-9]+]]:_(s32) = COPY [[SELECT46]](s32)
    ; CHECK: [[AND14:%[0-9]+]]:_(s32) = G_AND [[COPY104]], [[C66]]
    ; CHECK: [[C67:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND15:%[0-9]+]]:_(s32) = G_AND [[UV43]], [[C67]]
    ; CHECK: [[OR25:%[0-9]+]]:_(s32) = G_OR [[AND15]], [[AND14]]
    ; CHECK: [[COPY105:%[0-9]+]]:_(s32) = COPY [[OR25]](s32)
    ; CHECK: [[COPY106:%[0-9]+]]:_(s32) = COPY [[SELECT27]](s32)
    ; CHECK: [[COPY107:%[0-9]+]]:_(s32) = COPY [[SELECT45]](s32)
    ; CHECK: [[COPY108:%[0-9]+]]:_(s32) = COPY [[ICMP21]](s32)
    ; CHECK: [[SELECT47:%[0-9]+]]:_(s32) = G_SELECT [[COPY108]](s32), [[COPY106]], [[COPY107]]
    ; CHECK: [[COPY109:%[0-9]+]]:_(s32) = COPY [[COPY56]](s32)
    ; CHECK: [[COPY110:%[0-9]+]]:_(s32) = COPY [[COPY105]](s32)
    ; CHECK: [[COPY111:%[0-9]+]]:_(s32) = COPY [[ICMP21]](s32)
    ; CHECK: [[SELECT48:%[0-9]+]]:_(s32) = G_SELECT [[COPY111]](s32), [[COPY109]], [[COPY110]]
    ; CHECK: [[DEF12:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY112:%[0-9]+]]:_(s64) = COPY [[DEF12]](s64)
    ; CHECK: [[UV44:%[0-9]+]]:_(s32), [[UV45:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY112]](s64)
    ; CHECK: [[C68:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY113:%[0-9]+]]:_(s32) = COPY [[SELECT48]](s32)
    ; CHECK: [[AND16:%[0-9]+]]:_(s32) = G_AND [[COPY113]], [[C68]]
    ; CHECK: [[C69:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND17:%[0-9]+]]:_(s32) = G_AND [[UV45]], [[C69]]
    ; CHECK: [[OR26:%[0-9]+]]:_(s32) = G_OR [[AND17]], [[AND16]]
    ; CHECK: [[COPY114:%[0-9]+]]:_(s32) = COPY [[OR26]](s32)
    ; CHECK: [[COPY115:%[0-9]+]]:_(s32) = COPY [[SELECT34]](s32)
    ; CHECK: [[COPY116:%[0-9]+]]:_(s32) = COPY [[ASHR3]](s32)
    ; CHECK: [[COPY117:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT49:%[0-9]+]]:_(s32) = G_SELECT [[COPY117]](s32), [[COPY115]], [[COPY116]]
    ; CHECK: [[COPY118:%[0-9]+]]:_(s32) = COPY [[SELECT35]](s32)
    ; CHECK: [[COPY119:%[0-9]+]]:_(s32) = COPY [[ASHR4]](s32)
    ; CHECK: [[COPY120:%[0-9]+]]:_(s32) = COPY [[ICMP20]](s32)
    ; CHECK: [[SELECT50:%[0-9]+]]:_(s32) = G_SELECT [[COPY120]](s32), [[COPY118]], [[COPY119]]
    ; CHECK: [[DEF13:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
    ; CHECK: [[COPY121:%[0-9]+]]:_(s64) = COPY [[DEF13]](s64)
    ; CHECK: [[UV46:%[0-9]+]]:_(s32), [[UV47:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY121]](s64)
    ; CHECK: [[C70:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY122:%[0-9]+]]:_(s32) = COPY [[SELECT50]](s32)
    ; CHECK: [[AND18:%[0-9]+]]:_(s32) = G_AND [[COPY122]], [[C70]]
    ; CHECK: [[C71:%[0-9]+]]:_(s32) = G_CONSTANT i32 -65536
    ; CHECK: [[AND19:%[0-9]+]]:_(s32) = G_AND [[UV47]], [[C71]]
    ; CHECK: [[OR27:%[0-9]+]]:_(s32) = G_OR [[AND19]], [[AND18]]
    ; CHECK: [[COPY123:%[0-9]+]]:_(s32) = COPY [[OR27]](s32)
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $d4 = COPY [[SELECT47]](s32)
    ; CHECK: CALL @f, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $d2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: RET implicit $a11
    %0:_(p0) = COPY $a4
    %4:_(s96) = G_CONSTANT i96 31
    %6:_(s96) = G_CONSTANT i96 83
    %1:_(p0) = G_FRAME_INDEX %stack.0.result.ptr
    %2:_(p0) = G_FRAME_INDEX %stack.1.e
    G_STORE %0(p0), %1(p0) :: (store 4 into %ir.result.ptr)
    %3:_(s96) = G_LOAD %2(p0) :: (dereferenceable load 12 from %ir.1, align 4)
    %5:_(s96) = G_SHL %3, %4(s96)
    %7:_(s96) = G_ASHR %5, %6(s96)
    %8:_(s32) = G_TRUNC %7(s96)
    ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    $d4 = COPY %8(s32)
    CALL @f, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $d2
    ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    RET implicit $a11

...
