# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

# The legalizer has no way to legalize a G_PTR_ADD where the scalar offset is to be narrowed.
# Therefore we only test a valid s32 and a to-be-widened s8.
---
name:            test_ptr_add_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_ptr_add_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[COPY1]](s32)
    ; CHECK: $a2 = COPY [[PTR_ADD]](p0)
    %0:_(p0) = COPY $a4
    %1:_(s32) = COPY $d4
    %2:_(p0) = G_PTR_ADD %0, %1
    $a2 = COPY %2(p0)
...

---
name:            test_ptr_add_small_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_ptr_add_small_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(p0) = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY2]], 8
    ; CHECK: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[SEXT_INREG]](s32)
    ; CHECK: $a2 = COPY [[PTR_ADD]](p0)
    %0:_(p0) = COPY $a4
    %1:_(s32) = COPY $d4
    %2:_(s8) = G_TRUNC %1:_(s32)
    %4:_(p0) = G_PTR_ADD %0, %2
    $a2 = COPY %4(p0)
...
