# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
---
name:            test_sdiv_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_sdiv_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[SDIV:%[0-9]+]]:_(s32) = G_SDIV [[COPY]], [[COPY1]]
    ; CHECK: $d2 = COPY [[SDIV]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s32) = G_SDIV %0, %1
    $d2 = COPY %2(s32)
...
---
name:            test_sdiv_small_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_sdiv_small_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY2]], 8
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY3]], 8
    ; CHECK: [[SDIV:%[0-9]+]]:_(s32) = G_SDIV [[SEXT_INREG]], [[SEXT_INREG1]]
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[SDIV]](s32)
    ; CHECK: $d2 = COPY [[COPY4]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s8) = G_TRUNC %0:_(s32)
    %3:_(s8) = G_TRUNC %1:_(s32)
    %4:_(s8) = G_SDIV %2, %3
    %5:_(s32) = G_ANYEXT %4:_(s8)
    $d2 = COPY %5(s32)
...
---
name:            test_sdiv_big_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_sdiv_big_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e4 = COPY [[COPY]](s64)
    ; CHECK: $e6 = COPY [[COPY1]](s64)
    ; CHECK: CALL &__divdi3, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit $e6, implicit-def $e2
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY $e2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e2 = COPY [[COPY2]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = COPY $e6
    %2:_(s64) = G_SDIV %0, %1
    $e2 = COPY %2(s64)
...
---
name:            test_sdiv_nonpow2_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_sdiv_nonpow2_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: [[COPY2:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY2]], 48
    ; CHECK: [[COPY3:%[0-9]+]]:_(s64) = COPY [[COPY1]](s64)
    ; CHECK: [[SEXT_INREG1:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY3]], 48
    ; CHECK: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: $e4 = COPY [[SEXT_INREG]](s64)
    ; CHECK: $e6 = COPY [[SEXT_INREG1]](s64)
    ; CHECK: CALL &__divdi3, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit $e6, implicit-def $e2
    ; CHECK: [[COPY4:%[0-9]+]]:_(s64) = COPY $e2
    ; CHECK: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; CHECK: [[COPY5:%[0-9]+]]:_(s64) = COPY [[COPY4]](s64)
    ; CHECK: $e2 = COPY [[COPY5]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = COPY $e6
    %2:_(s48) = G_TRUNC %0:_(s64)
    %3:_(s48) = G_TRUNC %1:_(s64)
    %4:_(s48) = G_SDIV %2, %3
    %5:_(s64) = G_ANYEXT %4:_(s48)
    $e2 = COPY %5(s64)
...
