# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name: test_merge_s8_s4
body: |
  bb.0:
    ; CHECK-LABEL: name: test_merge_s8_s4
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY [[C2]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C3]]
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[C1]](s32)
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C4]]
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[AND]](s32)
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[C]](s32)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C5]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[SHL]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND2]], [[COPY3]]
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[OR]](s32)
    ; CHECK: $d0 = COPY [[COPY4]](s32)
    %0:_(s4) = G_CONSTANT i4 0
    %1:_(s4) = G_CONSTANT i4 1
    %2:_(s8) = G_MERGE_VALUES %0, %1
    %3:_(s32) = G_ANYEXT %2
    $d0 = COPY %3
...

---
name: test_merge_s12_s4
body: |
  bb.0:
    ; CHECK-LABEL: name: test_merge_s12_s4
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[DEF:%[0-9]+]]:_(s32) = G_IMPLICIT_DEF
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY [[C3]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY]], [[C4]]
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[C1]](s32)
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C5]]
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[AND]](s32)
    ; CHECK: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[C]](s32)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C6]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[SHL]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND2]], [[COPY3]]
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[OR]](s32)
    ; CHECK: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[C7]](s32)
    ; CHECK: [[AND3:%[0-9]+]]:_(s32) = G_AND [[COPY4]], [[C8]]
    ; CHECK: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY [[DEF]](s32)
    ; CHECK: [[AND4:%[0-9]+]]:_(s32) = G_AND [[COPY5]], [[C9]]
    ; CHECK: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[AND4]], [[AND3]](s32)
    ; CHECK: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[C2]](s32)
    ; CHECK: [[AND5:%[0-9]+]]:_(s32) = G_AND [[COPY6]], [[C10]]
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[SHL1]](s32)
    ; CHECK: [[OR1:%[0-9]+]]:_(s32) = G_OR [[AND5]], [[COPY7]]
    ; CHECK: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[OR1]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(s16) = G_MERGE_VALUES [[TRUNC]](s8), [[TRUNC1]](s8)
    ; CHECK: [[ANYEXT:%[0-9]+]]:_(s32) = G_ANYEXT [[MV]](s16)
    ; CHECK: $d0 = COPY [[ANYEXT]](s32)
    %0:_(s4) = G_CONSTANT i4 0
    %1:_(s4) = G_CONSTANT i4 1
    %2:_(s4) = G_CONSTANT i4 2
    %3:_(s12) = G_MERGE_VALUES %0, %1, %2
    %4:_(s32) = G_ANYEXT %3
    $d0 = COPY %4
...

---
name: test_merge_s32_s8
body: |
  bb.0:
    ; CHECK-LABEL: name: test_merge_s32_s8
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[C]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[C1]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC [[C2]](s32)
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[TRUNC3:%[0-9]+]]:_(s8) = G_TRUNC [[C3]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(s32) = G_MERGE_VALUES [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC3]](s8)
    ; CHECK: $d0 = COPY [[MV]](s32)
    %0:_(s8) = G_CONSTANT i8 0
    %1:_(s8) = G_CONSTANT i8 1
    %2:_(s8) = G_CONSTANT i8 2
    %3:_(s8) = G_CONSTANT i8 3
    %4:_(s32) = G_MERGE_VALUES %0, %1, %2, %3
    $d0 = COPY %4
...

---
name: test_merge_p0_s4
body: |
  bb.0:
    liveins: $d0, $d1, $d2, $d3, $d4, $d5, $d6, $d7
    ; CHECK-LABEL: name: test_merge_p0_s4
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d0
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d1
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY $d2
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY $d3
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY $d6
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY $d7
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY8:%[0-9]+]]:_(s32) = COPY [[C]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY8]], [[C1]]
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY9:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY9]], [[C2]]
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[AND]](s32)
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY10:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[AND2:%[0-9]+]]:_(s32) = G_AND [[COPY10]], [[C3]]
    ; CHECK: [[COPY11:%[0-9]+]]:_(s32) = COPY [[SHL]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND2]], [[COPY11]]
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s8) = G_TRUNC [[OR]](s32)
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY12:%[0-9]+]]:_(s32) = COPY [[C4]](s32)
    ; CHECK: [[AND3:%[0-9]+]]:_(s32) = G_AND [[COPY12]], [[C5]]
    ; CHECK: [[C6:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY13:%[0-9]+]]:_(s32) = COPY [[COPY3]](s32)
    ; CHECK: [[AND4:%[0-9]+]]:_(s32) = G_AND [[COPY13]], [[C6]]
    ; CHECK: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[AND4]], [[AND3]](s32)
    ; CHECK: [[C7:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY14:%[0-9]+]]:_(s32) = COPY [[COPY2]](s32)
    ; CHECK: [[AND5:%[0-9]+]]:_(s32) = G_AND [[COPY14]], [[C7]]
    ; CHECK: [[COPY15:%[0-9]+]]:_(s32) = COPY [[SHL1]](s32)
    ; CHECK: [[OR1:%[0-9]+]]:_(s32) = G_OR [[AND5]], [[COPY15]]
    ; CHECK: [[TRUNC1:%[0-9]+]]:_(s8) = G_TRUNC [[OR1]](s32)
    ; CHECK: [[C8:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C9:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY16:%[0-9]+]]:_(s32) = COPY [[C8]](s32)
    ; CHECK: [[AND6:%[0-9]+]]:_(s32) = G_AND [[COPY16]], [[C9]]
    ; CHECK: [[C10:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY17:%[0-9]+]]:_(s32) = COPY [[COPY5]](s32)
    ; CHECK: [[AND7:%[0-9]+]]:_(s32) = G_AND [[COPY17]], [[C10]]
    ; CHECK: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[AND7]], [[AND6]](s32)
    ; CHECK: [[C11:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY18:%[0-9]+]]:_(s32) = COPY [[COPY4]](s32)
    ; CHECK: [[AND8:%[0-9]+]]:_(s32) = G_AND [[COPY18]], [[C11]]
    ; CHECK: [[COPY19:%[0-9]+]]:_(s32) = COPY [[SHL2]](s32)
    ; CHECK: [[OR2:%[0-9]+]]:_(s32) = G_OR [[AND8]], [[COPY19]]
    ; CHECK: [[TRUNC2:%[0-9]+]]:_(s8) = G_TRUNC [[OR2]](s32)
    ; CHECK: [[C12:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C13:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY20:%[0-9]+]]:_(s32) = COPY [[C12]](s32)
    ; CHECK: [[AND9:%[0-9]+]]:_(s32) = G_AND [[COPY20]], [[C13]]
    ; CHECK: [[C14:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY21:%[0-9]+]]:_(s32) = COPY [[COPY7]](s32)
    ; CHECK: [[AND10:%[0-9]+]]:_(s32) = G_AND [[COPY21]], [[C14]]
    ; CHECK: [[SHL3:%[0-9]+]]:_(s32) = G_SHL [[AND10]], [[AND9]](s32)
    ; CHECK: [[C15:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK: [[COPY22:%[0-9]+]]:_(s32) = COPY [[COPY6]](s32)
    ; CHECK: [[AND11:%[0-9]+]]:_(s32) = G_AND [[COPY22]], [[C15]]
    ; CHECK: [[COPY23:%[0-9]+]]:_(s32) = COPY [[SHL3]](s32)
    ; CHECK: [[OR3:%[0-9]+]]:_(s32) = G_OR [[AND11]], [[COPY23]]
    ; CHECK: [[TRUNC3:%[0-9]+]]:_(s8) = G_TRUNC [[OR3]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(p0) = G_MERGE_VALUES [[TRUNC]](s8), [[TRUNC1]](s8), [[TRUNC2]](s8), [[TRUNC3]](s8)
    ; CHECK: $a2 = COPY [[MV]](p0)
    %0:_(s32) = COPY $d0
    %1:_(s32) = COPY $d1
    %2:_(s32) = COPY $d2
    %3:_(s32) = COPY $d3
    %4:_(s32) = COPY $d4
    %5:_(s32) = COPY $d5
    %6:_(s32) = COPY $d6
    %7:_(s32) = COPY $d7
    %8:_(s4) = G_TRUNC %0
    %9:_(s4) = G_TRUNC %1
    %10:_(s4) = G_TRUNC %2
    %11:_(s4) = G_TRUNC %3
    %12:_(s4) = G_TRUNC %4
    %13:_(s4) = G_TRUNC %5
    %14:_(s4) = G_TRUNC %6
    %15:_(s4) = G_TRUNC %7
    %16:_(p0) = G_MERGE_VALUES %8, %9, %10, %11, %12, %13, %14, %15
    $a2 = COPY %16
...

---
name: test_merge_p0_s16
body: |
  bb.0:
    liveins: $d0, $d1
    ; CHECK-LABEL: name: test_merge_p0_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d0
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d1
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[COPY]](s32)
    ; CHECK: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(p0) = G_MERGE_VALUES [[TRUNC]](s16), [[TRUNC1]](s16)
    ; CHECK: $a2 = COPY [[MV]](p0)
    %0:_(s32) = COPY $d0
    %1:_(s32) = COPY $d1
    %2:_(s16) = G_TRUNC %0
    %3:_(s16) = G_TRUNC %1
    %4:_(p0) = G_MERGE_VALUES %2, %3
    $a2 = COPY %4
...

---
name: test_merge_s64_s32
body: |
  bb.0:
    liveins: $d0, $d1
    ; CHECK-LABEL: name: test_merge_s64_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d0
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d1
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
    ; CHECK: $e0 = COPY [[MV]](s64)
    %0:_(s32) = COPY $d0
    %1:_(s32) = COPY $d1
    %2:_(s64) = G_MERGE_VALUES %0, %1
    $e0 = COPY %2
...

---
name: test_merge_s96_s16
body: |
  bb.0:
    ; CHECK-LABEL: name: test_merge_s96_s16
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s16) = G_TRUNC [[C]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[TRUNC1:%[0-9]+]]:_(s16) = G_TRUNC [[C1]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
    ; CHECK: [[TRUNC2:%[0-9]+]]:_(s16) = G_TRUNC [[C2]](s32)
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[TRUNC3:%[0-9]+]]:_(s16) = G_TRUNC [[C3]](s32)
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[TRUNC]](s16), [[TRUNC1]](s16), [[TRUNC2]](s16), [[TRUNC3]](s16)
    ; CHECK: $e0 = COPY [[MV]](s64)
    %0:_(s16) = G_CONSTANT i16 0
    %1:_(s16) = G_CONSTANT i16 1
    %2:_(s16) = G_CONSTANT i16 2
    %3:_(s16) = G_CONSTANT i16 3
    %4:_(s16) = G_CONSTANT i16 4
    %5:_(s16) = G_CONSTANT i16 5
    %8:_(s96) = G_MERGE_VALUES %0, %1, %2, %3, %4, %5
    %9:_(s64) = G_TRUNC %8
    $e0 = COPY %9
...
