# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
---
name:            test_shl_i32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_shl_i32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[COPY1]](s32)
    ; CHECK: $d2 = COPY [[SHL]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s32) = G_SHL %0, %1
    $d2 = COPY %2(s32)
...
---
name:            test_shl_small_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_shl_small_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 255
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY3]], [[AND]](s32)
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[SHL]](s32)
    ; CHECK: $d2 = COPY [[COPY4]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s8) = G_TRUNC %0:_(s32)
    %3:_(s8) = G_TRUNC %1:_(s32)
    %4:_(s8) = G_SHL %2, %3
    %5:_(s32) = G_ANYEXT %4:_(s8)
    $d2 = COPY %5(s32)
...

---
name:            test_shl_small_nonpow2_scalar
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_shl_small_nonpow2_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 7
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY3]], [[AND]](s32)
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[SHL]](s32)
    ; CHECK: $d2 = COPY [[COPY4]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s3) = G_TRUNC %0:_(s32)
    %3:_(s3) = G_TRUNC %1:_(s32)
    %4:_(s3) = G_SHL %2, %3
    %5:_(s32) = G_ANYEXT %4:_(s3)
    $d2 = COPY %5(s32)
...
---
name:            test_shl_big_scalar
body:             |
  bb.0.entry:
    ; There are two cases to consider:
    ; 1) If the shift amount is >= 32-bit, the lower bits of the source are
    ;    shifted completely into the higher bits of the result (using an
    ;    adjusted shift amount, SUB), while the lower bits of the result are
    ;    0.
    ; 2) If the shift amount is < 32, both the lower bits and the upper bits of
    ;    the src are shifted by the same amount, however parts of the lower bits
    ;    might be shifted into the higher part. Thus, the lower src part is
    ;    additionally shifted right (by SUB1) and OR'ed to the left-shifted src
    ;    high part.
    ; CHECK-LABEL: name: test_shl_big_scalar
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[COPY1]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[TRUNC]], [[C]]
    ; CHECK: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[C]], [[TRUNC]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[TRUNC]](s32), [[C]]
    ; CHECK: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[TRUNC]](s32), [[C1]]
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[UV]], [[TRUNC]](s32)
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[SUB1]](s32)
    ; CHECK: [[SHL1:%[0-9]+]]:_(s32) = G_SHL [[UV1]], [[TRUNC]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[LSHR]], [[SHL1]]
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL2:%[0-9]+]]:_(s32) = G_SHL [[UV]], [[SUB]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[COPY2]](s32), [[SHL]], [[C2]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[COPY3]](s32), [[OR]], [[SHL2]]
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[COPY4]](s32), [[UV1]], [[SELECT1]]
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[SELECT]](s32), [[SELECT2]](s32)
    ; CHECK: $e2 = COPY [[MV]](s64)
   %0:_(s64) = COPY $e4
   %1:_(s64) = COPY $e6
   %2:_(s64) = G_SHL %0, %1
   $e2 = COPY %2(s64)
...
---
name:            test_shl_cimm_32
body:             |
  bb.1:
    liveins: $d4
    ; CHECK-LABEL: name: test_shl_cimm_32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK: $d2 = COPY [[SHL]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = G_CONSTANT i32 8
    %2:_(s32) = G_SHL %0, %1(s32)
    $d2 = COPY %2(s32)
...
---
name:            test_shl_s33
body:             |
  bb.0.entry:
    ; This test is modelled after an actual SuperTest failure
    ; CHECK-LABEL: name: test_shl_s33
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY1]], [[C]]
    ; CHECK: [[SUB1:%[0-9]+]]:_(s32) = G_SUB [[C]], [[COPY1]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[COPY1]](s32), [[C]]
    ; CHECK: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[COPY1]](s32), [[C1]]
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL %21, [[COPY1]](s32)
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR %21, [[SUB1]](s32)
    ; CHECK: [[SHL1:%[0-9]+]]:_(s32) = G_SHL %23, [[COPY1]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[LSHR]], [[SHL1]]
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[SHL2:%[0-9]+]]:_(s32) = G_SHL %21, [[SUB]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[COPY2]](s32), [[SHL]], [[C2]]
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[COPY3]](s32), [[OR]], [[SHL2]]
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[SELECT2:%[0-9]+]]:_(s32) = G_SELECT [[COPY4]](s32), [[SELECT2]], [[SELECT1]]
    ; CHECK: $d2 = COPY [[SELECT]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s33) = G_ZEXT %0
    %3:_(s33) = G_SHL %3, %1
    %4:_(s32) = G_TRUNC %3
    $d2 = COPY %4(s32)
...
