# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name:            extract_s16_s32
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s16_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; CHECK: $d4 = COPY [[SEXT_INREG]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_EXTRACT %0, 0
    %2:_(s32) = G_SEXT %1(s16)
    $d4 = COPY %2
...

---
name:            extract_s1_s32
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s1_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY]], [[C]](s32)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[LSHR]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 1
    ; CHECK: $d4 = COPY [[SEXT_INREG]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s1) = G_EXTRACT %0, 31
    %2:_(s32) = G_SEXT %1(s1)
    $d4 = COPY %2
...

---
name:            extract_s32_s64
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s32_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[UV1]](s32)
    ; CHECK: $d4 = COPY [[COPY1]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s32) = G_EXTRACT %0, 32
    $d4 = COPY %1
...

---
name:            extract_s8_s64
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s8_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[UV]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 8
    ; CHECK: $d4 = COPY [[SEXT_INREG]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s8) = G_EXTRACT %0, 0
    %2:_(s32) = G_SEXT %1(s8)
    $d4 = COPY %2
...

---
name:            extract_s5_s24
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s5_s24
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[COPY1]], [[C]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[LSHR]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY2]], 5
    ; CHECK: $d4 = COPY [[SEXT_INREG]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s24) = G_TRUNC %0(s32)
    %2:_(s5) = G_EXTRACT %1, 3
    %3:_(s32) = G_SEXT %2(s5)
    $d4 = COPY %3
...

---
name:            extract_s32_s48
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s32_s48
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[LSHR]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C1]]
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[UV1]](s32)
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY3]], [[C2]]
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[C3]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; CHECK: $d4 = COPY [[OR]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s48) = G_TRUNC %0(s64)
    %2:_(s32) = G_EXTRACT %1, 16
    $d4 = COPY %2
...

---
name:            extract_s16_s48
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s16_s48
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 8
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[LSHR]](s32)
    ; CHECK: $d4 = COPY [[COPY2]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s48) = G_TRUNC %0(s64)
    %2:_(s16) = G_EXTRACT %1, 8
    %3:_(s32) = G_ANYEXT %2(s16)
    $d4 = COPY %3
...

---
name:            extract_s64_s96
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s64_s96
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV1]], [[C]](s32)
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[UV1]](s32), [[ASHR]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s96) = G_SEXT %0(s64)
    %2:_(s64) = G_EXTRACT %1, 32
    $e4 = COPY %2
...

---
name:            extract_s32_s96
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s32_s96
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV1]], [[C]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C1]](s32)
    ; CHECK: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[LSHR]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C2]]
    ; CHECK: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 65535
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[UV1]](s32)
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[COPY2]], [[C3]]
    ; CHECK: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
    ; CHECK: [[SHL:%[0-9]+]]:_(s32) = G_SHL [[AND1]], [[C4]](s32)
    ; CHECK: [[OR:%[0-9]+]]:_(s32) = G_OR [[AND]], [[SHL]]
    ; CHECK: $d4 = COPY [[OR]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s96) = G_SEXT %0(s64)
    %2:_(s32) = G_EXTRACT %1, 16
    $d4 = COPY %2
...

---
name:            extract_s16_s96
body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: extract_s16_s96
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK: [[ASHR:%[0-9]+]]:_(s32) = G_ASHR [[UV1]], [[C]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 5
    ; CHECK: [[LSHR:%[0-9]+]]:_(s32) = G_LSHR [[UV]], [[C1]](s32)
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY [[LSHR]](s32)
    ; CHECK: $d4 = COPY [[COPY1]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s96) = G_SEXT %0(s64)
    %2:_(s16) = G_EXTRACT %1, 5
    %3:_(s32) = G_ANYEXT %2(s16)
    $d4 = COPY %3
...
