# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -mcpu=tc4xx -global-isel -run-pass=legalizer \
# RUN:      -verify-machineinstrs %s -o - | FileCheck -check-prefixes=TC4XX %s
# RUN: llc -O0 -mtriple=tricore -mcpu=tc3xx -global-isel -run-pass=legalizer \
# RUN:      -verify-machineinstrs %s -o - | FileCheck -check-prefixes=TC3XX %s

---
name:            sitofp_s32_s32
body:             |
  bb.0:
    liveins: $d4

    ; TC4XX-LABEL: name: sitofp_s32_s32
    ; TC4XX: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC4XX: [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[COPY]](s32)
    ; TC4XX: $d4 = COPY [[SITOFP]](s32)
    ; TC3XX-LABEL: name: sitofp_s32_s32
    ; TC3XX: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC3XX: [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[COPY]](s32)
    ; TC3XX: $d4 = COPY [[SITOFP]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = G_SITOFP %0(s32)
    $d4 = COPY %1(s32)
...

---
name:            sitofp_s64_s32
body:             |
  bb.0:
    liveins: $e4

    ; TC4XX-LABEL: name: sitofp_s64_s32
    ; TC4XX: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC4XX: [[SITOFP:%[0-9]+]]:_(s64) = G_SITOFP [[COPY]](s32)
    ; TC4XX: $e4 = COPY [[SITOFP]](s64)
    ; TC3XX-LABEL: name: sitofp_s64_s32
    ; TC3XX: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC3XX: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $d4 = COPY [[COPY]](s32)
    ; TC3XX: CALL &__floatsidf, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $d4, implicit-def $e2
    ; TC3XX: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; TC3XX: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $e4 = COPY [[COPY1]](s64)
    %0:_(s32) = COPY $d4
    %1:_(s64) = G_SITOFP %0(s32)
    $e4 = COPY %1(s64)
...

---
name:            sitofp_s64_s64
body:             |
  bb.0:
    liveins: $e4

    ; TC4XX-LABEL: name: sitofp_s64_s64
    ; TC4XX: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC4XX: [[SITOFP:%[0-9]+]]:_(s64) = G_SITOFP [[COPY]](s64)
    ; TC4XX: $e4 = COPY [[SITOFP]](s64)
    ; TC3XX-LABEL: name: sitofp_s64_s64
    ; TC3XX: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC3XX: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $e4 = COPY [[COPY]](s64)
    ; TC3XX: CALL &__floatdidf, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $e2
    ; TC3XX: [[COPY1:%[0-9]+]]:_(s64) = COPY $e2
    ; TC3XX: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $e4 = COPY [[COPY1]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = G_SITOFP %0(s64)
    $e4 = COPY %1(s64)
...

---
name:            sitofp_smaller_than_s32
body:             |
  bb.0:
    liveins: $d4

    ; TC4XX-LABEL: name: sitofp_smaller_than_s32
    ; TC4XX: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC4XX: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; TC4XX: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; TC4XX: [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[SEXT_INREG]](s32)
    ; TC4XX: $d4 = COPY [[SITOFP]](s32)
    ; TC3XX-LABEL: name: sitofp_smaller_than_s32
    ; TC3XX: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; TC3XX: [[COPY1:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; TC3XX: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY1]], 16
    ; TC3XX: [[SITOFP:%[0-9]+]]:_(s32) = G_SITOFP [[SEXT_INREG]](s32)
    ; TC3XX: $d4 = COPY [[SITOFP]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_TRUNC %0
    %2:_(s32) = G_SITOFP %1
    $d4 = COPY %2
...

---
name:            sitofp_between_s32_and_s64
body:             |
  bb.0:
    liveins: $e4

    ; TC4XX-LABEL: name: sitofp_between_s32_and_s64
    ; TC4XX: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC4XX: [[COPY1:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; TC4XX: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY1]], 48
    ; TC4XX: [[SITOFP:%[0-9]+]]:_(s64) = G_SITOFP [[SEXT_INREG]](s64)
    ; TC4XX: $e4 = COPY [[SITOFP]](s64)
    ; TC3XX-LABEL: name: sitofp_between_s32_and_s64
    ; TC3XX: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC3XX: [[COPY1:%[0-9]+]]:_(s64) = COPY [[COPY]](s64)
    ; TC3XX: [[SEXT_INREG:%[0-9]+]]:_(s64) = G_SEXT_INREG [[COPY1]], 48
    ; TC3XX: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $e4 = COPY [[SEXT_INREG]](s64)
    ; TC3XX: CALL &__floatdidf, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $e2
    ; TC3XX: [[COPY2:%[0-9]+]]:_(s64) = COPY $e2
    ; TC3XX: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $e4 = COPY [[COPY2]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s48) = G_TRUNC %0
    %2:_(s64) = G_SITOFP %1
    $e4 = COPY %2
...

---
name:            sitofp_s32_s64
body:             |
  bb.0:
    liveins: $e4

    ; TC4XX-LABEL: name: sitofp_s32_s64
    ; TC4XX: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC4XX: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; TC4XX: $e4 = COPY [[COPY]](s64)
    ; TC4XX: CALL &__floatdisf, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $d2
    ; TC4XX: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; TC4XX: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; TC4XX: $d2 = COPY [[COPY1]](s32)
    ; TC3XX-LABEL: name: sitofp_s32_s64
    ; TC3XX: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; TC3XX: ADJCALLSTACKDOWN 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $e4 = COPY [[COPY]](s64)
    ; TC3XX: CALL &__floatdisf, csr_tricore_uppercontext, implicit-def $a11, implicit $psw, implicit $e4, implicit-def $d2
    ; TC3XX: [[COPY1:%[0-9]+]]:_(s32) = COPY $d2
    ; TC3XX: ADJCALLSTACKUP 0, 0, implicit-def $a10, implicit $a10
    ; TC3XX: $d2 = COPY [[COPY1]](s32)
    %0:_(s64) = COPY $e4
    %1:_(s32) = G_SITOFP %0
    $d2 = COPY %1
...
