# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name:            legalize_phi_s1
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
  - { id: 5, class: _ }
  - { id: 6, class: _ }
  - { id: 7, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_s1
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $d4, $d5, $d6
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY2]](s32)
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK:   [[COPY4:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[COPY3]](s32), %bb.0, [[COPY4]](s32), %bb.1
  ; CHECK:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK:   [[COPY5:%[0-9]+]]:_(s32) = COPY [[PHI]](s32)
  ; CHECK:   [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY5]], [[C]]
  ; CHECK:   $d2 = COPY [[AND]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $d4, $d5, $d6

    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32) = COPY $d6
    %3(s1) = G_TRUNC %2(s32)
    %4(s1) = G_TRUNC %0(s32)
    %5(s1) = G_TRUNC %1(s32)
    G_BRCOND %3(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %6(s1) = G_PHI %4(s1), %bb.0, %5(s1), %bb.1
    %7(s32) = G_ZEXT %6(s1)
    $d2 = COPY %7(s32)
    RET implicit $a11, implicit $d2

...

---
name:            legalize_phi_s8
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
  - { id: 5, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_s8
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
  ; CHECK:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -42
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY [[C1]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY [[C]](s32)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[COPY1]](s32), %bb.0, [[COPY2]](s32), %bb.1
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY [[PHI]](s32)
  ; CHECK:   [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY3]], 8
  ; CHECK:   $d2 = COPY [[SEXT_INREG]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $d4

    %0(s32) = COPY $d4
    %1(s8) = G_CONSTANT i8 42
    %2(s8) = G_CONSTANT i8 -42
    %3(s1) = G_TRUNC %0(s32)
    G_BRCOND %3(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %4(s8) = G_PHI %2(s8), %bb.0, %1(s8), %bb.1
    %5(s32) = G_SEXT %4(s8)
    $d2 = COPY %5(s32)
    RET implicit $a11, implicit $d2

...

---
name:            legalize_phi_s16
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
  - { id: 5, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_s16
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
  ; CHECK:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 -42
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY [[C1]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY [[C]](s32)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[COPY1]](s32), %bb.0, [[COPY2]](s32), %bb.1
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY [[PHI]](s32)
  ; CHECK:   [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY3]], 16
  ; CHECK:   $d2 = COPY [[SEXT_INREG]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $d4

    %0(s32) = COPY $d4
    %1(s16) = G_CONSTANT i16 42
    %2(s16) = G_CONSTANT i16 -42
    %3(s1) = G_TRUNC %0(s32)
    G_BRCOND %3(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %4(s16) = G_PHI %2(s16), %bb.0, %1(s16), %bb.1
    %5(s32) = G_SEXT %4(s16)
    $d2 = COPY %5(s32)
    RET implicit $a11, implicit $d2

...

---
name:            legalize_phi_s18
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
  - { id: 5, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_s18
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 42
  ; CHECK:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 262102
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY [[C1]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY [[C]](s32)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[COPY1]](s32), %bb.0, [[COPY2]](s32), %bb.1
  ; CHECK:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 262143
  ; CHECK:   [[COPY3:%[0-9]+]]:_(s32) = COPY [[PHI]](s32)
  ; CHECK:   [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY3]], [[C2]]
  ; CHECK:   $d2 = COPY [[AND]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $d4

    %0(s32) = COPY $d4
    %1(s18) = G_CONSTANT i18 42
    %2(s18) = G_CONSTANT i18 -42
    %3(s1) = G_TRUNC %0(s32)
    G_BRCOND %3(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %4(s18) = G_PHI %2(s18), %bb.0, %1(s18), %bb.1
    %5(s32) = G_ZEXT %4(s18)
    $d2 = COPY %5(s32)
    RET implicit $a11, implicit $d2

...

---
name:            legalize_phi_s32
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_s32
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $d4, $d5, $d6
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d6
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY2]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(s32) = G_PHI [[COPY]](s32), %bb.0, [[COPY1]](s32), %bb.1
  ; CHECK:   $d2 = COPY [[PHI]](s32)
  ; CHECK:   RET implicit $a11, implicit $d2
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $d4, $d5, $d6

    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32) = COPY $d6
    %3(s1) = G_TRUNC %2(s32)
    G_BRCOND %3(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %4(s32) = G_PHI %0(s32), %bb.0, %1(s32), %bb.1
    $d2 = COPY %4(s32)
    RET implicit $a11, implicit $d2

...

---
name:            legalize_phi_s64
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_s64
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $e4, $e6, $d7
  ; CHECK:   [[COPY:%[0-9]+]]:_(s64) = COPY $e4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d7
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY2]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(s64) = G_PHI [[COPY]](s64), %bb.0, [[COPY1]](s64), %bb.1
  ; CHECK:   $e2 = COPY [[PHI]](s64)
  ; CHECK:   RET implicit $a11, implicit $e2
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $e4, $e6, $d7

    %0(s64) = COPY $e4
    %1(s64) = COPY $e6
    %2(s32) = COPY $d7
    %3(s1) = G_TRUNC %2(s32)
    G_BRCOND %3(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %4(s64) = G_PHI %0(s64), %bb.0, %1(s64), %bb.1
    $e2 = COPY %4(s64)
    RET implicit $a11, implicit $e2

...

---
name:            legalize_phi_s128
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
  - { id: 5, class: _ }
  - { id: 6, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_s128
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $d4
  ; CHECK:   [[COPY:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[DEF:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
  ; CHECK:   [[DEF1:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
  ; CHECK:   [[DEF2:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
  ; CHECK:   [[DEF3:%[0-9]+]]:_(s64) = G_IMPLICIT_DEF
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(s64) = G_PHI [[DEF2]](s64), %bb.0, [[DEF]](s64), %bb.1
  ; CHECK:   [[PHI1:%[0-9]+]]:_(s64) = G_PHI [[DEF3]](s64), %bb.0, [[DEF1]](s64), %bb.1
  ; CHECK:   $e2 = COPY [[PHI]](s64)
  ; CHECK:   $e4 = COPY [[PHI1]](s64)
  ; CHECK:   RET implicit $a11, implicit $e2, implicit $e4
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $d4

    %0(s32) = COPY $d4
    %1(s128) = G_IMPLICIT_DEF
    %2(s128) = G_IMPLICIT_DEF
    %3(s1) = G_TRUNC %0(s32)
    G_BRCOND %3(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %4(s128) = G_PHI %2(s128), %bb.0, %1(s128), %bb.1
    %5(s64), %6(s64) = G_UNMERGE_VALUES %4(s128)
    $e2 = COPY %5(s64)
    $e4 = COPY %6(s64)
    RET implicit $a11, implicit $e2, implicit $e4

...

---
name:            legalize_phi_ptr
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
liveins:
body:             |
  ; CHECK-LABEL: name: legalize_phi_ptr
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK:   liveins: $d4, $a4, $a5
  ; CHECK:   [[COPY:%[0-9]+]]:_(p0) = COPY $a4
  ; CHECK:   [[COPY1:%[0-9]+]]:_(p0) = COPY $a5
  ; CHECK:   [[COPY2:%[0-9]+]]:_(s32) = COPY $d4
  ; CHECK:   [[TRUNC:%[0-9]+]]:_(s1) = G_TRUNC [[COPY2]](s32)
  ; CHECK:   G_BRCOND [[TRUNC]](s1), %bb.1
  ; CHECK:   G_BR %bb.2
  ; CHECK: bb.1:
  ; CHECK:   successors: %bb.2(0x80000000)
  ; CHECK: bb.2:
  ; CHECK:   [[PHI:%[0-9]+]]:_(p0) = G_PHI [[COPY]](p0), %bb.0, [[COPY1]](p0), %bb.1
  ; CHECK:   $a2 = COPY [[PHI]](p0)
  ; CHECK:   RET implicit $a11, implicit $a2
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $d4, $a4, $a5

    %0(p0) = COPY $a4
    %1(p0) = COPY $a5
    %4(s32) = COPY $d4
    %2(s1) = G_TRUNC %4(s32)
    G_BRCOND %2(s1), %bb.1
    G_BR %bb.2

  bb.1:
    successors: %bb.2

  bb.2:
    %3(p0) = G_PHI %0(p0), %bb.0, %1(p0), %bb.1
    $a2 = COPY %3(p0)
    RET implicit $a11, implicit $a2

...
