# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s

---
name:            ssubo_s16
body:             |
  bb.1:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: ssubo_s16
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY2]], [[COPY3]]
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[SUB]](s32)
    ; CHECK: [[SEXT_INREG:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY4]], 16
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY [[COPY]](s32)
    ; CHECK: [[SEXT_INREG1:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY5]], 16
    ; CHECK: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[SEXT_INREG]](s32), [[SEXT_INREG1]]
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[SEXT_INREG2:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY6]], 16
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[C]](s32)
    ; CHECK: [[SEXT_INREG3:%[0-9]+]]:_(s32) = G_SEXT_INREG [[COPY7]], 16
    ; CHECK: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[SEXT_INREG2]](s32), [[SEXT_INREG3]]
    ; CHECK: [[COPY8:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[COPY9:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY8]], [[COPY9]]
    ; CHECK: [[COPY10:%[0-9]+]]:_(s32) = COPY [[SUB]](s32)
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY11:%[0-9]+]]:_(s32) = COPY [[XOR]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY11]], [[C1]]
    ; CHECK: $d4 = COPY [[COPY10]](s32)
    ; CHECK: $d5 = COPY [[AND]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s16) = G_TRUNC %0
    %3:_(s16) = G_TRUNC %1
    %4:_(s16), %5:_(s1) = G_SSUBO %2, %3
    %6:_(s32) = G_ANYEXT %4
    %7:_(s32) = G_ZEXT %5
    $d4 = COPY %6
    $d5 = COPY %7
...

---
name:            ssubo_s32
body:             |
  bb.1:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: ssubo_s32
    ; CHECK: [[COPY:%[0-9]+]]:_(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s32) = COPY $d5
    ; CHECK: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[COPY]], [[COPY1]]
    ; CHECK: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[SUB]](s32), [[COPY]]
    ; CHECK: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[COPY1]](s32), [[C]]
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY2]], [[COPY3]]
    ; CHECK: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[XOR]](s32)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY4]], [[C1]]
    ; CHECK: $d4 = COPY [[SUB]](s32)
    ; CHECK: $d5 = COPY [[AND]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s32), %3:_(s1) = G_SSUBO %0, %1
    %4:_(s32) = G_ZEXT %3
    $d4 = COPY %2
    $d5 = COPY %4
...

---
name:            ssubo_s64
body:             |
  bb.1:
    liveins: $e4, $e6

    ; CHECK-LABEL: name: ssubo_s64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:_(s64) = COPY $e6
    ; CHECK: [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; CHECK: [[USUBO:%[0-9]+]]:_(s32), [[USUBO1:%[0-9]+]]:_(s1) = G_USUBO [[UV]], [[UV2]]
    ; CHECK: [[USUBE:%[0-9]+]]:_(s32), [[USUBE1:%[0-9]+]]:_(s1) = G_USUBE [[UV1]], [[UV3]], [[USUBO1]]
    ; CHECK: [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[USUBO]](s32), [[USUBE]](s32)
    ; CHECK: [[C:%[0-9]+]]:_(s64) = G_CONSTANT i64 0
    ; CHECK: [[UV4:%[0-9]+]]:_(s32), [[UV5:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[ICMP:%[0-9]+]]:_(s32) = G_ICMP intpred(slt), [[USUBE]](s32), [[UV5]]
    ; CHECK: [[ICMP1:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[USUBE]](s32), [[UV5]]
    ; CHECK: [[ICMP2:%[0-9]+]]:_(s32) = G_ICMP intpred(ult), [[USUBO]](s32), [[UV4]]
    ; CHECK: [[COPY2:%[0-9]+]]:_(s32) = COPY [[ICMP2]](s32)
    ; CHECK: [[COPY3:%[0-9]+]]:_(s32) = COPY [[ICMP]](s32)
    ; CHECK: [[COPY4:%[0-9]+]]:_(s32) = COPY [[ICMP1]](s32)
    ; CHECK: [[SELECT:%[0-9]+]]:_(s32) = G_SELECT [[COPY4]](s32), [[COPY2]], [[COPY3]]
    ; CHECK: [[UV6:%[0-9]+]]:_(s32), [[UV7:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[COPY1]](s64)
    ; CHECK: [[UV8:%[0-9]+]]:_(s32), [[UV9:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C]](s64)
    ; CHECK: [[ICMP3:%[0-9]+]]:_(s32) = G_ICMP intpred(sgt), [[UV7]](s32), [[UV9]]
    ; CHECK: [[ICMP4:%[0-9]+]]:_(s32) = G_ICMP intpred(eq), [[UV7]](s32), [[UV9]]
    ; CHECK: [[ICMP5:%[0-9]+]]:_(s32) = G_ICMP intpred(ugt), [[UV6]](s32), [[UV8]]
    ; CHECK: [[COPY5:%[0-9]+]]:_(s32) = COPY [[ICMP5]](s32)
    ; CHECK: [[COPY6:%[0-9]+]]:_(s32) = COPY [[ICMP3]](s32)
    ; CHECK: [[COPY7:%[0-9]+]]:_(s32) = COPY [[ICMP4]](s32)
    ; CHECK: [[SELECT1:%[0-9]+]]:_(s32) = G_SELECT [[COPY7]](s32), [[COPY5]], [[COPY6]]
    ; CHECK: [[COPY8:%[0-9]+]]:_(s32) = COPY [[SELECT1]](s32)
    ; CHECK: [[COPY9:%[0-9]+]]:_(s32) = COPY [[SELECT]](s32)
    ; CHECK: [[XOR:%[0-9]+]]:_(s32) = G_XOR [[COPY8]], [[COPY9]]
    ; CHECK: [[C1:%[0-9]+]]:_(s64) = G_CONSTANT i64 1
    ; CHECK: [[ANYEXT:%[0-9]+]]:_(s64) = G_ANYEXT [[XOR]](s32)
    ; CHECK: [[UV10:%[0-9]+]]:_(s32), [[UV11:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[ANYEXT]](s64)
    ; CHECK: [[UV12:%[0-9]+]]:_(s32), [[UV13:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[C1]](s64)
    ; CHECK: [[AND:%[0-9]+]]:_(s32) = G_AND [[UV10]], [[UV12]]
    ; CHECK: [[AND1:%[0-9]+]]:_(s32) = G_AND [[UV11]], [[UV13]]
    ; CHECK: [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[AND]](s32), [[AND1]](s32)
    ; CHECK: $e4 = COPY [[MV]](s64)
    ; CHECK: $e6 = COPY [[MV1]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = COPY $e6
    %2:_(s64), %3:_(s1) = G_SSUBO %0, %1
    %4:_(s64) = G_ZEXT %3
    $e4 = COPY %2
    $e6 = COPY %4
...
