# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_ptrtoint_s32_p0
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    liveins: $a4
    ; CHECK-LABEL: name: test_ptrtoint_s32_p0
    ; CHECK: [[COPY:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[PTRTOINT:%[0-9]+]]:addrregbank(s32) = G_PTRTOINT [[COPY]](p0)
    ; CHECK: $d2 = COPY [[PTRTOINT]](s32)
    %0(p0) = COPY $a4
    %1(s32) = G_PTRTOINT %0
    $d2 = COPY %1(s32)
...

---
name:            test_ptrtoint_s32_p0_explicit_data
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: dataregbank }
  - { id: 2, class: _ }
body: |
  bb.0:
    liveins: $a4
    ; CHECK-LABEL: name: test_ptrtoint_s32_p0_explicit_data
    ; CHECK: [[COPY:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(p0) = COPY [[COPY]](p0)
    ; CHECK: [[COPY2:%[0-9]+]]:addrregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK: [[PTRTOINT:%[0-9]+]]:addrregbank(s32) = G_PTRTOINT [[COPY2]](p0)
    ; CHECK: $d2 = COPY [[PTRTOINT]](s32)
    %0(p0) = COPY $a4
    %1(p0) = COPY %0(p0)
    %2(s32) = G_PTRTOINT %1
    $d2 = COPY %2(s32)
...

---
name:            test_inttoptr_p0_s32
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: test_inttoptr_p0_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[INTTOPTR:%[0-9]+]]:dataregbank(p0) = G_INTTOPTR [[COPY]](s32)
    ; CHECK: $a2 = COPY [[INTTOPTR]](p0)
    %0(s32) = COPY $d4
    %1(p0) = G_INTTOPTR %0
    $a2 = COPY %1(p0)
...

---
name:            test_inttoptr_p0_s32_explicit_addr
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: addrregbank }
  - { id: 2, class: _ }
body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: test_inttoptr_p0_s32_explicit_addr
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:addrregbank(s32) = COPY [[COPY]](s32)
    ; CHECK: [[COPY2:%[0-9]+]]:dataregbank(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[INTTOPTR:%[0-9]+]]:dataregbank(p0) = G_INTTOPTR [[COPY2]](s32)
    ; CHECK: $a2 = COPY [[INTTOPTR]](p0)
    %0(s32) = COPY $d4
    %1(s32) = COPY %0(s32)
    %2(p0) = G_INTTOPTR %1
    $a2 = COPY %2(p0)
...
