# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_freeze_p0
legalized:       true
body: |
  bb.0:
    liveins: $a4
    ; CHECK-LABEL: name: test_freeze_p0
    ; CHECK: [[COPY:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[FREEZE:%[0-9]+]]:addrregbank(p0) = G_FREEZE [[COPY]]
    ; CHECK: $a2 = COPY [[FREEZE]](p0)
    %0:_(p0) = COPY $a4
    %1:_(p0) = G_FREEZE %0
    $a2 = COPY %1(p0)
...

---
name:            test_freeze_s32
legalized:       true
body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: test_freeze_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[FREEZE:%[0-9]+]]:dataregbank(s32) = G_FREEZE [[COPY]]
    ; CHECK: $d2 = COPY [[FREEZE]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = G_FREEZE %0
    $d2 = COPY %1(s32)
...

---
name:            test_freeze_s64
legalized:       true
body: |
  bb.0:
    liveins: $e4
    ; CHECK-LABEL: name: test_freeze_s64
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[FREEZE:%[0-9]+]]:dataregbank(s64) = G_FREEZE [[COPY]]
    ; CHECK: $e2 = COPY [[FREEZE]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s64) = G_FREEZE %0
    $e2 = COPY %1(s64)
...
