# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_fcmp_oeq_s32
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fcmp_oeq_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[FCMP:%[0-9]+]]:dataregbank(s32) = G_FCMP floatpred(oeq), [[COPY]](s32), [[COPY1]]
    ; CHECK: [[C:%[0-9]+]]:dataregbank(s32) = G_CONSTANT i32 1
    ; CHECK: [[AND:%[0-9]+]]:dataregbank(s32) = G_AND [[FCMP]], [[C]]
    ; CHECK: $d2 = COPY [[AND]](s32)
    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32) = G_FCMP floatpred(oeq), %0(s32), %1
    %3(s32) = G_CONSTANT i32 1
    %4(s32) = G_AND %2, %3
    $d2 = COPY %4(s32)
...

---
name:            test_fcmp_oeq_s64
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fcmp_oeq_s64
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s64) = COPY $e6
    ; CHECK: [[FCMP:%[0-9]+]]:dataregbank(s32) = G_FCMP floatpred(oeq), [[COPY]](s64), [[COPY1]]
    ; CHECK: [[C:%[0-9]+]]:dataregbank(s32) = G_CONSTANT i32 1
    ; CHECK: [[AND:%[0-9]+]]:dataregbank(s32) = G_AND [[FCMP]], [[C]]
    ; CHECK: $d2 = COPY [[AND]](s32)
    %0(s64) = COPY $e4
    %1(s64) = COPY $e6
    %2(s32) = G_FCMP floatpred(oeq), %0(s64), %1
    %3(s32) = G_CONSTANT i32 1
    %4(s32) = G_AND %2, %3
    $d2 = COPY %4(s32)
...
