# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            insert_s32_s16
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: insert_s32_s16
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[TRUNC:%[0-9]+]]:dataregbank(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK: [[INSERT:%[0-9]+]]:dataregbank(s32) = G_INSERT [[COPY]], [[TRUNC]](s16), 0
    ; CHECK: $d4 = COPY [[INSERT]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s16) = G_TRUNC %1(s32)
    %3:_(s32) = G_INSERT %0, %2, 0
    $d4 = COPY %3
...

---
name:            insert_p0_s16
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:

    ; CHECK-LABEL: name: insert_p0_s16
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(p0) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[TRUNC:%[0-9]+]]:dataregbank(s16) = G_TRUNC [[COPY1]](s32)
    ; CHECK: [[INSERT:%[0-9]+]]:dataregbank(p0) = G_INSERT [[COPY]], [[TRUNC]](s16), 0
    ; CHECK: $d4 = COPY [[INSERT]](p0)
    %0:_(p0) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s16) = G_TRUNC %1(s32)
    %3:_(p0) = G_INSERT %0, %2, 0
    $d4 = COPY %3
...
