# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_select_p0
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_select_p0
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[COPY2:%[0-9]+]]:addrregbank(p0) = COPY $a5
    ; CHECK: [[COPY3:%[0-9]+]]:dataregbank(p0) = COPY [[COPY1]](p0)
    ; CHECK: [[COPY4:%[0-9]+]]:dataregbank(p0) = COPY [[COPY2]](p0)
    ; CHECK: [[SELECT:%[0-9]+]]:dataregbank(p0) = G_SELECT [[COPY]](s32), [[COPY3]], [[COPY4]]
    ; CHECK: $a2 = COPY [[SELECT]](p0)
    %0(s32) = COPY $d4
    %1(p0) = COPY $a4
    %2(p0) = COPY $a5
    %3(p0) = G_SELECT %0(s32), %1, %2
    $a2 = COPY %3(p0)
...

---
name:            test_select_s32
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_select_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[COPY2:%[0-9]+]]:dataregbank(s32) = COPY $d6
    ; CHECK: [[SELECT:%[0-9]+]]:dataregbank(s32) = G_SELECT [[COPY]](s32), [[COPY1]], [[COPY2]]
    ; CHECK: $d2 = COPY [[SELECT]](s32)
    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32) = COPY $d6
    %3(s32) = G_SELECT %0(s32), %1, %2
    $d2 = COPY %3(s32)
...
