# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name: fpext_f16_to_f32
legalized: true

body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: fpext_f16_to_f32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[TRUNC:%[0-9]+]]:dataregbank(s16) = G_TRUNC [[COPY]](s32)
    ; CHECK: [[FPEXT:%[0-9]+]]:dataregbank(s32) = G_FPEXT [[TRUNC]](s16)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_TRUNC %0
    %2:_(s32) = G_FPEXT %1
...

---
name: fpext_f32_to_f64
legalized: true

body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: fpext_f32_to_f64
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[FPEXT:%[0-9]+]]:dataregbank(s64) = G_FPEXT [[COPY]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s64) = G_FPEXT %0
...

---
name: fptrunc_f64_to_f32
legalized: true

body: |
  bb.0:
    liveins: $e4
    ; CHECK-LABEL: name: fptrunc_f64_to_f32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[FPTRUNC:%[0-9]+]]:dataregbank(s32) = G_FPTRUNC [[COPY]](s64)
    %0:_(s64) = COPY $e4
    %1:_(s32) = G_FPTRUNC %0
...

---
name: fptrunc_f32_to_f16
legalized: true

body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: fptrunc_f32_to_f16
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[FPTRUNC:%[0-9]+]]:dataregbank(s16) = G_FPTRUNC [[COPY]](s32)
    %0:_(s32) = COPY $d4
    %1:_(s16) = G_FPTRUNC %0
...
