# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_merge
legalized:         true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
body:             |
  bb.0.entry:
    liveins: $a4, $d4
    ; CHECK-LABEL: name: test_merge
    ; CHECK: liveins: $a4, $d4
    ; CHECK: [[COPY:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[MV:%[0-9]+]]:dataregbank(s64) = G_MERGE_VALUES [[COPY1]](s32), [[COPY1]](s32)
    ; CHECK: [[MV1:%[0-9]+]]:dataregbank(s64) = G_MERGE_VALUES [[COPY]](p0), [[COPY]](p0)
    ; CHECK: $e2 = COPY [[MV]](s64)
    ; CHECK: $e2 = COPY [[MV1]](s64)
    %0(p0) = COPY $a4
    %1(s32) = COPY $d4
    %2(s64) = G_MERGE_VALUES %1(s32), %1(s32)
    %3(s64) = G_MERGE_VALUES %0(p0), %0(p0)
    $e2 = COPY %2(s64)
    $e2 = COPY %3(s64)
...

---
name:            test_unmerge
legalized:         true
tracksRegLiveness: true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
body:             |
  bb.0.entry:
    liveins: $e4
    ; CHECK-LABEL: name: test_unmerge
    ; CHECK: liveins: $e4
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[UV:%[0-9]+]]:dataregbank(s32), [[UV1:%[0-9]+]]:dataregbank(s32) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: [[UV2:%[0-9]+]]:addrregbank(p0), [[UV3:%[0-9]+]]:addrregbank(p0) = G_UNMERGE_VALUES [[COPY]](s64)
    ; CHECK: $d2 = COPY [[UV]](s32)
    ; CHECK: $d3 = COPY [[UV1]](s32)
    ; CHECK: $a2 = COPY [[UV2]](p0)
    ; CHECK: $a3 = COPY [[UV3]](p0)
    %0(s64) = COPY $e4
    %1(s32), %2(s32) = G_UNMERGE_VALUES %0(s64)
    %3(p0), %4(p0) = G_UNMERGE_VALUES %0(s64)
    $d2 = COPY %1(s32)
    $d3 = COPY %2(s32)
    $a2 = COPY %3(p0)
    $a3 = COPY %4(p0)
...
