# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -global-isel -regbankselect-greedy -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_ptr_add_dataregbank
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_ptr_add_dataregbank
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(p0) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[PTR_ADD:%[0-9]+]]:dataregbank(p0) = G_PTR_ADD [[COPY]], [[COPY1]](s32)
    ; CHECK: $d2 = COPY [[PTR_ADD]](p0)
    %0(p0) = COPY $d4
    %1(s32) = COPY $d5
    %2(p0) = G_PTR_ADD %0, %1
    $d2 = COPY %2
...

---
name:            test_ptr_add_addrregbank
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_ptr_add_addrregbank
    ; CHECK: [[COPY:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:addrregbank(s32) = COPY $a5
    ; CHECK: [[PTR_ADD:%[0-9]+]]:addrregbank(p0) = G_PTR_ADD [[COPY]], [[COPY1]](s32)
    ; CHECK: $a2 = COPY [[PTR_ADD]](p0)
    %0(p0) = COPY $a4
    %1(s32) = COPY $a5
    %2(p0) = G_PTR_ADD %0, %1
    $a2 = COPY %2
...

---
name:            test_ptr_add_default
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_ptr_add_default
    ; CHECK: [[COPY:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[COPY2:%[0-9]+]]:addrregbank(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[PTR_ADD:%[0-9]+]]:addrregbank(p0) = G_PTR_ADD [[COPY]], [[COPY2]](s32)
    ; CHECK: $a2 = COPY [[PTR_ADD]](p0)
    %0(p0) = COPY $a4
    %1(s32) = COPY $d5
    %2(p0) = G_PTR_ADD %0, %1
    $a2 = COPY %2
...
