# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---

name:            test_add
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_add
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[ADD:%[0-9]+]]:dataregbank(s32) = G_ADD [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_ADD %0, %0
...

---
name:            test_add_with_carry
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
  - { id: 5, class: _ }
  - { id: 6, class: _ }
  - { id: 7, class: _ }
  - { id: 8, class: _ }
  - { id: 9, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_add_with_carry
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[UADDO:%[0-9]+]]:dataregbank(s32), [[UADDO1:%[0-9]+]]:statusregbank(s1) = G_UADDO [[COPY]], [[COPY]]
    ; CHECK: [[UADDE:%[0-9]+]]:dataregbank(s32), [[UADDE1:%[0-9]+]]:statusregbank(s1) = G_UADDE [[COPY1]], [[COPY1]], [[UADDO1]]
    ; CHECK: $d2 = COPY [[UADDE]](s32)
    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32), %3(s1) = G_UADDO %0, %0
    %4(s32), %5(s1) = G_UADDE %1, %1, %3
    $d2 = COPY %4(s32)
...

---
name:            test_sub
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_sub
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[SUB:%[0-9]+]]:dataregbank(s32) = G_SUB [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_SUB %0, %0
...

---
name:            test_sub_with_carry
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
  - { id: 3, class: _ }
  - { id: 4, class: _ }
  - { id: 5, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_sub_with_carry
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[USUBO:%[0-9]+]]:dataregbank(s32), [[USUBO1:%[0-9]+]]:statusregbank(s1) = G_USUBO [[COPY]], [[COPY]]
    ; CHECK: [[USUBE:%[0-9]+]]:dataregbank(s32), [[USUBE1:%[0-9]+]]:statusregbank(s1) = G_USUBE [[COPY1]], [[COPY1]], [[USUBO1]]
    ; CHECK: $d2 = COPY [[USUBE]](s32)
    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32), %3(s1) = G_USUBO %0, %0
    %4(s32), %5(s1) = G_USUBE %1, %1, %3
    $d2 = COPY %4(s32)
...

---
name:            test_and
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_and
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[AND:%[0-9]+]]:dataregbank(s32) = G_AND [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_AND %0, %0
...

---
name:            test_or
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_or
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[OR:%[0-9]+]]:dataregbank(s32) = G_OR [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_OR %0, %0
...

---
name:            test_xor
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_xor
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[XOR:%[0-9]+]]:dataregbank(s32) = G_XOR [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_XOR %0, %0
...

---

name:            test_ptr_add
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
  - { id: 2, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_ptr_add
    ; CHECK: [[COPY:%[0-9]+]]:addrregbank(p0) = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY2:%[0-9]+]]:addrregbank(s32) = COPY [[COPY1]](s32)
    ; CHECK: [[PTR_ADD:%[0-9]+]]:addrregbank(p0) = G_PTR_ADD [[COPY]], [[COPY2]](s32)
    %0(p0) = COPY $a4
    %1(s32) = COPY $d4
    %2(p0) = G_PTR_ADD %0, %1
...

---
name:            test_mul
legalized:       true
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: test_mul
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregbank(s32) = COPY $d5
    ; CHECK: [[MUL:%[0-9]+]]:dataregbank(s32) = G_MUL [[COPY]], [[COPY1]]
    ; CHECK: $d2 = COPY [[MUL]](s32)
    ; CHECK: RET implicit $a11, implicit $d2
    %0:_(s32) = COPY $d4
    %1:_(s32) = COPY $d5
    %2:_(s32) = G_MUL %0, %1
    $d2 = COPY %2(s32)
    RET implicit $a11, implicit $d2
...

---

name:            test_umulh
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_umulh
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[UMULH:%[0-9]+]]:dataregbank(s32) = G_UMULH [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_UMULH %0, %0
...

---

name:            test_smulh
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_smulh
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[SMULH:%[0-9]+]]:dataregbank(s32) = G_SMULH [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_SMULH %0, %0
...

---
name:            test_sdiv
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_sdiv
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[SDIV:%[0-9]+]]:dataregbank(s32) = G_SDIV [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_SDIV %0, %0
...

---
name:            test_srem
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_srem
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[SREM:%[0-9]+]]:dataregbank(s32) = G_SREM [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_SREM %0, %0
...

---
name:            test_udiv
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_udiv
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[UDIV:%[0-9]+]]:dataregbank(s32) = G_UDIV [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_UDIV %0, %0
...

---
name:            test_urem
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_urem
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[UREM:%[0-9]+]]:dataregbank(s32) = G_UREM [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_UREM %0, %0
...

---
name:            test_fadd_f32
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fadd_f32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[FADD:%[0-9]+]]:dataregbank(s32) = G_FADD [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_FADD %0, %0
...

---
name:            test_fadd_f64
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fadd_f64
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[FADD:%[0-9]+]]:dataregbank(s64) = G_FADD [[COPY]], [[COPY]]
    %0(s64) = COPY $e4
    %1(s64) = G_FADD %0, %0
...

---
name:            test_fsub_f32
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fsub_f32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[FSUB:%[0-9]+]]:dataregbank(s32) = G_FSUB [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_FSUB %0, %0
...

---
name:            test_fsub_f64
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fsub_f64
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[FSUB:%[0-9]+]]:dataregbank(s64) = G_FSUB [[COPY]], [[COPY]]
    %0(s64) = COPY $e4
    %1(s64) = G_FSUB %0, %0
...

---
name:            test_fmul_f32
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fmul_f32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[FMUL:%[0-9]+]]:dataregbank(s32) = G_FMUL [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_FMUL %0, %0
...

---
name:            test_fmul_f64
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fmul_f64
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[FMUL:%[0-9]+]]:dataregbank(s64) = G_FMUL [[COPY]], [[COPY]]
    %0(s64) = COPY $e4
    %1(s64) = G_FMUL %0, %0
...

---
name:            test_fdiv_f32
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fdiv_f32
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s32) = COPY $d4
    ; CHECK: [[FDIV:%[0-9]+]]:dataregbank(s32) = G_FDIV [[COPY]], [[COPY]]
    %0(s32) = COPY $d4
    %1(s32) = G_FDIV %0, %0
...

---
name:            test_fdiv_f64
legalized:       true
registers:
  - { id: 0, class: _ }
  - { id: 1, class: _ }
body: |
  bb.0:
    ; CHECK-LABEL: name: test_fdiv_f64
    ; CHECK: [[COPY:%[0-9]+]]:dataregbank(s64) = COPY $e4
    ; CHECK: [[FDIV:%[0-9]+]]:dataregbank(s64) = G_FDIV [[COPY]], [[COPY]]
    %0(s64) = COPY $e4
    %1(s64) = G_FDIV %0, %0
...
