# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s


---
name: fpext_f16_to_f32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: fpext_f16_to_f32
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[FTOHP_dd:%[0-9]+]]:dataregs = FTOHP_dd [[COPY]], implicit-def $psw, implicit $psw
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[FTOHP_dd]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s32) = COPY $d4
    %1:dataregbank(s16) = G_FPTRUNC %0
    %2:dataregbank(s32) = G_FPEXT %1
    $d2 = COPY %2(s32)
...

---
name: fpext_f32_to_f64
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: fpext_f32_to_f64
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[FTODF_ed:%[0-9]+]]:extdataregs = FTODF_ed [[COPY]], implicit-def $psw
    ; CHECK: $e2 = COPY [[FTODF_ed]]
    %0:dataregbank(s32) = COPY $d4
    %1:dataregbank(s64) = G_FPEXT %0
    $e2 = COPY %1(s64)
...

---
name: fptrunc_f64_to_f32
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $e4
    ; CHECK-LABEL: name: fptrunc_f64_to_f32
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[DFTOF_de:%[0-9]+]]:dataregs = DFTOF_de [[COPY]], implicit-def $psw, implicit $psw
    ; CHECK: $d2 = COPY [[DFTOF_de]]
    %0:dataregbank(s64) = COPY $e4
    %1:dataregbank(s32) = G_FPTRUNC %0
    $d2 = COPY %1(s32)
...

---
name: fptrunc_f32_to_f16
legalized: true
regBankSelected: true

body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: fptrunc_f32_to_f16
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[FTOHP_dd:%[0-9]+]]:dataregs = FTOHP_dd [[COPY]], implicit-def $psw, implicit $psw
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[FTOHP_dd]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s32) = COPY $d4
    %1:dataregbank(s16) = G_FPTRUNC %0
    %2:dataregbank(s32) = G_FPEXT %1
    $d2 = COPY %2(s32)
...
