# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            sitofp_s32_s32
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $d4

    ; CHECK-LABEL: name: sitofp_s32_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[ITOF_dd:%[0-9]+]]:dataregs = ITOF_dd [[COPY]], implicit-def $psw, implicit $psw
    ; CHECK: $d4 = COPY [[ITOF_dd]]
    %0(s32) = COPY $d4
    %1(s32) = G_SITOFP %0
    $d4 = COPY %1(s32)
...

---
name:            sitofp_s64_s32
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $e4

    ; CHECK-LABEL: name: sitofp_s64_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[ITODF_ed:%[0-9]+]]:extdataregs = ITODF_ed [[COPY]], implicit-def $psw, implicit $psw
    ; CHECK: $e4 = COPY [[ITODF_ed]]
    %0(s32) = COPY $d4
    %1(s64) = G_SITOFP %0
    $e4 = COPY %1(s64)
...

---
name:            sitofp_s64_s64
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $e4

    ; CHECK-LABEL: name: sitofp_s64_s64
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[LTODF_ee:%[0-9]+]]:extdataregs = LTODF_ee [[COPY]], implicit-def $psw, implicit $psw
    ; CHECK: $e4 = COPY [[LTODF_ee]]
    %0(s64) = COPY $e4
    %1(s64) = G_SITOFP %0
    $e4 = COPY %1(s64)
...
