# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=instruction-select \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name:            fptosi_s32_s32
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $d4

    ; CHECK-LABEL: name: fptosi_s32_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[FTOIZ_dd:%[0-9]+]]:dataregs = FTOIZ_dd [[COPY]], implicit-def $psw
    ; CHECK: $d4 = COPY [[FTOIZ_dd]]
    %0(s32) = COPY $d4
    %1(s32) = G_FPTOSI %0
    $d4 = COPY %1(s32)
...

---
name:            fptosi_s32_s64
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $e4

    ; CHECK-LABEL: name: fptosi_s32_s64
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[DFTOIZ_de:%[0-9]+]]:dataregs = DFTOIZ_de [[COPY]], implicit-def $psw
    ; CHECK: $d4 = COPY [[DFTOIZ_de]]
    %0(s64) = COPY $e4
    %1(s32) = G_FPTOSI %0
    $d4 = COPY %1(s32)
...

---
name:            fptosi_s64_s64
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $e4

    ; CHECK-LABEL: name: fptosi_s64_s64
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[DFTOLZ_ee:%[0-9]+]]:extdataregs = DFTOLZ_ee [[COPY]], implicit-def $psw
    ; CHECK: $e4 = COPY [[DFTOLZ_ee]]
    %0(s64) = COPY $e4
    %1(s64) = G_FPTOSI %0
    $e4 = COPY %1(s64)
...
