# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -global-isel -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            fcopysign_s32
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }
  - { id: 2, class: dataregbank }

body:             |
  bb.0:
    liveins: $d4, $d5

    ; CHECK-LABEL: name: fcopysign_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregs = COPY $d5
    ; CHECK: [[INST_ddcdc:%[0-9]+]]:dataregs = INST_ddcdc [[COPY]], 31, [[COPY1]], 31
    ; CHECK: $d4 = COPY [[INST_ddcdc]]
    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32) = G_FCOPYSIGN %0, %1
    $d4 = COPY %2(s32)
...

---
name:            fcopysign_s64
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }
  - { id: 2, class: dataregbank }

body:             |
  bb.0:
    liveins: $e4, $e6

    ; CHECK-LABEL: name: fcopysign_s64
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:extdataregs = COPY $e6
    ; CHECK: [[COPY2:%[0-9]+]]:dataregs = COPY [[COPY1]].dsub1
    ; CHECK: [[COPY3:%[0-9]+]]:dataregs = COPY [[COPY]].dsub1
    ; CHECK: [[INST_ddcdc:%[0-9]+]]:dataregs = INST_ddcdc [[COPY3]], 31, [[COPY2]], 31
    ; CHECK: [[INSERT_SUBREG:%[0-9]+]]:extdataregs = INSERT_SUBREG [[COPY]], [[INST_ddcdc]], %subreg.dsub1
    ; CHECK: $e4 = COPY [[INSERT_SUBREG]]
    %0(s64) = COPY $e4
    %1(s64) = COPY $e6
    %2(s64) = G_FCOPYSIGN %0, %1
    $e4 = COPY %2(s64)
...
