# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_merge
legalized:         true
regBankSelected:   true
tracksRegLiveness: true
registers:
  - { id: 0, class: addrregbank }
  - { id: 1, class: dataregbank }
  - { id: 2, class: dataregbank }
  - { id: 3, class: dataregbank }
body:             |
  bb.0.entry:
    liveins: $a4, $d4
    ; CHECK-LABEL: name: test_merge
    ; CHECK: liveins: $a4, $d4
    ; CHECK: [[COPY:%[0-9]+]]:addrregs = COPY $a4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[REG_SEQUENCE:%[0-9]+]]:extdataregs = REG_SEQUENCE [[COPY1]], %subreg.dsub0, [[COPY1]], %subreg.dsub1
    ; CHECK: [[REG_SEQUENCE1:%[0-9]+]]:extdataregs = REG_SEQUENCE [[COPY]], %subreg.dsub0, [[COPY]], %subreg.dsub1
    ; CHECK: $e2 = COPY [[REG_SEQUENCE]]
    ; CHECK: $e2 = COPY [[REG_SEQUENCE1]]
    %0(p0) = COPY $a4
    %1(s32) = COPY $d4
    %2(s64) = G_MERGE_VALUES %1(s32), %1(s32)
    %3(s64) = G_MERGE_VALUES %0(p0), %0(p0)
    $e2 = COPY %2
    $e2 = COPY %3
...

---
name:            test_unmerge
legalized:         true
regBankSelected:   true
tracksRegLiveness: true
registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }
  - { id: 2, class: dataregbank }
  - { id: 3, class: addrregbank }
  - { id: 4, class: addrregbank }
body:             |
  bb.0.entry:
    liveins: $a4, $e4
    ; CHECK-LABEL: name: test_unmerge
    ; CHECK: liveins: $a4, $e4
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregs = COPY [[COPY]].dsub0
    ; CHECK: [[COPY2:%[0-9]+]]:dataregs = COPY [[COPY]].dsub1
    ; CHECK: [[COPY3:%[0-9]+]]:addrregs = COPY [[COPY]].dsub0
    ; CHECK: [[COPY4:%[0-9]+]]:addrregs = COPY [[COPY]].dsub1
    ; CHECK: $d2 = COPY [[COPY1]]
    ; CHECK: $d3 = COPY [[COPY2]]
    ; CHECK: $a2 = COPY [[COPY3]]
    ; CHECK: $a3 = COPY [[COPY4]]
    %0(s64) = COPY $e4
    %1(s32), %2(s32) = G_UNMERGE_VALUES %0(s64)
    %3(p0), %4(p0) = G_UNMERGE_VALUES %0(s64)
    $d2 = COPY %1(s32)
    $d3 = COPY %2(s32)
    $a2 = COPY %3(p0)
    $a3 = COPY %4(p0)
...
