# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -global-isel -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            select_i32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }
  - { id: 2, class: dataregbank }
  - { id: 3, class: dataregbank }
body:             |
  bb.0:
    ; CHECK-LABEL: name: select_i32
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:dataregs = COPY $d5
    ; CHECK: [[COPY2:%[0-9]+]]:dataregs = COPY $d6
    ; CHECK: [[SEL_dddd:%[0-9]+]]:dataregs = SEL_dddd [[COPY]], [[COPY1]], [[COPY2]]
    ; CHECK: $d2 = COPY [[SEL_dddd]]
    %0(s32) = COPY $d4
    %1(s32) = COPY $d5
    %2(s32) = COPY $d6
    %3(s32) = G_SELECT %0(s32), %1, %2
    $d2 = COPY %3
...

---
name:            select_p0
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: addrregbank }
  - { id: 2, class: addrregbank }
  - { id: 3, class: dataregbank }
  - { id: 4, class: dataregbank }
  - { id: 5, class: dataregbank }
  - { id: 6, class: addrregbank }
body:             |
  bb.0:
    ; CHECK-LABEL: name: select_p0
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[COPY1:%[0-9]+]]:addrregs = COPY $a5
    ; CHECK: [[COPY2:%[0-9]+]]:addrregs = COPY $a6
    ; CHECK: [[COPY3:%[0-9]+]]:dataregs = COPY [[COPY1]]
    ; CHECK: [[COPY4:%[0-9]+]]:dataregs = COPY [[COPY2]]
    ; CHECK: [[SEL_dddd:%[0-9]+]]:dataregs = SEL_dddd [[COPY]], [[COPY3]], [[COPY4]]
    ; CHECK: [[COPY5:%[0-9]+]]:addrregs = COPY [[SEL_dddd]]
    ; CHECK: $a2 = COPY [[COPY5]]
    %0(s32) = COPY $d4
    %1(p0) = COPY $a5
    %2(p0) = COPY $a6
    %3(p0) = COPY %1(p0)
    %4(p0) = COPY %2(p0)
    %5(p0) = G_SELECT %0(s32), %3, %4
    %6(p0) = COPY %5(p0)
    $a2 = COPY %6
...
