# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=instruction-select \
# RUN:   -verify-machineinstrs %s -o - | FileCheck %s

---
name:            fptoui_s32_s32
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $d4

    ; CHECK-LABEL: name: fptoui_s32_s32
    ; CHECK: [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK: [[FTOUZ_dd:%[0-9]+]]:dataregs = FTOUZ_dd [[COPY]], implicit-def $psw
    ; CHECK: $d4 = COPY [[FTOUZ_dd]]
    %0(s32) = COPY $d4
    %1(s32) = G_FPTOUI %0
    $d4 = COPY %1(s32)
...

---
name:            fptoui_s32_s64
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $e4

    ; CHECK-LABEL: name: fptoui_s32_s64
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[DFTOUZ_de:%[0-9]+]]:dataregs = DFTOUZ_de [[COPY]], implicit-def $psw
    ; CHECK: $d4 = COPY [[DFTOUZ_de]]
    %0(s64) = COPY $e4
    %1(s32) = G_FPTOUI %0
    $d4 = COPY %1(s32)
...

---
name:            fptoui_s64_s64
legalized:       true
regBankSelected: true

registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }

body:             |
  bb.0:
    liveins: $e4

    ; CHECK-LABEL: name: fptoui_s64_s64
    ; CHECK: [[COPY:%[0-9]+]]:extdataregs = COPY $e4
    ; CHECK: [[DFTOULZ_ee:%[0-9]+]]:extdataregs = DFTOULZ_ee [[COPY]], implicit-def $psw
    ; CHECK: $e4 = COPY [[DFTOULZ_ee]]
    %0(s64) = COPY $e4
    %1(s64) = G_FPTOUI %0
    $e4 = COPY %1(s64)
...
