# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=tricore -global-isel -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            test_ptrtoint_addr_addr
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
  - { id: 1, class: addrregbank }
body: |
  bb.0:
    liveins: $a4
    ; CHECK-LABEL: name: test_ptrtoint_addr_addr
    ; CHECK:      [[COPY:%[0-9]+]]:addrregs = COPY $a4
    ; CHECK-NEXT: $a2 = COPY [[COPY]]
    %0(p0) = COPY $a4
    %1(s32) = G_PTRTOINT %0
    $a2 = COPY %1(s32)
...

---
name:            test_ptrtoint_data_data
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }
body: |
  bb.0:
    liveins: $a4
    ; CHECK-LABEL: name: test_ptrtoint_data_data
    ; CHECK:      [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK-NEXT: $d2 = COPY [[COPY]]
    %0(p0) = COPY $d4
    %1(s32) = G_PTRTOINT %0
    $d2 = COPY %1(s32)
...

---
name:            test_ptrtoint_addr_data
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
  - { id: 1, class: dataregbank }
body: |
  bb.0:
    liveins: $a4
    ; CHECK-LABEL: name: test_ptrtoint_addr_data
    ; CHECK:      [[COPY:%[0-9]+]]:addrregs = COPY $a4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:dataregs = COPY [[COPY]]
    ; CHECK-NEXT: $d2 = COPY [[COPY1]]
    %0(p0) = COPY $a4
    %1(s32) = G_PTRTOINT %0
    $d2 = COPY %1(s32)
...

---
name:            test_ptrtoint_data_addr
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: addrregbank }
body: |
  bb.0:
    liveins: $a4
    ; CHECK-LABEL: name: test_ptrtoint_data_addr
    ; CHECK:      [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:addrregs = COPY [[COPY]]
    ; CHECK-NEXT: $a2 = COPY [[COPY1]]
    %0(p0) = COPY $d4
    %1(s32) = G_PTRTOINT %0
    $a2 = COPY %1(s32)
...

---
name:            test_inttoptr_addr_addr
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
  - { id: 1, class: addrregbank }
body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: test_inttoptr_addr_addr
    ; CHECK:      [[COPY:%[0-9]+]]:addrregs = COPY $a4
    ; CHECK-NEXT: $a2 = COPY [[COPY]]
    %0(s32) = COPY $a4
    %1(p0) = G_INTTOPTR %0
    $a2 = COPY %1(p0)
...

---
name:            test_inttoptr_data_data
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: dataregbank }
body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: test_inttoptr_data_data
    ; CHECK:      [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK-NEXT: $a2 = COPY [[COPY]]
    %0(s32) = COPY $d4
    %1(p0) = G_INTTOPTR %0
    $a2 = COPY %1(p0)
...

---
name:            test_inttoptr_addr_data
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
  - { id: 1, class: dataregbank }
body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: test_inttoptr_addr_data
    ; CHECK:      [[COPY:%[0-9]+]]:addrregs = COPY $a4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:dataregs = COPY [[COPY]]
    ; CHECK-NEXT: $d2 = COPY [[COPY1]]
    %0(s32) = COPY $a4
    %1(p0) = G_INTTOPTR %0
    $d2 = COPY %1(p0)
...

---
name:            test_inttoptr_data_addr
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
  - { id: 1, class: addrregbank }
body: |
  bb.0:
    liveins: $d4
    ; CHECK-LABEL: name: test_inttoptr_data_addr
    ; CHECK:      [[COPY:%[0-9]+]]:dataregs = COPY $d4
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:addrregs = COPY [[COPY]]
    ; CHECK-NEXT: $a2 = COPY [[COPY1]]
    %0(s32) = COPY $d4
    %1(p0) = G_INTTOPTR %0
    $a2 = COPY %1(p0)
...
