# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -global-isel -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

--- |
  define void @test_constant_s32() {
  entry:
    ret void
  }
  define void @test_constant_small_s32() {
  entry:
    ret void
  }
  define void @test_constant_negative_s32() {
  entry:
    ret void
  }
  define void @test_constant_s64() {
  entry:
    ret void
  }
  define void @test_constant_small_s64() {
  entry:
    ret void
  }
  define void @test_constant_negative_s64() {
  entry:
    ret void
  }
  define void @test_constant_nullptr_p0() {
  entry:
    ret void
  }
  define void @test_constant_p0() {
  entry:
    ret void
  }
  define void @test_fconst_s16() {
  entry:
    ret void
  }
  define void @test_fconst_s32() {
  entry:
    ret void
  }
  define void @test_fconst_s64() {
  entry:
    ret void
  }
  define void @test_fconst_s16_0() {
  entry:
    ret void
  }
  define void @test_fconst_s32_0() {
  entry:
    ret void
  }
  define void @test_fconst_s64_0() {
  entry:
    ret void
  }
  define void @test_fconstant_negative_s16() {
  entry:
    ret void
  }
  define void @test_fconstant_negative_s32() {
  entry:
    ret void
  }
  define void @test_fconstant_negative_s64() {
  entry:
    ret void
  }
  define void @test_fconstant_infinity_s16() {
  entry:
    ret void
  }
  define void @test_fconstant_infinity_s32() {
  entry:
    ret void
  }
  define void @test_fconstant_infinity_s64() {
  entry:
    ret void
  }
  define void @test_fconstant_negative_infinity_s16() {
  entry:
    ret void
  }
  define void @test_fconstant_negative_infinity_s32() {
  entry:
    ret void
  }
  define void @test_fconstant_negative_infinity_s64() {
  entry:
    ret void
  }
  define void @test_fconstant_nan_s16() {
  entry:
    ret void
  }
  define void @test_fconstant_nan_s32() {
  entry:
    ret void
  }
  define void @test_fconstant_nan_s64() {
  entry:
    ret void
  }
  @var = global i8 0
  define i8* @test_global() {
  entry:
    ret i8* undef
  }
  define void @test_constant_p0_dataregs() {
  entry:
    ret void
  }
  define void @test_constant_s32_addregs() {
  entry:
    ret void
  }
  define void @test_constant_f32_addregs() {
  entry:
    ret void
  }
...

---
name:            test_constant_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 1234567890
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0(s32) = G_CONSTANT i32 1234567890
    $d2 = COPY %0(s32)
...

---
name:            test_constant_small_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_small_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 42
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0(s32) = G_CONSTANT i32 42
    $d2 = COPY %0(s32)
...
---
name:            test_constant_negative_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_negative_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 4294967295
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0(s32) = G_CONSTANT i32 -1
    $d2 = COPY %0(s32)
...

---
name:            test_constant_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg -6101065172721897295
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0(s64) = G_CONSTANT i64 12345678900987654321
    $e2 = COPY %0(s64)
...

---
name:            test_constant_small_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_small_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg 10
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0(s64) = G_CONSTANT i64 10
    $e2 = COPY %0(s64)
...

---
name:            test_constant_negative_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_negative_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg -1
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0(s64) = G_CONSTANT i64 -1
    $e2 = COPY %0(s64)
...

---
name:            test_constant_nullptr_p0
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_nullptr_p0
    ; CHECK: [[MOVImmAddrReg:%[0-9]+]]:addrregs = MOVImmAddrReg 0
    ; CHECK: $a2 = COPY [[MOVImmAddrReg]]
    %0(p0) = G_CONSTANT i32 0
    $a2 = COPY %0(p0)
...

---
name:            test_constant_p0
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_p0
    ; CHECK: [[MOVImmAddrReg:%[0-9]+]]:addrregs = MOVImmAddrReg 2863311530
    ; CHECK: $a2 = COPY [[MOVImmAddrReg]]
    %0(p0) = G_CONSTANT i32 2863311530
    $a2 = COPY %0(p0)
...

---
name:            test_fconst_s16
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconst_s16
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 16640
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[MOVImmDataReg]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s16) = G_FCONSTANT half 2.5
    %1:dataregbank(s32) = G_FPEXT %0
    $d2 = COPY %1(s32)
...

---
name:            test_fconst_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconst_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 1080033280
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0(s32) = G_FCONSTANT float 3.5
    $d2 = COPY %0(s32)
...

---
name:            test_fconst_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconst_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg 4607182418800017408
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0(s64) = G_FCONSTANT double 1.0
    $e2 = COPY %0(s64)
...

---
name:            test_fconst_s16_0
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconst_s16_0
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 0
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[MOVImmDataReg]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s16) = G_FCONSTANT half 0.0
    %1:dataregbank(s32) = G_FPEXT %0
    $d2 = COPY %1(s32)
...

---
name:            test_fconst_s32_0
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconst_s32_0
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 0
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0(s32) = G_FCONSTANT float 0.0
    $d2 = COPY %0(s32)
...

---
name:            test_fconst_s64_0
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconst_s64_0
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg 0
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0(s64) = G_FCONSTANT double 0.0
    $e2 = COPY %0(s64)
...

---
name:            test_fconstant_negative_s16
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_negative_s16
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 48128
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[MOVImmDataReg]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s16) = G_FCONSTANT half -1.0
    %1:dataregbank(s32) = G_FPEXT %0
    $d2 = COPY %1(s32)
...

---
name:            test_fconstant_negative_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_negative_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 3212836864
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0(s32) = G_FCONSTANT float -1.0
    $d2 = COPY %0(s32)
...

---
name:            test_fconstant_negative_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_negative_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg -4616189618054758400
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0(s64) = G_FCONSTANT double -1.0
    $e2 = COPY %0(s64)
...

---
name:            test_fconstant_infinity_s16
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_infinity_s16
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 31744
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[MOVImmDataReg]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s16) = G_FCONSTANT half 0x7FF0000000000000
    %1:dataregbank(s32) = G_FPEXT %0
    $d2 = COPY %1(s32)
...

---
name:            test_fconstant_infinity_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_infinity_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 2139095040
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0:dataregbank(s32) = G_FCONSTANT float 0x7FF0000000000000
    $d2 = COPY %0(s32)
...

---
name:            test_fconstant_infinity_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_infinity_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg 9218868437227405312
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0:dataregbank(s64) = G_FCONSTANT double 0x7FF0000000000000
    $e2 = COPY %0(s64)
...


---
name:            test_fconstant_negative_infinity_s16
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_negative_infinity_s16
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 64512
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[MOVImmDataReg]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s16) = G_FCONSTANT half 0xFFF0000000000000
    %1:dataregbank(s32) = G_FPEXT %0
    $d2 = COPY %1(s32)
...

---
name:            test_fconstant_negative_infinity_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_negative_infinity_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 4286578688
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0:dataregbank(s32) = G_FCONSTANT float 0xFFF0000000000000
    $d2 = COPY %0(s32)
...

---
name:            test_fconstant_negative_infinity_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_negative_infinity_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg -4503599627370496
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0:dataregbank(s64) = G_FCONSTANT double 0xFFF0000000000000
    $e2 = COPY %0(s64)
...

---
name:            test_fconstant_nan_s16
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_nan_s16
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 32256
    ; CHECK: [[HPTOF_dd:%[0-9]+]]:dataregs = HPTOF_dd [[MOVImmDataReg]], implicit-def $psw
    ; CHECK: $d2 = COPY [[HPTOF_dd]]
    %0:dataregbank(s16) = G_FCONSTANT half 0x7FF8000000000000
    %1:dataregbank(s32) = G_FPEXT %0
    $d2 = COPY %1(s32)
...

---
name:            test_fconstant_nan_s32
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_nan_s32
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 2143289344
    ; CHECK: $d2 = COPY [[MOVImmDataReg]]
    %0:dataregbank(s32) = G_FCONSTANT float 0x7FF8000000000000
    $d2 = COPY %0(s32)
...

---
name:            test_fconstant_nan_s64
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }

body:             |
  bb.0:
    ; CHECK-LABEL: name: test_fconstant_nan_s64
    ; CHECK: [[MOVImmExtDataReg:%[0-9]+]]:extdataregs = MOVImmExtDataReg 9221120237041090560
    ; CHECK: $e2 = COPY [[MOVImmExtDataReg]]
    %0:dataregbank(s64) = G_FCONSTANT double 0x7FF8000000000000
    $e2 = COPY %0(s64)
...

---
name:            test_global
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_global
    ; CHECK: [[MOVHA_ac:%[0-9]+]]:addrregs = MOVHA_ac target-flags(tricore-hi) @var
    ; CHECK: [[LEA_aac:%[0-9]+]]:addrregs = LEA_aac [[MOVHA_ac]], target-flags(tricore-lo) @var
    ; CHECK: $a2 = COPY [[LEA_aac]]
    %0(p0) = G_GLOBAL_VALUE @var
    $a2 = COPY %0(p0)
...

---
name:            test_constant_p0_dataregs
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: dataregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_p0_dataregs
    ; CHECK: [[MOVImmDataReg:%[0-9]+]]:dataregs = MOVImmDataReg 0
    ; CHECK: $a2 = COPY [[MOVImmDataReg]]
    %0(p0) = G_CONSTANT i32 0
    $a2 = COPY %0(p0)
...

---
name:            test_constant_s32_addregs
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_s32_addregs
    ; CHECK: [[MOVImmAddrReg:%[0-9]+]]:addrregs = MOVImmAddrReg 0
    ; CHECK: $a2 = COPY [[MOVImmAddrReg]]
    %0(s32) = G_CONSTANT i32 0
    $a2 = COPY %0(s32)
...

---
name:            test_constant_f32_addregs
legalized:       true
regBankSelected: true
registers:
  - { id: 0, class: addrregbank }
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_constant_f32_addregs
    ; CHECK: [[MOVImmAddrReg:%[0-9]+]]:addrregs = MOVImmAddrReg 0
    ; CHECK: $a2 = COPY [[MOVImmAddrReg]]
    %0(s32) = G_FCONSTANT float 0.0
    $a2 = COPY %0(s32)
...
