# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -run-pass=tricore-expand-pseudo -o - -verify-machineinstrs %s | FileCheck %s

---
name:           test_i32
alignment:       8
tracksRegLiveness: true
machineFunctionInfo: {}
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_i32
    ; CHECK: $d0 = MOVU_dc 32767
    ; CHECK: $d0 = ADDIH_ddc $d0, 65535, implicit-def $psw
    ; CHECK: $d1 = MOV_dc -32768
    ; CHECK: $d2 = MOV_dc 32767
    ; CHECK: $d3 = MOVU_dc 32768
    ; CHECK: $d4 = MOVU_dc 65535
    ; CHECK: $d5 = MOVH_dc 1
    ; CHECK: $d6 = MOVU_dc 1
    ; CHECK: $d6 = ADDIH_ddc $d6, 1, implicit-def $psw
    ; CHECK: $d7 = MOV_dc 0
    ; CHECK: $d8 = MOVH_dc 3
    ; CHECK: $d8 = SH_ddc $d8, -1
    ; CHECK: $d9 = MOVU_dc 65528
    ; CHECK: $d9 = SH_ddc $d9, 1
    ; CHECK: $d10 = MOV_dc -1
    ; CHECK: $d10 = SH_ddc $d10, -15
    ; CHECK: $d11 = MOVH_dc 65535
    ; CHECK: $d11 = SH_ddc $d11, -4
    ; CHECK: $d12 = MOVU_dc 65535
    ; CHECK: $d12 = SH_ddc $d12, 1
    ; CHECK: $d13 = MOV_dc -32768
    $d0 = MOVImmDataReg -32769
    $d1 = MOVImmDataReg -32768
    $d2 = MOVImmDataReg 32767
    $d3 = MOVImmDataReg 32768
    $d4 = MOVImmDataReg 65535
    $d5 = MOVImmDataReg 65536
    $d6 = MOVImmDataReg 65537
    $d7 = MOVImmDataReg 0
    $d8 = MOVImmDataReg 98304
    $d9 = MOVImmDataReg 131056
  ; Edge case: Trailing Zeros: 0 Leading Zeros: 15
    $d10 = MOVImmDataReg 131071
    $d11 = MOVImmDataReg 268431360
    $d12 = MOVImmDataReg 131070
    $d13 = MOVImmDataReg 4294934528
...

---
name:           test_i64
alignment:       8
tracksRegLiveness: true
machineFunctionInfo: {}
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_i64
    ; CHECK: $e0 = MOV_ec -32768
    ; CHECK: $d2 = MOVU_dc 32767
    ; CHECK: $d2 = ADDIH_ddc $d2, 65535, implicit-def $psw
    ; CHECK: $d3 = MOV_dc -1
    $e0 = MOVImmExtDataReg -32768
    $e2 = MOVImmExtDataReg -32769
...

---
name:           test_p0
alignment:       8
tracksRegLiveness: true
machineFunctionInfo: {}
body:             |
  bb.0:

    ; CHECK-LABEL: name: test_p0
    ; CHECK: $a0 = MOVHA_ac 16
    ; CHECK: $a0 = LEA_aac $a0, -1
    ; CHECK: $a1 = LEA_ac 15
    ; CHECK: $a2 = LEA_ac 16
    $a0 = MOVImmAddrReg 1048575
  ; Make sure we do not select MOVA_16_ac here, since that is the job of our
  ; compression backend
    $a1 = MOVImmAddrReg 15
    $a2 = MOVImmAddrReg 16
...
