# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tricore -run-pass=tricore-expand-pseudo -o - -verify-machineinstrs %s | FileCheck %s

---
name:           test_i32
alignment:       8
tracksRegLiveness: true
machineFunctionInfo: {}
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_i32
    ; CHECK: $d0 = MOVU_dc 32767
    ; CHECK: dead $d0 = ADDIH_ddc $d0, 65535, implicit-def $psw
    ; CHECK: dead $d1 = MOV_dc -32768
    ; CHECK: dead $d2 = MOVU_dc 32768
    ; CHECK: dead $d3 = MOVH_dc 1
    ; CHECK: $d4 = MOVH_dc 3
    ; CHECK: dead $d4 = SH_ddc $d4, -1
    ; CHECK: $d5 = MOVU_dc 65528
    ; CHECK: dead $d5 = SH_ddc $d5, 1
    ; CHECK: $d6 = MOVU_dc 65535
    ; CHECK: dead $d6 = SH_ddc $d6, 1
    dead $d0 = MOVImmDataReg -32769
    dead $d1 = MOVImmDataReg -32768
    dead $d2 = MOVImmDataReg 32768
    dead $d3 = MOVImmDataReg 65536
    dead $d4 = MOVImmDataReg 98304
    dead $d5 = MOVImmDataReg 131056
    dead $d6 = MOVImmDataReg 131070
...

---
name:           test_i64
alignment:       8
tracksRegLiveness: true
machineFunctionInfo: {}
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_i64
    ; CHECK: dead $e0 = MOV_ec -32768
    ; CHECK: $d2 = MOVU_dc 32767
    ; CHECK: dead $d2 = ADDIH_ddc $d2, 65535, implicit-def $psw
    ; CHECK: dead $d3 = MOV_dc -1
    ; CHECK: $d4 = MOVU_dc 61166
    ; CHECK: dead $d4 = ADDIH_ddc $d4, 61166, implicit-def $psw
    ; CHECK: $d5 = MOVU_dc 61166
    ; CHECK: dead $d5 = ADDIH_ddc $d5, 32494, implicit-def $psw
    dead $e0 = MOVImmExtDataReg -32768
    ; make sure the sub-registers are marked dead correctly
    dead $e2 = MOVImmExtDataReg -32769
    dead $e4 = MOVImmExtDataReg 9146510603214319342
...

---
name:           test_p0
alignment:       8
tracksRegLiveness: true
machineFunctionInfo: {}
body:             |
  bb.0:
    ; CHECK-LABEL: name: test_p0
    ; CHECK: $a0 = MOVHA_ac 16
    ; CHECK: dead $a0 = LEA_aac $a0, -1
    ; CHECK: dead $a1 = LEA_ac 15
    dead $a0 = MOVImmAddrReg 1048575
    dead $a1 = MOVImmAddrReg 15
...
