# RUN: llvm-mc %s -triple=tricore -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK,CHECK-INST %s

# CHECK-INST: bisr 0
# CHECK: encoding: [0xe0,0x00]
.code16
bisr 0

# CHECK-INST: bisr 1
# CHECK: encoding: [0xe0,0x01]
.code16
bisr 1

# CHECK-INST: bisr 16
# CHECK: encoding: [0xe0,0x10]
.code16
bisr 16

# CHECK-INST: bisr 255
# CHECK: encoding: [0xe0,0xff]
.code16
bisr 255

# CHECK-INST: bisr 271
# CHECK: encoding: [0xad,0xf0,0x10,0x00]
.code32
bisr 271

# CHECK-INST: bisr 496
# CHECK: encoding: [0xad,0x00,0x1f,0x00]
.code32
bisr 496

# CHECK-INST: bisr 511
# CHECK: encoding: [0xad,0xf0,0x1f,0x00]
.code32
bisr 511

# CHECK-INST: rslcx
# CHECK: encoding: [0x0d,0x00,0x40,0x02]
.code32
rslcx 

# CHECK-INST: svlcx
# CHECK: encoding: [0x0d,0x00,0x00,0x02]
.code32
svlcx


### Test if 16 bit instructions are generated by default

# CHECK-INST: bisr 0
# CHECK: encoding: [0xe0,0x00]
bisr 0
 